---
title: "Data management"
bibliography: ../assets/complementary-references.bib
csl: ../assets/apa.csl
nocite: |
  @Wickham2014
---

Effective data management is a cornerstone of rigorous research. It ensures the proper organization, preservation, and sharing of research data, aligning with principles of transparency, reproducibility, and ethical responsibility. This section outlines the key principles and processes for research data management, highlights available tools, and links to relevant guidelines and resources.

## Principles of research data management

Research data management refers to the organization, storage, preservation, and sharing of data collected and used during a research project. This practice is essential to ensure data is:

1. **FAIR**: Findable, Accessible, Interoperable, and Reusable
2. **Secure**: Protected from unauthorized access or loss
3. **Organized**: Clearly structured (see [tidy data](https://www.jstatsoft.org/article/view/v059i10){target=_blank}) and documented for ease of use and understanding
4. **Reproducible**: Ensuring that future researchers can validate results by using the same data

Several principles should guide researchers in managing their data:

- **Data Collection and Documentation**: Ensure accurate and thorough documentation of the data collection process.
- **Data Storage and Security**: Store data securely during the research project, ensuring data integrity and confidentiality.
- **Data Sharing and Accessibility**: Share data in open-access repositories where possible to comply with funder requirements and maximize the impact of your research.
- **Data Archiving and Preservation**: Safeguard data for long-term access and reuse by archiving it in trusted repositories.

For further guidance, see the Science Europe guide on [Research Data Management](https://scienceeurope.org/our-priorities/research-data/research-data-management){target=_blank}.

## Data reuse

::: callout-note
Existing data repositories offer a good starting point to identify datasets that can be reused.
:::

Data repositories:

- [Awesome public datasets](https://github.com/awesomedata/awesome-public-datasets){target=_blank}
- [Stanford Large Network Dataset Collection](https://snap.stanford.edu/data/){target=_blank}

## Data management process

Below is a recommended process structure for managing research data throughout the lifecycle of a project:

1. **Planning stage**
   - Develop a **Data Management Plan (DMP)** that outlines how the data will be collected, stored, and shared.
   - Ensure compliance with institutional and funding body requirements.
   - Identify relevant data policies from your funder or publisher.

2. **Data collection and organization**
   - Establish clear protocols for data collection.
   - Use standardized formats and file naming conventions to ensure consistency and ease of use.
   - Document metadata thoroughly to facilitate future understanding and use of the data.

3. **Data storage and security**
   - Store data in secure, backed-up locations during the project to protect against loss.
   - Ensure that sensitive data is encrypted and access-controlled where necessary.
   - Use platforms like [OSF](https://help.osf.io/article/201-create-a-view-only-link-for-a-project){target=_blank} for project collaboration and version control.

4. **Data sharing and accessibility**
   - Publish data in open-access repositories where possible to comply with funder and publisher requirements (e.g., via [GitHub](https://docs.github.com/de/repositories/archiving-a-github-repository/referencing-and-citing-content){target=_blank} - [Zenodo](https://zenodo.org/){target=_blank}).
   - Add the `dataset` tag to the GitHub repository (see [overview](https://github.com/orgs/digital-work-lab/repositories?q=topic%3Adataset){target=_blank})
   - Create anonymous or view-only links for peer review using tools like [Anonymous GitHub for peer review](https://anonymous.4open.science/){target=_blank} or [OSF anonymous online datasets](https://help.osf.io/article/201-create-a-view-only-link-for-a-project){target=_blank}.
   - Cite data appropriately in publications using DOIs or other identifiers.

5. **Data archiving and preservation**
   - After project completion, archive data in a trusted repository that supports long-term access and preservation.
   - Ensure that your archived data is available under FAIR principles.

## Institutional and funder requirements

Increasingly, institutions and funding bodies require detailed data management plans as part of project proposals. Below are guidelines from key institutions and organizations:

| Institution | Requirements | Further information |
|-------------|---------------|---------------------|
| **German Research Foundation (DFG)** | The DFG provides guidelines on project planning, application processes, and safeguarding data. | [DFG Guidelines on Research Data Management](https://www.dfg.de/en/research_funding/programmes/infrastructure/lis/funding_opportunities/research_data/){target=_blank} |
| **European Union (Horizon 2020)** | The EU requires a DMP and open data policies for projects funded under Horizon 2020. | [Guidelines on Open Access to Scientific Publications and Research Data](https://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-data-mgt_en.pdf){target=_blank} |
| **National Science Foundation (NSF)** | NSF project proposals must include a Data Management Plan to ensure data is appropriately archived and accessible. | [NSF Data Sharing Policy](https://www.nsf.gov/bfa/dias/policy/dmp.jsp){target=_blank} |
| **German Rectors' Conference (HRK)** | HRK offers detailed guidelines for university leaders on establishing robust research data management practices. | [HRK Guidelines](https://www.hrk.de/positionen/beschluss/detail/management-von-forschungsdaten-eine-zentrale-strategische-herausforderung-fuer-hochschulleitungen/){target=_blank} |

## Additional resources

- [Ten Simple Rules for Creating a Good Data Management Plan](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004525){target=_blank}
- [Anonymous GitHub for peer review](https://anonymous.4open.science/){target=_blank}
- [RWTH Aachen FDM](https://www.rwth-aachen.de/cms/root/forschung/forschungsdatenmanagement/erste-schritte/~svay/was-ist-forschungsdaten-management-/?lidx=1){target=_blank}
- [How to share data with a statistician](https://github.com/jtleek/datasharing){target=_blank}
