---
title: "Funding"
transition_status: "toupdate"
transition_comment: "update"
---

## Process

```{mermaid}
flowchart LR
    subgraph pre_award
        Search --> Apply
    end
    
    Apply --> Manage
    
    subgraph post_award
        Manage --> Close
    end
    Close --> Search
```

## Systems

System | Description |
---|---|
[DFG-GEPRIS](https://gepris.dfg.de/gepris/OCTOPUS){: target="_blank"}| - Database of the German Research Foundation (DFG)<br>- Provides information about all DFG-funded research projects<br>- Useful for finding funding opportunities and understanding the scope of funded projects |
[DFG elan Portal](https://elan.dfg.de/my.policy){: target="_blank"}| - Submission of proposals |

## Application

- [Ampelsystem Vertragsgestaltung Drittmittelverträge](https://www.uni-bamberg.de/justitiariat/merkblaetter/){: target="_blank"}
- [Research Data Management](https://www.uni-bamberg.de/ub/forschen-und-publizieren/forschungsdatenmanagement/){: target="_blank"}

- Drittmittelerklärung: Im Downloadcenter des Dezernats Z/FFT ([link](https://www.uni-bamberg.de/fileadmin/fft/dateien/intranet/2024-04-10_Erklaerung_Drittmittelvorhaben.pdf){: target="_blank"})
- Antrag auf DFG-Programmpauschale ([link](https://www.uni-bamberg.de/fileadmin/fft/dateien/intranet/2017-04-04_FormblattDFG-Programmpauschale.pdf){: target="_blank"})
- Übersicht Personalkosten ([link](https://www.uni-bamberg.de/fileadmin/fft/dateien/intranet/2024-04_Personalkosten_Finanzierungsplanung_Arbeitgeber_Brutto_FINAL.pdf){: target="_blank"})
- Diese und viele weitere Informationen finden Sie auf unserer Webseite und insb. ([link im Intranet](https://www.uni-bamberg.de/intranet/lehren-und-forschen-an-der-uni/drittmittelverfahren/){: target="_blank"})

## Project phase

- Regularly update the research data management plan (living document)
