---
title: "Goals"
---

<style>
  p {
    text-align: justify;
  }
</style>

## Research Statement: Digital knowledge work

The digitalization of knowledge work is reshaping how tasks are performed across various industries, with significant implications for individual workers and organizations.
This transformation is driven by the adoption of digital work practices, distributed organizing models, powerful AI capabilities, and advancements in knowledge synthesis.
These shifts are creating new opportunities and challenges for knowledge workers, as traditional practices are reconfigured by emerging technologies.

**Our focus is on understanding these shifts at the intersection of digital work, distributed organizing, and knowledge synthesis, identifying effective practices, and designing tools to meet the evolving demands of knowledge workers.**

Our work builds on literature review methods, design science research, and empirical research.
We work on projects in collaboration with researchers from institutions like HEC Montréal, Sydney University, the University of Virginia, Bamberg University, and Dortmund University.
These joint efforts enable us to combine expertise across disciplines and leverage synergies between different research streams, allowing us to tackle both practical applications and foundational questions.
This integrated approach helps us address key challenges in digital knowledge work while driving advancements that benefit both academic research and industry practices.

### Research stream 1: Digital work practices

**Summary** This research stream explores the evolving role of individual knowledge workers, such as physicians, data scientists, developers, and innovative thinkers, whose work is characterized by agility, innovation, and emergent practices driven by experience and expertise rather than formalized procedures.
It focuses on how digital technologies, particularly AI, are reconfiguring these work practices.
Key areas of inquiry include the adoption of AI in professional settings, the interaction between AI and evidence-based practices, and how expert knowledge can be leveraged to adapt and improve enterprise systems.
At the core, the goal of this research stream is to understand how knowledge work practices are reconfigured by digital technology and to provide actionable insights for leaders in knowledge-intensive fields, enabling them to capitalize on opportunities emerging from the digitalization of work, optimize the integration of new technologies, and enhance the effectiveness of digital work environments.

Exemplary research questions

- **Adoption of AI** What are the AI profiles of prospective physicians associated with a strong intention to use AIHT in their future medical practice?
- **Interaction of AI with traditional evidence-based practices** Do new AI capabilities reduce or reinforce evidence-based practices?
- **Leveraging expertise to adapt enterprise systems** How can the expertise of clinical experts be used to resolve misfits in enterprise systems? 

Selected publications

<div class="references">
    <p>Wagner, G., Raymond, L., and Paré, G. (2023). "Understanding prospective physicians’ intention to use artificial intelligence in their future medical practice: A configurational analysis". <em>JMIR Medical Education</em>, 9, e45631. doi:<a href="https://doi.org/10.2196/45631" target="_blank">10.2196/45631</a></p>
    <p>Morquin, D., Ologeanu-Taddei, R., Paré, G., and Wagner, G. (2023). "Design and Evaluation of a Method to Solve Organization-Enterprise System Misfits in the Post-Implementation Phase: An Action Research". <em>Information Systems Journal</em>, 33(5), 1–34. doi:<a href="https://doi.org/10.1111/isj.12345" target="_blank">10.1111/isj.12345</a></p>
    <p>Paré, G., Raymond, L., Castonguay, A., and Wagner, G. (2023). "Prospective Physicians’ Intention to Adopt Artificial Intelligence: A Configurational Perspective". in Proceedings of the <em>Hawaii International Conference on System Sciences</em>. doi:<a href="https://doi.org/10.24251/HICSS.2023.123" target="_blank">10.24251/HICSS.2023.123</a></p>
  <p>Wagner, G., Ringeval, M., Raymond, L., and Paré, G. (2025). "Digital Health Competences and AI Beliefs as Conditions for the Practice of Evidence-Based Medicine: A Study of Prospective Physicians in Canada". <em>Medical Education Online</em>, 30(1), 1–13. doi:<a href="https://doi.org/10.1080/10872981.2025.2459910" target="_blank">10.1080/10872981.2025.2459910</a></p>
</div>

### Research stream 2: Organizing distributed work

**Summary** This research stream investigates how traditional organizational hierarchies—characterized by strict control and large, monolithic structures—are evolving alongside new, more flexible forms of work organization.
These include distributed (Git-based) knowledge work, open-source communities, online labor markets, and open strategy initiatives such as open employee handbooks in all-remote organizations.
These models are widely used in large tech companies, knowledge-intensive industries, and academia.
The primary goal is to understand how distributed work practices can be organized effectively and how to manage these work arrangements for maximum productivity.
This includes informing stakeholders about best practices for integrating these models with existing organizational frameworks.

Exemplary research questions

- **Processes of knowledge-intensive crowd work** How can online marketplaces for knowledge-intensive service work be distinguished? How can the micro-and macro-level processes be organized?
- **Effective sourcing of knowledge work in online labor markets** What explains the successful sourcing of knowledge work from online labor markets at the level of individual workers and projects?

Selected publications

<div class="references">
    <p>Wagner, G., Prester, J., and Paré, G. (2021). "Exploring the Boundaries and Processes of Digital Platforms for Knowledge Work: A Review of Information Systems Research". <em>The Journal of Strategic Information Systems</em>, 30(4), 101694. doi:<a href="https://doi.org/10.1016/j.jsis.2021.101694" target="_blank">10.1016/j.jsis.2021.101694</a></p>
    <p>Wagner, G. and Prester, J. (2021). "A Framework of Platform Design Mechanisms, Platform Congruence and Value Creation on C2C Platforms". in Proceedings of the <em>29th European Conference on Information Systems (ECIS 2021)</em>, Marrakech, Morocco.</p>
    <p>Wagner, G. and Prester, J. (2019). "Information Systems Research on Digital Platforms for Knowledge Work: A Scoping Review". in Proceedings of the <em>40th International Conference on Information Systems (ICIS 2019)</em>, Munich, Germany.</p>
</div>

### Research stream 3: Knowledge synthesis

**Summary** This research stream addresses the critical need for more efficient and effective knowledge synthesis in response to the vast and rapidly growing body of research.
While the volume of available knowledge continues to increase, methods for synthesizing this research—particularly in the context of open and reproducible literature reviews—are falling behind.
Key areas needing improvement include search query construction, validation, knowledge record matching, emergent concept analyses, and enhancing transparency and validation through AI and generative AI (GenAI) tools.
These challenges are crucial across many fields, particularly for professions like medicine, where synthesizing the best available evidence is essential.
At the core, the goal of this research stream is to design tools that make knowledge synthesis processes more efficient, transparent, and reliable, benefiting practitioners, policymakers, researchers, and students who navigate both academic and industry perspectives.

Exemplary research questions

- **AI/LLM-supported literature reviews** How can AI and LLM capabilities support the individual steps of the literature review process?
- **Understanding quality and impact of review papers** What makes a literature review successful in terms of scientific impact?
- **Design of open and reproducible research synthesis platforms** How can tools make literature reviews and knowledge synthesis more efficient, transparent, and reliable?

Selected publications

<div class="references">
    <p>Wagner, G. (2024). "BibDedupe: An Open-Source Python Library for Bibliographic Record Deduplication". <em>Journal of Open Source Software</em>, 9(97), 6318. doi:<a href="https://doi.org/10.21105/joss.06318" target="_blank">10.21105/joss.06318</a></p>
    <p>Wagner, G., Lukyanenko, R., and Paré, G. (2022). "Artificial Intelligence and the Conduct of Literature Reviews". <em>Journal of Information Technology (JIT)</em>, 37(2), 209–226. doi:<a href="https://doi.org/10.1177/02683962211048201" target="_blank">10.1177/02683962211048201</a></p>
    <p>Wagner, G., Prester, J., Roche, M. P., Schryen, G., Benlian, A., Paré, G., and Templier, M. (2021). "Which Factors Affect the Scientific Impact of Review Papers in IS Research? A Scientometric Study". <em>Information & Management (I&M)</em>, 58(3), 103427. doi:<a href="https://doi.org/10.1016/j.im.2021.103427" target="_blank">10.1016/j.im.2021.103427</a></p>
    <p>Wagner, G. and Prester, J. (2024). "CoLRev - An Open-Source Environment for Collaborative Literature Reviews". Available at <a href="https://github.com/CoLRev-Environment/colrev" target="_blank">https://github.com/CoLRev-Environment/colrev</a>. doi:<a href="https://doi.org/10.5281/zenodo.11668338" target="_blank">10.5281/zenodo.11668338</a></p>
</div>

## Resources

- [United Nations Goals: 4. Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all](https://sdgs.un.org/goals/goal4){target=_blank}
- [United Nations Goals: 8. Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all](https://sdgs.un.org/goals/goal8){target=_blank}
