---
title: "Literature"
---

## Books (Physical Library)

See [library]({{ site.baseurl }}/docs/10-lab/18_resources/18.01.library.html)

## Journals and Conferences

We collect PDFs from key IS journals and conferences. This is essential for full-text searching (see [tools]({{ site.baseurl }}/docs/20-research/20_processes/20.03.systems.html#2003-systems-for-research)) and retrieval (e.g., using CoLRev).

{: .resource } 
> A selection of journal and conference papers is available [on Nextcloud](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/373460?dir=/20-research/22_literature){target=_blank}.

{: .info } 
> Note: only download conference proceedings/issues when they are complete.

Overview of journals:

<!-- labot local-cronjob -->


<table class="table table-sm">
  <colgroup>
    <col style="width: 40%;">
    <col style="width: 10%;">
    <col style="width: 25%;">
    <col style="width: 25%;">
  </colgroup>
  <thead>
    <tr>
      <th>Curation</th>
      <th>Type</th>
      <th style="text-align:right;">Latest in records.bib<br>(last updated)</th>
      <th style="text-align:right;">Latest in data/pdfs<br>(last updated)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>americas-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/americas-conference-on-information-systems/blob/main/data/records.bib">2024</a> (<span style="color:green">2025-10-29</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a> (<span style="color:green">2025-09-12</span>)</td></tr>
    <tr><td>communications-of-the-association-for-information-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/communications-of-the-association-for-information-systems/blob/main/data/records.bib">57</a> (<span style="color:green">2025-11-08</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">57</a> (<strong><span style="color:orange">2025-08-07</span></strong>)</td></tr>
    <tr><td>decision-support-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/decision-support-systems/blob/main/data/records.bib">187</a> (<span style="color:green">2025-10-30</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">200</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>european-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/european-conference-on-information-systems/blob/main/data/records.bib">2025</a> (<span style="color:green">2025-11-23</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a> (<strong><span style="color:orange">2025-06-06</span></strong>)</td></tr>
    <tr><td>european-journal-of-information-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/european-journal-of-information-systems/blob/main/data/records.bib">33_2</a> (<span style="color:green">2025-09-25</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">34_6</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>hawaii-international-conference-on-system-sciences</td><td>conference</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/hawaii-international-conference-on-system-sciences/blob/main/data/records.bib">2025</a> (<span style="color:green">2025-11-13</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2024</a> (<strong><span style="color:orange">2025-09-05</span></strong>)</td></tr>
    <tr><td>information-and-management</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/information-and-management/blob/main/data/records.bib">63_2</a> (<span style="color:green">2025-11-24</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">62_6</a> (<strong><span style="color:orange">2025-08-05</span></strong>)</td></tr>
    <tr><td>information-systems-frontiers</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/information-systems-frontiers/blob/main/data/records.bib">26_1</a> (<span style="color:green">2025-12-03</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">27_4</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>information-systems-journal</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/information-systems-journal/blob/main/data/records.bib">34_1</a> (<span style="color:green">2025-09-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">35_6</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>information-systems-research</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/information-systems-research/blob/main/data/records.bib">36_3</a> (<span style="color:green">2025-11-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">36_3</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>international-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/international-conference-on-information-systems/blob/main/data/records.bib">2024</a> (<span style="color:green">2025-11-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2024</a> (<strong><span style="color:orange">2025-05-23</span></strong>)</td></tr>
    <tr><td>journal-of-information-systems-education</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/journal-of-information-systems-education/blob/main/data/records.bib">36_3</a> (<span style="color:green">2025-10-29</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">36_4</a> (<span style="color:green">2025-11-08</span>)</td></tr>
    <tr><td>journal-of-information-technology</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/journal-of-information-technology/blob/main/data/records.bib">40_3</a> (<span style="color:green">2025-11-13</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">40_4</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>journal-of-management-information-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/journal-of-management-information-systems/blob/main/data/records.bib">40_4</a> (<span style="color:green">2025-09-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">42_4</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>journal-of-the-association-for-information-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/journal-of-the-association-for-information-systems/blob/main/data/records.bib">26_5</a> (<span style="color:green">2025-11-19</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">26_6</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>mis-quarterly</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/mis-quarterly/blob/main/data/records.bib">49_3</a> (<span style="color:green">2025-11-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">49_4</a> (<span style="color:green">2025-12-09</span>)</td></tr>
    <tr><td>pacific-asia-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/pacific-asia-conference-on-information-systems/blob/main/data/records.bib">2025</a> (<span style="color:green">2025-11-26</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a> (<span style="color:green">2025-12-08</span>)</td></tr>
    <tr><td>the-journal-of-strategic-information-systems</td><td>journal</td><td style="text-align:right;"><a href="https://github.com/CoLRev-curations/the-journal-of-strategic-information-systems/blob/main/data/records.bib">33_1</a> (<span style="color:green">2025-12-03</span>)</td><td style="text-align:right;"><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">35_1</a> (<span style="color:green">2025-12-09</span>)</td></tr>
  </tbody>
</table>


<!-- END -->

## Literature Summaries

```{mermaid}
graph BT
    subgraph SharedRepository["Shared Repository"]
        direction LR
        A@{ shape: lean-r, label: "References (references.bib)" }
        B@{ shape: lean-r, label: "Literature Summaries" }
        C@{ shape: lean-r, label: "PDFs (Git-LFS)" }
    end

    subgraph LocalWorkflow["Local workflow"]
        K["Import paper in Zotero"]
        K --> L["Export to Obsidian"]
        L --> D["Create literature summary, add PDF and reference"]
    end

    subgraph OnlineWorkflow["Online workflow"]
        J["Revise files in a shared repository on GitHub (upload of PDFs is not possible)"]
    end

    J --> E
    E[Pull Request]
    D --> E
    E --> SharedRepository

    style LocalWorkflow fill:white,stroke:#333,stroke-width:3px
    style SharedRepository fill:white,stroke:#333,stroke-width:3px
    style OnlineWorkflow fill:white,stroke:#333,stroke-width:3px
```

### Shared repository

Git repository with

- References: `references.bib` in Git repository
- PDFs: Git-LFS (add locally) - **PDFs cannot be uploaded online - must use the local cli for git-lfs**
- Obsidian literature summaries
- If Word integration (citation plugin) is needed: Zotero (for individual projects)

<!-- 
### Local workflow

Zotero can be used (recommended) to facilitate the export to the repository

- Quick export - with [Zotero connector](https://chromewebstore.google.com/detail/zotero-connector/ekhagklcjbdpajgpjgmbionohlpdbjgc){target=_blank} for web exports, [Zotero integration](https://github.com/mgmeyers/obsidian-zotero-integration){target=_blank} and [Obsidian Web Clipper](https://obsidian.md/clipper){target=_blank} for web export

**TODO**

- How to export PDFs efficiently / add the record to the references
- TBD: PDF Commenting (Zotero??)

## Online workflow

- No setup is required.
- Uploading PDFs to git-lfs is not possible.

**TODO**: Create concept notes with a script (not manually with obsidian/Zotero?)

**TODO**:

- Zotero vs. JabRef?
- Update repo setup: include Git-LFS
- Existing projects: Move PDFs to git repositories with Git-LFS [Nextcloud](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/22-literature/23_data&fileid=88094){target=_blank} in sections 25 and 36.
- TBD: CoLRev repositories (PDFs and obsidian vaults)
 -->

**Pull request**: Labot support is enabled for pull requests (e.g., checking consistency, updating references).

Example repository: [work_hub](https://github.com/digital-work-lab/work_hub){target=_blank}


<div style="position:relative; padding-bottom:56.25%; height:0; overflow:hidden; max-width:100%;">
  <iframe src="https://www.youtube-nocookie.com/embed/7zE5i0WrLko"
          frameborder="0" allowfullscreen
          style="position:absolute; top:0; left:0; width:100%; height:100%;">
  </iframe>
</div>

## References

- [Obsidian for academic workflows](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/for+Academic+Writing){target=_blank}

{: .resource } 
> - [GitHub](https://github.com/orgs/digital-work-lab/repositories?q=topic%3Aresearch){target=_blank}
