---
title: "Paper Templates"
---

{: .no_toc }

{: .highlight }
If you would like to contribute to an existing project, jump to the [edit-the-paper](#edit-the-paper) section.

The paper development process is based on markdown, git, Docker, pandoc, and csl.
The goal is to support the collaborative writing process effectively, building on powerful open source tools, and supporting efficient production of documents for submission.

Start your manuscript development by using the [Markdown template](https://github.com/digital-work-lab/paper-template){target=_blank}. This template provides a structured format for your initial drafts, helping to organize content efficiently.

## Table of contents
{: .no_toc .text-delta }

- TOC
{:toc}

## Initial setup

This section explains how to install the environment and build the paper.
[Git](https://git-scm.com/){target=_blank}, [Docker](https://www.docker.com/){target=_blank} and make are required.
The following steps describe how to

1. Set up the repository (create a new one or contribute to an existing one),
2. Set up the paper production pipeline, and
3. Build the paper

The manuscript template creates the following files (additional [files for the analysis](20.21.analysis-templates.html) can be added)

```text
├── README.md     <- Readme containing summaries of the paper's revisions (completed
│                    and ongoing). Revision sheets are created from this document.
├── paper.md      <- Contains the paper
├── Makefile      <- Contains instructions to build the paper (as pdf or docx),
│                    and run the analyses (if a Makefile exists in the analysis
│                    directory)
├── Dockerfile    <- Describes the pandoc container for building the paper
│                    (called by the Makefile)  
├── literature    <- Directory containing literature summaries for Obsidian
├── figures       <- Directory contains all conceptual figures
├── output        <- Directory contains all output, such as data plots and
│                    tables, which is generated by the scripts (do not store
│                    anything else that is not generated by the scripts in this
│                    directory)
└── .gitignore    <- Contains a list of files that are excluded from git
                     versioning (e.g., paper.pdf, which would create conflicts
                     when merging changes)
```

Templates (\*.docx, \*.tex) and styles (\*.csl) are versioned in the paper repository.
This can be accomplished by using the code in comments at the beginning of the [Makefile](Makefile).

### 1: Set up the repository

Option 1: Create a new repository

- Select a short and pronounceable title for the paper
- Do not refer to papers by their target journal (e.g., "the Journal of Information Technology paper")
- Use labot to set up the paper:

```
labot paper --init
```

<details>
  <summary>Manual setup</summary>

<div class="language-text highlighter-rouge"><div class="highlight"><pre class="highlight"><code>git clone git@github.com:digital-work-lab/paper-template.git
# MANUALLY rename the folder using a short project title
# remove the .git directory containing older versions
rm -rf .git
# repo setup:
git init
# MANUALLY create paper (update titles etc.)
mkdir analysis data figures output
pre-commit install
cd .git/hooks
cp ../../post-xxx-sample.txt post-checkout
cp post-checkout post-merge
cp post-checkout post-commit
rm ../../post-xxx-sample.txt
cd ../..
git add .
git commit -m 'initial commit'
make pdf
# connect to git remote
# MANUALLY update url in the following line
git remote add origin https://github.com/....
git branch -M main
git push -u origin main
# MANUALLY invite coauthors/provide access to the remote repository
# git clone template-repository
# git clone https://github.com/citation-style-language/styles
# MANUALLY symlink the templates and styles repos</code></pre></div><button type="button" aria-label="Copy code to clipboard"><svg viewBox="0 0 24 24" class="copy-icon"><use xlink:href="#svg-copy"></use></svg></button></div>

</details>

Option 2: Contribute to an existing repository

```shell
# pull repository
git clone git@github.com:digital-work-lab/...
pre-commit install
```

### 2: Set up the paper production pipeline

```shell
# Build the Docker container
make build
# MANUALLY select a citation style by updating the link at the beginning of the Makefile
# MANUALLY select templates for docx/tex by updating the link at the beginning of the Makefile
```

- Citation styles can be selected [here](https://github.com/citation-style-language/styles){target=_blank}
- Templates are available [here](https://github.com/digital-work-lab/templates){target=_blank}

### 3: Build the paper

```shell
make pdf
make docx
```


## Edit the paper

The [paper](paper.md) is written in markdown.
There are three ways to edit a paper:

| **Option**             | **Explanation**                                                                                                                                          | **Short illustration**                                                                                                                |
|------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------|
| **GitHub Edit**        | - Does not support PDF/DOCX generation<br>- Does not support commits changing multiple files<br>- Requires an Internet connection<br>- No setup required | <a href="#" onclick="window.open('20.20.paper-templates-edit-paper-github.html', '_blank', 'width=1300,height=800');">GitHub Edit</a>        |
| **Codespace Edit**     | - Supports PDF/DOCX generation<br>- Supports all types of commits<br>- Requires an Internet connection<br>- No setup required                            | <a href="#" onclick="window.open('20.20.paper-templates-edit-paper-codespaces.html', '_blank', 'width=1300,height=800');">Codespace Edit</a> |
| **Local Edit**         | - Supports PDF/DOCX generation<br>- Supports all types of commits<br>- Does not require an Internet connection<br>- Requires some setup                  | <a href="#" onclick="window.open('20.20.paper-templates-edit-paper-local.html', '_blank', 'width=1300,height=800');">Local Edit</a>          |

{: .highlight }
> **Markdown hints**
> 
> Useful guides on markdown are available online ([1](https://bookdown.org/yihui/rmarkdown/){target=_blank}, [2](https://bookdown.org/yihui/rmarkdown-cookbook/){target=_blank}).
> A short overview is in the [markdown kitchen sink](../../10-lab/10_processes/10.07.markdown.html) section.
> 
> It is good practice to
> 
> - Begin **each sentence in a new line** to make the history more readable and to make merging easier (see [semantic line breaks](https://sembr.org/){target=_blank}).

<!-- 
In local setups, several editors are available for markdown documents, for example:

- [Atom](https://shd101wyy.github.io/markdown-preview-enhanced/#/){target=_blank} with [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced){target=_blank}
- [Panwriter](https://panwriter.com/){target=_blank}
 -->

The bibliography is stored as a bib file (typically `references.bib`) and versioned by git.
<!-- It can be edited using tools like [JabRef](https://github.com/JabRef/jabref){target=_blank}. -->
It is recommended to configure save actions to [store titles as sentence case](https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#sentence-case){target=_blank}, [normalize names of persons for author fields](https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#normalize-names-of-persons){target=_blank}, and to [normalize page numbers](https://docs.jabref.org/finding-sorting-and-cleaning-entries/saveactions#normalize-page-numbers){target=_blank}.
Changes in the bib-file should be checked before committing and adding {} to protect cases when necessary (e.g., `{J}ab{R}ef`).

Formatting the bibliography (*.bib file)

- Title field: use sentence case (e.g., "On the origin of species", not "On the Origin of Species"). CSL styles that require title case will use an automatic title-case conversion ([1](https://citationstyles.org/authors/#/titles-in-sentence-and-title-case){target=_blank}).
- Journal field: use long version (e.g., "Journal of Information Technology", not "JIT"). For CSL styles that require abbreviations, temporarily replace the journal field in the bib-file since CSL does not handle style-specific journal abbreviations ([1](https://citationstyles.org/authors/#/csl-limitations){target=_blank}). JSON-files containing journal abbreviations can be passed to pandoc using the [citation-abbreviations](https://pandoc.org/MANUAL.html#option--citation-abbreviations){target=_blank} field.
- Inproceedings: when using crossrefs (e.g., `crossref = {icis2010}`) for conference papers, the year and month field should _not_ be set, only the original \@Proceedings entry should include the date formatted as follows: `date    = {2015-12-13/2015-12-16}`.

{: .highlight }
> **Literature summaries: Obsidian**
>
> Literature summaries for each paper are stored in Obsidian format in the `literature` directory.

## Resources

The paper-template is based on the following underlying architectural principles and considerations.

- Minimal functionality: the most frequent use cases (writing, citing, creating submission files in docx/latex format with different templates and citation styles) must be supported in a highly efficient way.
More complex functionality (such as tables with merged cells and detailed formatting) is used less frequently (requiring less effort if not supported in an efficient way).
It may also create fewer problems (e.g., merging complex tables - as in Word/comparisons of tables)

Advantages of the markdown/pandoc workflow:

- Separation of content and format
- Collaboration and versioning of text with Git
- Relying on active open source projects such as the [CSL](https://citationstyles.org/){target=_blank} standard
- Flexibility regarding the bibliography type (pandoc supports .bib, .enl, ...)
- Combined writing and comments in the same document
- Reproducibility across platforms
- Generating docx/tex/pdf as output

Since the underlying open source projects (especially CSL, pandoc, pandoc-citeproc) evolve constantly, it is recommended to work with the latest versions.
This is a limitation of the popular [manubot project](https://github.com/manubot/rootstock){target=_blank} or [pandoc scholar](https://github.com/pandoc-scholar/pandoc-scholar){target=_blank}, which work with old versions of pandoc (which may be hard to update).

Possible extensions (lua-filters): [bibexport](https://github.com/pandoc/lua-filters/tree/master/bibexport){target=_blank}, [abstract-to-meta](https://github.com/pandoc/lua-filters/tree/master/abstract-to-meta){target=_blank}, [spellcheck](https://github.com/pandoc/lua-filters/tree/master/spellcheck){target=_blank}, [wordcount](https://github.com/pandoc/lua-filters/tree/master/wordcount){target=_blank}.

- [pandoc journal templates](https://github.com/sachsmc/pandoc-journal-templates){target=_blank}
