---
title: "PDF collection"
---

## Journals and conferences

We collect PDFs from key IS journals and conferences. This is essential for full-text searching (see [tools](/docs/20-research/20_processes/20.03.systems.html#2003-systems-for-research)) and retrieval (e.g., using CoLRev).
PDFs are available [on Nextcloud](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/373460?dir=/20-research/22_literature){target=_blank}.

<!-- labot local-cronjob -->


<table class="table table-sm">
  <colgroup>
    <col style="width: 50%;">
    <col style="width: 8%;">
    <col style="width: 21%;">
    <col style="width: 21%;">
  </colgroup>
  <thead>
    <tr>
      <th>Journal / Conference</th>
      <th>Type</th>
      <th style="text-align:right;">Latest in records.bib<br>(last updated)</th>
      <th style="text-align:right;">Latest in data/pdfs<br>(last updated)</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>americas-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/americas-conference-on-information-systems/blob/main/data/records.bib">2024</a></div><div style="font-size:0.85em;"><span style="color:green">2025-10-29</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-09-12</span></div></td></tr>
    <tr><td>communications-of-the-association-for-information-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/communications-of-the-association-for-information-systems/blob/main/data/records.bib">57</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-08</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">57</a></div><div style="font-size:0.85em;"><strong><span style="color:orange">2025-08-07</span></strong></div></td></tr>
    <tr><td>decision-support-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/decision-support-systems/blob/main/data/records.bib">187</a></div><div style="font-size:0.85em;"><span style="color:green">2025-10-30</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">200</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>european-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/european-conference-on-information-systems/blob/main/data/records.bib">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-23</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-06-06</span></div></td></tr>
    <tr><td>european-journal-of-information-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/european-journal-of-information-systems/blob/main/data/records.bib">33_2</a></div><div style="font-size:0.85em;"><span style="color:green">2025-09-25</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">34_6</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>hawaii-international-conference-on-system-sciences</td><td>conference</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/hawaii-international-conference-on-system-sciences/blob/main/data/records.bib">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-13</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2024</a></div><div style="font-size:0.85em;"><span style="color:green">2025-09-05</span></div></td></tr>
    <tr><td>information-and-management</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/information-and-management/blob/main/data/records.bib">63_2</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-24</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">63_1</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-12</span></div></td></tr>
    <tr><td>information-systems-frontiers</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/information-systems-frontiers/blob/main/data/records.bib">26_1</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-03</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">27_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>information-systems-journal</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/information-systems-journal/blob/main/data/records.bib">34_1</a></div><div style="font-size:0.85em;"><span style="color:green">2025-09-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">35_6</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>information-systems-research</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/information-systems-research/blob/main/data/records.bib">36_3</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">36_3</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>international-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/international-conference-on-information-systems/blob/main/data/records.bib">2024</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-12</span></div></td></tr>
    <tr><td>journal-of-information-systems-education</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/journal-of-information-systems-education/blob/main/data/records.bib">36_3</a></div><div style="font-size:0.85em;"><span style="color:green">2025-10-29</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">36_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-08</span></div></td></tr>
    <tr><td>journal-of-information-technology</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/journal-of-information-technology/blob/main/data/records.bib">40_3</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-13</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">40_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>journal-of-management-information-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/journal-of-management-information-systems/blob/main/data/records.bib">40_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-09-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">42_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>journal-of-the-association-for-information-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/journal-of-the-association-for-information-systems/blob/main/data/records.bib">26_5</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-19</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">26_6</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>mis-quarterly</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/mis-quarterly/blob/main/data/records.bib">49_3</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">49_4</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
    <tr><td>pacific-asia-conference-on-information-systems</td><td>conference</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/pacific-asia-conference-on-information-systems/blob/main/data/records.bib">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-11-26</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">2025</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-08</span></div></td></tr>
    <tr><td>the-journal-of-strategic-information-systems</td><td>journal</td><td style="text-align:right;"><div><a href="https://github.com/CoLRev-curations/the-journal-of-strategic-information-systems/blob/main/data/records.bib">33_1</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-03</span></div></td><td style="text-align:right;"><div><a href="https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files">35_1</a></div><div style="font-size:0.85em;"><span style="color:green">2025-12-09</span></div></td></tr>
  </tbody>
</table>


<!-- END -->

## Process

::: {.callout-note}
Note: only download conference proceedings/issues when they are complete.
:::

TODO: 

- explain how the overview is generated/upated
- Check: updating a PDF (to change the last-updated time stamp and document "last checked")
