---
title: "Peer review"
---

::: {.callout-warning}
When using this checklist, remember that the peer review process is strictly confidential.
The manuscript and your review comments must not be shared, distributed, or discussed outside the formal review process.
Always maintain professionalism and provide constructive, unbiased feedback.
:::

## Review Structure

```Markdown
# Section 0: Review Details

# Section 1: Introduction (3 paragraphs)

- **Paragraph 1:** Main question, goals, approach, and conclusions.
- **Paragraph 2:** Contribution to the journal, ideally with reference to prior work.
- **Paragraph 3:** Publishability evaluation and recommendation.

# Section 2: Major Issues (numbered items)

# Section 3: Minor Issues (indicate line, figure, table numbers)

```

## Step 1: Invitation to Review

- [ ] Read the abstract.
- [ ] Assess if your expertise qualifies you to critically evaluate the manuscript.
- [ ] Check for conflicts of interest.
- [ ] Confirm time availability to complete the review.
- [ ] Review journal guidelines and adjust workflow accordingly.
- [ ] Respond promptly to the invitation (Accept/Decline and provide reasons, if applicable).

## Step 2: First Overview

- [ ] Prepare a text file with the [review structure](#review-structure).
- [ ] Read the entire paper, noting motivation, approach, results, and conclusions.
- [ ] Examine figures and tables to ensure they complement the results.
- [ ] Assess readability; notify the editor if the manuscript is incomprehensible.
- [ ] Identify key aspects:

  - [ ] Main question addressed by the research.
  - [ ] Relevance and contribution to the field.
  - [ ] Clarity and justification of the Abstract and Introduction.
  - [ ] Appropriateness of the methods.
  - [ ] Presentation and justification of results.
  - [ ] Clear and described figures.
  - [ ] Conclusions aligned with the main questions.
  - [ ] Scope and publishability of the paper.

- [ ] Write introductory paragraphs (Section 1)

## Step 3: Full Read

- [ ] Take detailed notes with references to section, line, figure, and table numbers.
- [ ] Read the manuscript in detail, section by section (Introduction, Methods, Results, etc.).
- [ ] Validate:

  - [ ] Methods, including reproducibility and rationale for non-reproducible methods.
  - [ ] Figures, ensuring clarity and reflection of the main text.
  - [ ] References and supplementary materials.
  - [ ] Compliance with journal guidelines and data policy.

- [ ] Identify issues:
  - **Major Issues (Section 2):** Use numbered paragraphs for clarity.
  - **Minor Issues (Section 3):** Detail line, figure, and table numbers.

::: {.callout-note}
When reviewing conference papers, point to issues that would make for a fruitful discussion.
:::

## Step 4: Writing

- [ ] Check organization and flow of arguments:

  - [ ] Ensure clarity and logical flow of paragraphs.
  - [ ] Minimize excessive jargon and confusing acronyms.

- [ ] Polish the review for tone and clarity.
- [ ] Address specific questions from the journal.
- [ ] Include optional remarks to the editor.
- [ ] Submit the review using the provided platform.


::: {.callout-note}
**Constructive Tone**
 
Always adopt a constructive tone when providing feedback during peer review.
Frame comments in a way that helps the authors refine their work, offering actionable suggestions rather than vague criticisms.
A respectful and supportive approach fosters collaboration and enhances the quality of academic discourse.
:::

## Resources

<div class="references">
 <p>Sarker, S., Whitley, E. A., Goh, K. Y., Hong, Y., Mähring, M., Sanyal, P., ... & Zhao, H. (2023). Some thoughts on reviewing for Information Systems Research and other leading information systems journals. <i>Information Systems Research</i>, 34(4), 1321-1338. <a href="https://pubsonline.informs.org/doi/full/10.1287/isre.2023.editorial.v34.n4">link</a></p>
 <p>Ragins, B. R. (2017). Editor’s comments: Raising the bar for developmental reviewing. <i>Academy of Management Review</i>, 42(4), 573-576. <a href="https://psycnet.apa.org/record/2017-47161-001">link</a></p>
 <p>Davison, R. M. (2015). Editorial‐The Art of Constructive Reviewing. <i>Information Systems Journal</i>, 25(5), 429-432. <a href="https://onlinelibrary.wiley.com/doi/full/10.1111/isj.12083">link</a></p>
 <p>Rai, A. (2016). Editor's comments: writing a virtuous review. <i>MIS Quarterly</i>, 40(3), iii-x. <a href="https://dl.acm.org/doi/abs/10.5555/3177634.3177635">link</a></p>
</div>

- [MISQ Open Report](https://drive.google.com/file/d/1-cyLPxpK2R1K_HV4TeA9NeE9GHro126K/view){target=_blank}
