---
title: "Presentation"
---

## General guidelines

- Adapt to the audience
- Prepare a short elevator pitch
- Plan for eventualities (e.g., no Internet/Wi-Fi connection available)
- Make slides available [TODO: link repo] and allow participants to connect/give feedback (TODO: add suggestions)
- Communicate a clear reason why your audience should be interested in your presentation (in particular when some participants are required to attend)
- When appropriate: start with a bold pitch like "After this talk, you will do ... differently."
- When appropriate, use storytelling to make the presentation memorable

The [Beamer checklist](../teaching/session.html#beamer-checklist) may be helpful.

## Template

::: resource

[fs-ise/quarto-template-presentation](https://github.com/fs-ise/quarto-template-presentation){target=_blank}

```bash
copier copy --trust gh:fs-ise/quarto-template-presentation my-talk
cd my-talk
quarto render
```

:::

### Preview

Preview the Frankfurt School Quarto presentation template below.

<iframe class="presentation-preview" src="https://fs-ise.github.io/quarto-template-presentation/" title="Frankfurt School Quarto presentation template preview" loading="lazy"></iframe>

[Open presentation in full screen](https://fs-ise.github.io/quarto-template-presentation/){target="_blank"} · [View template repository](https://github.com/fs-ise/quarto-template-presentation){target="_blank"}

## Resources

- [Better Poster LaTeX Template](https://github.com/rafaelbailo/betterposter-latex-template){target=_blank}
- [Podcast: The three most useless slides in conference presentations](https://www.janrecker.com/this-is-research-podcast/the-three-most-useless-slides-in-conference-presentations-4-september-2024/){target=_blank}
