---
title: "Publication"
transition_status: "toupdate"
transition_comment: "Update institutional systems for updating publications, publication fees"
---

::: {.callout-note}
This section is marked as "toupdate": Update institutional systems for updating publications, publication fees
:::

## Publication fees

TBD.

<!--
Zukünftig wird die Universitätsbibliothek die Bearbeitung von Rechnungen im Zusammenhang mit dem wissenschaftlichen Publizieren übernehmen. Bitte senden Sie ab 01.04.2024 Rechnungen über Publikationskosten (= Kosten im Zusammenhang mit der Veröffentlichung wissenschaftlicher Dokumente) direkt an die Universitätsbibliothek (UB/F21, rechnungswesen.ub@uni-bamberg.de ). Bitte geben Sie bei der Rechnung wie bisher die Kostenstelle an und ob die Rechnung aus dem regulären Lehrstuhletat oder aus einem spezifischen Drittmittelkonto bezahlt werden soll. Die Universitätsbibliothek wird die Rechnung dann bearbeiten.

Die Rechnungen werden ab 01.04.24 direkt von der Bibliothek gebucht und auch dort abgelegt. Es ist zwingend darauf zu achten, dass jede Rechnung mit „sachlich und rechnerisch richtig“ unterzeichnet ist.

"Aus dem Open-Access-Fonds kann hier weiterhin eine Unterstützung mit maximal 2.000 Euro pro Artikel erfolgen. Jedoch kann diese Finanzierung auf Empfehlung des Beirats der Universitätsbibliothek **nun auch anteilig erfolgen, d.h. die Publikationsgebühr darf über diesem Betrag liegen**. Für den darüber hinausgehenden Anteil müssen die Autorinnen und Autoren eine andere Finanzierung angeben. Unverändert bleibt, dass aus dem Open-Access-Fonds nur Beiträge gefördert werden, die in “echten“ Open-Access-Zeitschriften erscheinen, deren Beiträge sämtlich unmittelbar mit Erscheinen open access zugänglich sind. Eine Doppelfinanzierung von Zeitschriften durch Publikationsgebühren und Abo-Gebühren möchten wir nicht unterstützen."

[Open-Access Fonds](https://www.uni-bamberg.de/ub/forschen-und-publizieren/open-access-publizieren/foerderung-oa-artikel/){target=_blank}
-->

## Authors with first-time publication

Create accounts:

- [ORCID](https://ORCID.org/){target=_blank}, [link ORCID in GitHub](https://github.blog/changelog/2024-03-13-authenticate-ORCID-id/){target=_blank}
- [GoogleScholar](https://scholar.google.com/intl/de/scholar/citations.html){target=_blank}
- [ResearchGate](https://www.researchgate.net/){target=_blank}

## Enter publication details and store full-text document

Enter publication details in:

- [references.bib](https://github.com/fs-ise/handbook/blob/main/data/references.bib){target=_blank} (the [publications](publications.html) page will be updated automatically).
- [Forschungsinformationssystem (FIS)](https://fis.uni-bamberg.de/mydspace){target=_blank}
- ORCID (if the publisher has not added the publication)
- GoogleScholar
- ResearchGate
- Website
- CV

Add PDF to

- Nextcloud [publications]({{< var nextcloud.publications >}}){target=_blank}

## Improvement, reflection and follow-up

- Reflect on potential improvements in the research process and document [here](/research/improvement.html)
- Discuss potential follow-up projects and document [here](/research/projects.html)

## Archive and publish PDF and/or data

- Reuse of literature (PDFs should be in nextcloud; PDF names should be IDs; BibTeX file and final paper should be added)
- Reuse of data, and scripts (archive of git repository)
- Check whether PDFs and primary data can be made available, if so:

  - Use [Zenodo](https://zenodo.org/){target=_blank} to assign a DOI to the repo and make it citable: [link](https://zenodo.org/account/settings/github/){target=_blank} ([instructions](https://coderefinery.github.io/github-without-command-line/doi/){target=_blank})
  - Add `dataset` tag to GitHub repository (see [overview](https://github.com/orgs/fs-ise/repositories?q=topic%3Adataset){target=_blank})
