---
title: "Repository setup"
---

The base structure of a repository contains the following:

| File or folder      | Description                                                     |
|---------------------|-----------------------------------------------------------------|
| `README.md`         | Readme explaining the project.                                  |
| `paper.md`          | The paper in Markdown format.                                   |
| `references.bib`    | The references in BibTeX format.                                |
| `data/`             | Directory containing the data.                                  |
| `analysis/`         | Directory containing the code for the analyses.                 |
| `figures/`          | Directory containing the figures.                               |
| `Makefile`          | Instructions on how to build the paper and/or run the analysis. |
| `Dockerfile`        | Instructions on how to build the virtual environment.           |
| `.gitignore`        | A list of files excluded from git versioning.                   |

The following templates are available for different use cases:

| Use case                         | Template                                                                                    |
|----------------------------------|---------------------------------------------------------------------------------------------|
| Paper repository                 | [Paper template](/research/writing_technical.html)                                                |
| Analysis repository              | [Analysis template](/research/analysis_templates.html)                                          |
| Literature review (and paper)    | [CoLRev repository](https://github.com/CoLRev-Environment/colrev){target=_blank}        |

The research team can decide to combine repositories (e.g., containing the paper with analyses) or create separate repositories.

::: callout-note
- Add the tags `research` and `paper` to ensure that the repository is listed correctly in the [overview](/management/repositories.html).
- Set the `MY_PAT_TOKEN` as a repository secret (for the Labot workflow)
:::

TODO: describe creation of GitHub repository, see [repositories](/management/repositories.html) (https://github.com/organizations/digital-work-lab/repositories/new)

## Resources

- [gitignore](https://www.toptal.com/developers/gitignore){target=_blank}
- [Cookiecutter Data Science template](https://cookiecutter-data-science.drivendata.org/){target=_blank}
- [showyourwork](https://show-your.work/en/latest/){target=_blank}
- [Research Software Engineering with Python: Chapter 13 Tracking Provenance](https://third-bit.com/py-rse/provenance.html){target=_blank}
- [Organizing scientific work](https://forschungsdaten.info/themen/organisieren-und-aufbereiten/kollaboratives-arbeiten/tools-fuer-die-organisation-wissenschaftlicher-datenarbeit/){target=_blank}
- [Research Compendia](https://book.the-turing-way.org/reproducible-research/compendia){target=_blank}
