---
title: "SOP"
---

## Process

The process is illustrated [here](../../20-research/)

## Principles

- Use [Markdown](../../10-lab/10_processes/10.07.markdown.html) for manuscripts, presentations, and knowledge management
- Use Git to version, collaborate, and share

The principles are reflected in the [paper template](20.20.paper-templates.html), the [presentation template](20.28.presentation.html), and the [thesis template](https://github.com/digital-work-lab/thesis-template){target=_blank}.

## Project management

Notes on project management are added to the README.md file of the repository.
Expected contributions can be specified using [CRediT](https://credit.niso.org/){target=_blank}.
The following can be used as a template:

::: callout-note
**Research project title (abbreviation)**

Target: Journal A, B

Contributors:

- Contributor A (initials): Conceptualization, Writing - original draft, Writing - review & editing, Supervision
- Contributor B (initials): Data Curation, Writing - review & editing

Instructions for [setup](link) and building the paper:

```
make pdf
```

## Log

Next steps:

- [ ] (initials): Taks A
- [ ] (initials): Task B

## CW1

- [X] Task C
:::
