---
title: "Systems"
---

System | Description |
---|---|
[Obsidian](https://obsidian.md/){target=_blank} with [Obsidian Web Clipper](https://chromewebstore.google.com/detail/obsidian-web-clipper/cnjifjpddelmedmihgijeibhnjfabmlf?pli=1){target=_blank} | - Markdown-based knowledge management tool<br>- Follows a second brain approach<br>- Allows linking pieces of information together to draw conclusions<br>- Helps to structure contents for a comprehensive teaching and writing outline |
[Marp](https://marp.app/){target=_blank}| - Open source Markdown-based presentation tool<br>- Creating slides with text, images, code blocks, diagrams, ...<br>- Exporting Presentations to many formats (HTML, PDF, ...)<br>- Speaker notes and presenter view during presentations<br>- CSS styling for customization<br>- Good integration with [Git](#git)<br>- Template is available [here](https://github.com/digital-work-lab/slides_template){target=_blank} |
[Zotero](https://www.zotero.org/){target=_blank}| - IT-support offers help when switching from [Citavi](#Citavi) to Zotero<br>- Store and organize various types of research materials<br>- Generate citations and bibliographies in various citation styles (such as APA, MLA, Chicago, etc.)<br>- Easy collaboration with other researchers by sharing libraries<br>- Built-in PDF reader<br>- Provides advanced search and filtering options to quickly locate specific sources within large collections<br>- Synchronization between devices |
[Agent Ransack](https://www.mythicsoft.com/agentransack/){target=_blank}, [Recoll](https://wiki.ubuntuusers.de/Recoll/){target=_blank}, [pdfgrep](https://pdfgrep.org/){target=_blank} | - Searching content across PDF files |
[R / RStudio](https://posit.co/){target=_blank} / [Tidyverse](https://www.tidyverse.org/){target=_blank}| - Statistical analyses and visualization (ggplot2) |
[Python](https://www.python.org/){target=_blank}| - Data science projects |
[Juypyter notebooks](https://jupyter.org/){target=_blank}| - Interactive analyses in Python or R |
[Cursor: AI Code Editor](https://cursor.sh/){target=_blank}| - Write code with AI support (ctrl+k / ctrl+l) |
[Gigamove](https://gigamove.rwth-aachen.de/de/provide){target=_blank}| - Share large files |
