---
title: "Research training"
---

Categories:

- methods
- writing
- The [Bamberg Center for Empirical Studies (BACES)](https://www.uni-bamberg.de/baces/){target=_blank} offers free consultation related to data management and statistical analyses

See [podcast episode on phd education](https://www.janrecker.com/this-is-research-podcast/nicks-rules-for-a-good-phd-education-24-september-2025/){target=_blank}

Resources (to sort):

- [The Turing Way](https://book.the-turing-way.org/){target=_blank}
- [Good-enough practices in scientific computing](https://carpentries-lab.github.io/good-enough-practices/index.html){target=_blank}
- [How to document your research software](https://coderefinery.github.io/documentation/){target=_blank}
- [how-to docs](https://nashpy.readthedocs.io/en/stable/contributing/how-to/index.html){target=_blank}
- [Awesome reproducible research](https://github.com/leipzig/awesome-reproducible-research?tab=readme-ov-file){target=_blank}
- [Awesome open science](https://github.com/ZoranPandovski/awesome-open-science){target=_blank}
- [Instats courses](https://instats.org/){target=_blank}
- [IDIS: International Doctoral Network in Information Systems](https://idis.digital/){target=_blank}
- [VHB Prodoc](https://www.vhbonline.org/veranstaltungen/prodok){target=_blank}
- [Good Enough Practices in Scientific Computing](https://carpentries-lab.github.io/good-enough-practices/){target=_blank}
- [Tidyverse skills for Data Science](https://jhudatascience.org/tidyversecourse/){target=_blank}
- [Git & GitHub Tutorial for Scientists](https://gitbookdown.dallasdatascience.com/)
- [Intro to reproducible reserach with R (3-day workshop)](https://r-cubed-intro.rostools.org/)

Books on philosophy of science:

- Thomas S. Kuhn – The Structure of Scientific Revolutions (paradigms & paradigm shifts)
- Karl Popper – The Logic of Scientific Discovery (falsification)
- Karl Popper – Conjectures and Refutations (essays, very readable)
- Paul Feyerabend – Against Method (“anything goes” critique)
- Alan Chalmers – What Is This Thing Called Science? (widely used intro)
- Herbert Simon - Sciences of the Artificial (for design science)

Research and modes of reasoning

Levallet, N., Denford, J. S., & Chan, Y. E. (2020). Following the MAP (methods, approaches, perspectives) in information systems research. Information Systems Research, 32(1), 130-146. ([link](https://pubsonline.informs.org/doi/10.1287/isre.2020.0964){target=_blank}).

Validity

Boudreau, Gefen & Straub (2001), “Validation in Information Systems Research: A State-of-the-Art Assessment,” MIS Quarterly.
Shadish, Cook & Campbell (2002), Experimental and Quasi-Experimental Designs for Generalized Causal Inference.
Straub, Boudreau & Gefen (2004), “Validation Guidelines for IS Positivist Research,” CAIS.

IS Research Podcast Episodes:
- [Cognitive conflict, courage, humility, and respect: Ingredients for a productive academic discourse](https://www.youtube.com/watch?v=7Eq2JL4qTvQ){target=_blank}
- [Every contribution can be interesting but not all of them are](https://www.youtube.com/watch?v=N3NFJlI84Z0){target=_blank}
