---
title: "Course organization"
---

TODO:

See https://digital-work-lab.github.io/handbook/docs/30-teaching/32_courses/


## Scheduling of courses

The scheduling department (individuals responsible for specific degree programs) contacts me (with preferences gathered via Google Forms). I then receive a proposed schedule (I must manually check and resolve conflicts between programs; if necessary, clarify with the scheduling department or speak directly with colleagues). Ensure that module coordinators list me as the instructor (otherwise invitations will be sent to the wrong person).

## Coordination

Planned: Coordination meetings for overlapping course materials.


## New modules

New modules must be created in FlexNow based on the [process overview](https://www.uni-bamberg.de/qm/prozesse-studium-und-lehre/prozessportal/){target=_blank}.

A description for creating and editing modules in FlexNow is available in the [VC course "FlexNow für Lehrstühle"](https://vc.uni-bamberg.de/course/view.php?id=268){target=_blank}.

Once the new module is created, teaching sessions must be created for each semester:

- [lectures](30.10.lecture.html)
- [seminars](30.11.seminars.html)
- [projects](30.12.projects.html)

**TODO**: Create an overview of modules x study programs (WI/AI/I/...)


TODO : describe the process and system of booking lecture rooms.

Projekt: see dates on the [project page](https://digital-work-lab.github.io/open-source-project/){target=_blank}.

## Room bookings UnivIS

::: callout-important
First, the dean's office books the central courses, then the secretariats are _allowed_ to book their decentralized courses
:::

July:
- Email from the dean's office with the occupancy plan for the central courses (?)

- Pay attention to overlaps within the chair
- After booking a room, you must inform Alex **immediately**
