---
title: "Hiring"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": update complete process
:::

::: resource
Confidential data is stored on the [Nextcloud]({{< var nextcloud.hiring >}}){target=_blank}.
:::

## Processes

### Announcements

- Create new section in [hiring]({{< var nextcloud.hiring >}}){target=_blank}
- Check available budget
- Create position announcement based on the template for [student assistant positions (HIWI)](https://github.com/fs-ise/handbook/raw/main/assets/docs/Ausschreibung-HIWI-Stellen.docx){target=_blank}
- Promote open job position via several channels:
  - Post on website and update monthly (highlight or make it stick on top)
  - Inform Fachschaft fachschaft-wiai.stuve[at]uni-bamberg.de
  - Inform Jobbörse WIAI careercenter.wiai[at]uni-bamberg.de
  - Create a job slide and present it at the first or last lesson of lectures
  - Place a job offering printout on the job whiteboard at WE5, ground floor (must be authorized by Dekanat)
  - Place a job offering printout on "Choose-a-chair" fair booth

### Interviews

- Provide an overview of our goals, the team, and how we work ([goals](/research/statement.html) and [SOP](/management/sop.html)
- Explain modalities, responsibilities, and development opportunities
- Ask questions on qualifications, CV, soft-skills
- Prepare questions and tasks (knowing theory, understanding research, applying methods/Git/..., creating, writing)
- Answer questions of applicants
- Inform applicants about the next steps

### Contracts

When sending documents to HR, clearly indicate who should receive the confirmation documents and contracts.

::: {.callout-note title="Contracts: PhD students" collapse=true}

Submit documents at least 4 weeks before start of work to [HR](https://www.uni-bamberg.de/abt-personal/personal3-3/team-zustaendigkeiten/){target=_blank}:

[Application form](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsantraege_Weiterbeschaeftigungsantraege/Einstellungsantrag_wissenschaftliche_Beschaeftigte.docx){target=_blank}

[Necessary contract documents](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsunterlagen/Einstellungsunterl_Besch_wiss.zip){target=_blank}

Send to **Referat III/2 (Dienstvertrag/vertraulich)** via internal mail.
:::


::: {.callout-note title="Contracts: student assistants" collapse=true}

Submit documents at least 4 weeks before start of work to [HR](https://www.uni-bamberg.de/abt-personal/personal3-3/team-zustaendigkeiten/){target=_blank}:


::: {.callout-warning}
The ZUV template raises validation errors when the browser language is English. Switch to German or use another browser.
:::

Forms to hire student assistants are available via [ZUV Portal](https://zuvportal.uni-bamberg.de/){target=_blank}.

[Necessary contract documents](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsunterlagen/Einstellungsunterl_Hilfskraefte.zip){target=_blank}

**Mindestvertragslaufzeit**: Mit dem Tarifabschluss TV-L vom 09.12.2023 ist eine Mindestvertragslaufzeit für Hilfskräfte von mindestens 1 Jahr beschlossen worden. Nur in begründeten Einzelfällen kann von dieser Vorgabe abgewichen werden. Als Universität haben wir folgende Sachverhalte als Ausnahme definiert:

- Erstsemestereinführungstage
- Persönliche Gründe auf ausdrücklichem eigenen Wunsch der Hilfskraft
- Projektlaufzeit von unter einem Jahr
- Tätigkeiten als Tutor:in
- Begleitung von Tagungen

Jedem Ausnahmefall ist eine formlose Begründung zuzufügen, die vom direkten Vorgesetzten abzuzeichnen ist ([Formular zum Download](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Hilfskraefte/Begr%C3%BCndung_Vertragslaufzeit.pdf){target=_blank}). Sofern der Grund für die verkürzte Vertragslaufzeit in der Person der Hilfskraft liegt, muss auch diese unterschreiben.

## Student assistants: After completing the Bachelor/Master

Wenn ein Vertrag für eine SHK-Stelle mit abgeschlossenem Studium beantragen werden soll, das Abschlusszeugnis jedoch noch nicht vorliegt, besteht die Möglichkeit, den Vertrag trotzdem als „SHK mit Abschluss“ anzufragen.
Denn man kann beim Prüfungsamt eine Bestätigung über den bestandenen Studienabschluss beantragen, diese wird dann ausgestellt und zugeschickt oder kann auch im Prüfungsamt abgeholt werden. Diese Bestätigung ersetzt vorübergehend das Abschlusszeugnis und dient dem Personalamt als Nachweis für die Vertragserstellung.
Sobald das offizielle Abschlusszeugnis erstellt wurde, muss dieses lediglich von der SHK per E-Mail an das Personalamt mit dem Sekretariat im CC nachgereicht werden.

Send to **Referat III/2 (SHK Dienstvertrag/vertraulich)** via internal mail.

:::

::: {.callout-note title="Contracts: staff" collapse=true}

Submit documents at least 4 weeks before start of work to [HR](https://www.uni-bamberg.de/abt-personal/personal3-2/team-zustaendigkeiten/){target=_blank}:

[Application form](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsantraege_Weiterbeschaeftigungsantraege/Einstellungsantrag_nichtwissenschaftliche_Beschaeftigte.docx){target=_blank}

[Necessary contract documents](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsunterlagen/Einstellungsunterl_Besch_nichtwiss.zip){target=_blank}

Send to **Referat III/2 (Dienstvertrag/vertraulich)** via internal mail.
:::

::: {.callout-note title="Contracts: external lecturers" collapse=true}

Submit application form to deanery (until deadline sent by deanery via e-mail to professors and secretaries) and after the application was granted sent all other necessary contract documents to deanery:

[Application form](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsantraege_Weiterbeschaeftigungsantraege/Antrag_Erteilung_Lehrauftrag.docx){target=_blank}

[Necessary contract documents](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Einstellungsunterlagen/Einstellungsunterl_Lehrbeauftragte.zip){target=_blank}

Send to **Referat III/2 (vertraulich)** via internal mail.
:::

### Subsequent steps

- Contracts are stored in [hiring](/management/hiring.html).
- After creating an initial contract: order workstation etc.
- For student assistants, we can order a used laptop (if needed).
- Office and keys:

  - Transponder keys are provided by the janitor's office
  - The supervisor must first write an email to the janitor's office (name of employee, room nr)
  - Pick-up by employees

## Links

- [Checkliste Einstellung der Personalabteilung](https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Checklisten_bei_Einstellung_und_Beendigung/Checkliste_Einstellung.pdf){target=_blank}
- [HR: information and forms](https://www.uni-bamberg.de/abt-personal/formulare-infos-und-merkblaetter/){target=_blank}

::: {.callout-note title="TODO"}
Create "applicant page" and share with candidates (maybe instead of the PDF)?
:::
