---
title: "Onboarding"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": update complete process
:::

Welcome! We are pleased to welcome you as a new member of our team.
Together with the other handbook pages, this **onboarding page** will help you start your position smoothly.
Please do not hesitate to ask questions or request support.

<!--
Before your first day at work, you could explore Bamberg and get to know a few new places where you can spend some time after work. If you're interested in the local beer culture, you could try an authentic Schlenkerla Rauchbier and get to know a few new people. It's also a nice icebreaker for your first few conversations.
-->

## Setup

::: self-service
To join, please [create a GitHub account](https://github.com/signup){target=_blank} (if you do not have one yet) and start the onboarding process here: [Open Onboarding Issue](https://github.com/fs-ise/handbook/issues/new?template=request-onboarding.md){target=_blank}.
:::

Take a look at the [systems](systems_overview.html) page to get a first overview.

## First meeting

See [agenda](onboarding_first_meeting.html)

In the first meeting, we will talk about our goals and start your [agenda](agendas.html) repository.

## Development opportunities

<!--
### Social integration and university life

- Summer festival of the University of Bamberg 
- Schwof @LiveClub in Bamberg: Your goal should be to visit the very first Schwof on Mondays to get to know everyone and socialize a bit.
- Partycipate:
- Feki.de e.V. is the largest and most active Bamberg university-related group.
  The goal of Feki.de is to simplify the everyday life of students at the University of Bamberg and to promote the exchange of information among students.
  You can inform yourself on www.feki.de about everything that happens in Bamberg and around your university.


Training

- You can complete courses and gain further qualifications online at the VHS website.
-->

Training and development opportunities are crucial for the growth and success of our team.
They help team members acquire new skills, expand their knowledge, and stay updated with the latest advancements in their respective fields. 

- Identify Individual Needs: Start by conducting a skills assessment to identify the training needs of each team member.
  This can be done through one-on-one discussions, self-assessment forms, or performance evaluations.
  Encourage team members to express their interests and areas where they want to develop their expertise.
- Create a Training Plan: Based on the identified needs, develop a training plan that outlines the specific training programs or activities for each team member.
  Consider a mix of internal and external training options such as workshops, conferences, online courses, mentoring, and on-the-job training.
- Encourage Self-Learning: In addition to formal training programs, promote a culture of self-learning within the team.
  Encourage team members to explore relevant resources like online tutorials, books, research papers, and industry blogs.
  Provide access to online learning platforms or subscription services that offer a wide range of educational content.
- Internal Knowledge Sharing: Organize regular knowledge-sharing sessions where team members can present and discuss their ongoing projects, research findings, or new tools and techniques they have learned.
  Encourage collaboration and peer learning within the team.
- External Networking: Encourage team members to attend conferences, workshops, and seminars relevant to their research interests.
  Networking with experts in the field and participating in discussions and panels can provide valuable learning and collaboration opportunities.

### Job shadowing

- If you need further support, arranging a job shadowing day can be helpful. 

### Feedback

- Feedback and Support: We regularly check in with team members to assess their progress and provide support.
  We share learning experiences, challenges faced, and areas where we need further assistance.
  We offer guidance and mentorship to help all team members overcome obstacles and make the most of their development opportunities.

## Resources

- TODO: link relevant training resources in the handbook
- [GitHub tutorial](https://coderefinery.github.io/github-without-command-line/){target=_blank} 
- [ai onboarding](https://www.alexandria.unisg.ch/entities/publication/91fba548-c04d-4772-802e-0bc1db82680a){target=_blank} 

<!-- 
- Track Progress: Maintain a record of the training and development activities undertaken by each team member. This will help evaluate the effectiveness of the programs and identify any gaps or areas that need further attention. Use tools like spreadsheets or project management software to track and update training progress.
Remember, training and development should be an ongoing process. Continuously evaluate the impact of the programs and adjust the training plan as needed to ensure the team members are equipped with the skills and knowledge required to excel in their roles
-->
