---
title: "Publications"
---

# 29 Publications

Publications are listed in [FIS](https://fis.uni-bamberg.de/entities/person/b64b9fe6-7322-4c7f-8b84-89be565e3c46/publications){target=_blank}, and PDFs are available [here](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/20-20-research/29_publications&fileid=1264){target=_blank}.

## 2025

<div class="references">
  <p><b>Wagner, G.</b>, Ringeval, M., Raymond, L., & Paré, G. "Digital health competences and AI beliefs as conditions for the practice of evidence-based medicine: a study of prospective physicians in Canada". <i>Medical Education Online</i>, 30(1). doi:<a href="https://doi.org/10.1080/10872981.2025.2459910" target="_blank">10.1080/10872981.2025.2459910</a></p>
  <p>Li, L., Ringeval, M., <b>Wagner, G.</b>, Paré, G., Ozemek, C., & Kitsiou, S. (2025). Effectiveness of home-based cardiac rehabilitation interventions delivered via mHealth technologies: a systematic review and meta-analysis. <i>The Lancet Digital Health</i>, 7(4), e238-e254. doi:<a href="https://doi.org/10.1016/j.landig.2025.01.011" target="_blank">10.1016/j.landig.2025.01.011</a></p>
  <p><b>Wagner, G.</b>, and Thurner, L. "Rethinking How We Teach Git: Recommendations and Practical Strategies for the Information Systems Curriculum". <i>Journal of Information Systems Education</i>, 36(1), 1-12. doi:<a href="https://doi.org/10.62273/BTKM5634" target="_blank">10.62273/BTKM5634</a></p>
</div>

## 2024

<div class="references">
 <p>Paré, G., Castonguay, A., <b>Wagner, G.</b>, and Motulsky, A. "AI Maturity in Health Care: An Overview of 10 OECD Countries". <i>Health Policy</i>, 140, p.104938.</p>
 <p>Paré, G., Raymond, L., Castonguay, A., and <b>Wagner, G.</b> "Prospective Physicians’ Intention to Adopt Artificial Intelligence: A Configurational Perspective". in <i>Proceedings of the Hawaii International Conference on System Sciences</i>.</p>
 <p><b>Wagner, G.</b> “BibDedupe: An Open-Source Python Library for Bibliographic Record Deduplication”. <i>Journal of Open Source Software</i>, 9(97), 6318.</p>
</div>

## 2023

<div class="references">
 <p>Paré, G., <b>Wagner, G.</b>, and Prester, J. "How to develop and frame impactful review articles: Key recommendations". <i>Journal of Decision Systems</i>, 33(4), 566-582. doi:<a href="https://doi.org/10.1080/12460125.2023.2197701">10.1080/12460125.2023.2197701</a></p>
 <p><b>Wagner, G.</b>, Raymond, L, and Paré, G. "Understanding prospective physicians’ intention to use artificial intelligence in their future medical practice: A configurational analysis". <i>JMIR Medical Education</i>, 9, e45631.</p>
 <p>Morquin, D., Ologeanu-Taddei, R., Paré, G., and <b>Wagner, G.</b> "Design and Evaluation of a Method to Solve Organization-Enterprise System Misfits in the Post-Implementation Phase: An Action Research". <i>Information Systems Journal (ISJ)</i>, 33(5), 1–34.</p>
</div>

## 2022

<div class="references">
 <p><b>Wagner, G.</b>, Lukyanenko, R., and Paré, G. "Artificial Intelligence and the Conduct of Literature Reviews". Journal of Information Technology (JIT), 37(2), 209–226.<br>🏆 <a href="https://journals.sagepub.com/page/jin/jin-prize/prize-winning">Journal of Information Technology Best Paper Prize 2022</a></p>
 <p><b>Wagner, G.</b> and Prester, J. "A Framework of Platform Design Mechanisms, Platform Congruence and Value Creation on C2C Platforms". in Proceedings of the 29th European Conference on Information Systems (ECIS 2021), Marrakech, Morocco.</p>
</div>

## 2021

<div class="references">
 <p><b>Wagner, G.</b>, Prester, J., and Paré, G. "Exploring the Boundaries and Processes of Digital Platforms for Knowledge Work: A Review of Information Systems Research". <i>The Journal of Strategic Information Systems (JSIS)</i>, 30(4), 101694.</p>
 <p><b>Wagner, G.</b>, Prester, J., and Schryen, G. "Exploring the Scientific Impact of Information Systems Design Science Research". <i>Communications of the Association for Information Systems (CAIS)</i>, 48 (Paper 37), 379–423.</p>
 <p><b>Wagner, G.</b>, Prester, J., Roche, M. P., Schryen, G., Benlian, A., Paré, G., and Templier, M. "Which Factors Affect the Scientific Impact of Review Papers in IS Research? A Scientometric Study". <i>Information & Management (I&M)</i>, 58(3), 103427.</p>
 <p>Prester, J., <b>Wagner, G.</b>, Hassan, N. R., and Schryen, G. "Classifying the Ideational Impact of Information Systems Review Articles: A Content-Enriched Deep Learning Approach". <i>Decision Support Systems (DSS)</i>, 140, 113432.</p>
 <p>Grenier-Ouimet, A., <b>Wagner, G.</b>, Raymond, L., and Paré, G. "Investigating Patients’ Intention to Continue Using Teleconsultation to Anticipate Postcrisis Momentum: Survey Study". <i>Journal of Medical Internet Research (JMIR)</i>, 22(11), e22081.</p>
 <p>Schryen, G., <b>Wagner, G.</b>, Benlian, A., and Paré, G. "A Knowledge Development Perspective on Literature Reviews: Validation of a New Typology in the IS Field," <i>Communications of the Association for Information Systems (CAIS)</i>, 46 (Paper 7), 134–186.</p>
 <p>Yasasin, E., Prester, J., <b>Wagner, G.</b>, and Schryen, G. "Forecasting IT Security Vulnerabilities - An Empirical Analysis," <i>Computers & Security (C&S)</i>, 88, 1–23.</p>
 <p>Prester, J. and <b>Wagner, G.</b> "Contracting Decisions on Digital Markets for Knowledge Work Services: A Qualitative Systematic Review," in <i>Proceedings of the 42nd International Conference on Information Systems (ICIS 2021)</i>, Austin, Texas.</p>
</div>

## 2020

<div class="references">
 <p>Ringeval, M., <b>Wagner, G.</b>, Denford, J., Paré, G., and Kitsiou, S. "Fitbit-Based Interventions for Healthy Lifestyle Outcomes: Systematic Review and Meta-Analysis". <i>Journal of Medical Internet Research (JMIR)</i>, 22(10), e23954.</p>
 <p>Grenier-Ouimet, A., <b>Wagner, G.</b>, Raymond, L., and Paré, G. "Investigating Patients’ Intention to Continue Using Teleconsultation to Anticipate Postcrisis Momentum: Survey Study". <i>Journal of Medical Internet Research (JMIR)</i>, 22(11), e22081.</p>
 <p>Schryen, G., <b>Wagner, G.</b>, Benlian, A., and Paré, G. "A Knowledge Development Perspective on Literature Reviews: Validation of a New Typology in the IS Field," <i>Communications of the Association for Information Systems (CAIS)</i>, 46 (Paper 7), 134–186.</p>
 <p>Grenier-Ouimet, A., Paré, G., and <b>Wagner, G.</b> "Why do People Keep Consulting Physicians Online? A Study of Teleconsultation Continuance Intention," in <i>Proceedings of the 2020 Conference of the Administrative Sciences Association of Canada (ASAC 2020)</i>.<br>🏆 Best Paper Award, IS Division.</p>
 <p><b>Wagner, G.</b>, Empl, P., and Schryen, G. "Designing a Novel Strategy for Reading and Skimming Literature Corpora," in <i>Proceedings of the 28th European Conference on Information Systems (ECIS 2020)</i>, Marrakech, Morocco.</p>
 <p>Hassan, N. R., Prester, J., and <b>Wagner, G.</b> "Seeking Out Clear and Unique Information Systems Concepts: A Natural Language Processing Approach," in <i>Proceedings of the 28th European Conference on Information Systems (ECIS 2020)</i>, Marrakech, Morocco.</p>
</div>
 
## 2019

<div class="references">
 <p><b>Wagner, G.</b>, Prester, J., and Schryen, G. "Information Systems Research on Digital Platforms for Knowledge Work: A Scoping Review," in <i>Proceedings of the 40th International Conference on Information Systems (ICIS 2019)</i>, Munich, Germany.</p>
</div>

## 2018

<div class="references">
 <p>Heinrich, B., Klier, M., Schiller, A., and <b>Wagner, G.</b> "Assessing Data Quality - A Probability-based Metric for Semantic Consistency," <i>Decision Support Systems (DSS)</i>, 110, 95-106.</p>
 <p>Schuster, R., <b>Wagner, G.</b>, and Schryen, G. "Information Systems Design Science Research and Cumulative Knowledge Development: An Exploratory Study," in <i>Proceedings of the 39th International Conference on Information Systems (ICIS 2018)</i>, San Francisco, California, USA.<br>🏆 Best Theory Paper Award, ICIS 2018.</p>
 <p>Prester, J., <b>Wagner, G.</b>, and Schryen, G. "Classifying the Ideational Impact of IS Review Articles: A Natural Language Processing Based Approach," in <i>Proceedings of the 39th International Conference on Information Systems (ICIS 2018)</i>, San Francisco, California, USA.</p>
</div>

## 2017

<div class="references">
 <p>Schryen, G., <b>Wagner, G.</b>, and Schlegel, A. "Development of Two Novel Face-recognition CAPTCHAs: A Security and Usability Study," <i>Computers & Security (C&S)</i>, 60, 95-116.</p>
 <p><b>Wagner, G.</b>, Prester, J., and Schryen, G. "Exploring the Scientific Impact of Information Systems Design Science Research: A Scientometric Study," in <i>Proceedings of the 38th International Conference on Information Systems (ICIS 2017)</i>, Seoul, South Korea.</p>
</div>

## 2016

<div class="references">
 <p>Schryen, G., <b>Wagner, G.</b>, and Schlegel, A. "Development of Two Novel Face-recognition CAPTCHAs: A Security and Usability Study," <i>Computers & Security (C&S)</i>, 60, 95-116.</p>
 <p><b>Wagner, G.</b>, Prester, J., Roche, M., Benlian, A., and Schryen, G. "Factors Affecting the Scientific Impact of Literature Reviews: A Scientometric Study," in <i>Proceedings of the 37th International Conference on Information Systems (ICIS 2016)</i>, Dublin, Ireland.</p>
</div>

## 2015

<div class="references">
 <p>Schryen, G., <b>Wagner, G.</b>, and Benlian, A. "Theory of Knowledge for Literature Reviews: An Epistemological Model, Taxonomy and Empirical Analysis of IS Literature," in <i>Proceedings of the 36th International Conference on Information Systems (ICIS 2015)</i>, Fort Worth, Texas, USA.</p>
 <p>Weishäupl, E., Kunz, M., Yasasin, E., <b>Wagner, G.</b>, Prester, J., Schryen, G., and Pernul, G. "Towards an Economic Approach to Identity and Access Management Systems Using Decision Theory," in <i>2nd International Workshop on Security in Highly Connected IT Systems (SHCIS 2015)</i>, Vienna, Austria.</p>
</div>

