---
title: "Resources misc"
transition_status: "toupdate"
transition_comment: "Update keys, lab access, printing/scanning, design, archive"
---

::: callout-note
This section is marked as "toupdate": update complete process
:::

## Transponders (keys)

- Transponder keys are provided by the janitor's office
- The supervisor must first write an email to the janitor's office
  - Name of employee
  - Rooms
- Pick-up by employees

## Lab access

- For group meetings, reservations for the ISM lab (1.094) can be made via the shared [Labor ISM (1.094)](https://mailex.uni-bamberg.de/owa/#path=/calendar/view/Month){target=_blank} calendar.

## Virtual machines

- Access to virtual machines, e.g., for student projects, can be requested through the IT department [1](https://www.uni-bamberg.de/its/wir/mitarbeiter/mai/){target=_blank}.

## HPC

- [NHR - FAU](https://hpc.fau.de/){target=_blank} - [Apply for access](https://hpc.fau.de/application-for-bayernki-access/){target=_blank}

## Printing and scanning

- Our printer (HP-LaserJet-P3010-Series) can be used by all team members (available when connected to LAN in 1.081)
- [Campusprint](https://www.uni-bamberg.de/campusprint/){target=_blank}, [VPN](#vpn) access needed, payment with a chip card
- Scanning: TBD.

## Design

- [IconMonster](https://iconmonstr.com/?s=git){target=_blank}
- [Font Awesome Icons](https://fontawesome.com/v4/icons/){target=_blank}
- [QR codes](https://www.resourcefuldev.com/qr-code-generator/){target=_blank}

## Archive

- The archive room WE5/05.058 is available to store theses and seminar papers.
  Access (key) is managed by the Team Assistant's office.

<!-- 
Templates: letters, etc. -> directory
-->
