---
title: "Software overview"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note

TODO: highlight what is (not) installed with ansible (workstation-setup)

:::



## Machine setup

- [Eduroam](https://www.uni-bamberg.de/its/dienstleistungen/netz/wlan/eduroam/){target=_blank}: Log-in with university credentials
- [VPN](https://www.uni-bamberg.de/its/dienstleistungen/netz/vpn/einrichten/){target=_blank}: Some Services are only available via VPN or within the university network
- [Proxy servers](https://dataimpulse.com/#pricing){target=_blank}: Residential proxy server service
- [LanguageTools](https://languagetool.org/de){target=_blank}: Free Online Spellchecker (local setup: see academy)


- [Systems for teaching](/teaching/systems.html)
- [Systems for research](/research/systems.html)

System | Description |
---|---|
[Mail](https://www.uni-bamberg.de/its/dienstleistungen/mail/zugriff/){target=_blank}| - Every member of the university gets a mail assigned<br>- [Personnel](https://www.uni-bamberg.de/its/dienstleistungen/mail/wlv/){target=_blank} has the format `firstname.surname@uni-bamberg.de` while [student](https://www.uni-bamberg.de/its/dienstleistungen/mail/studium/){target=_blank} mail addresses have the format `firstname1-firstname2-firstname3-(...).surname@stud.uni-bamberg.de`<br>- The messages are accessible via [Outlook](https://www.uni-bamberg.de/its/dienstleistungen/mail/zugriff/outlook/){target=_blank} or any other e-mail client |
Teams | - Platform for collaboration and organization, allowing users to create different areas called "Teams" to work together or manage part of their online teaching<br>- Shared chat and separate chats in different channels<br>- Lectures and seminars can be held as phone or video meetings with up to 250 participants<br>- Recording functionality<br>- Collaborate on files within a team |
[Zoom](https://www.uni-bamberg.de/its/dienstleistungen/tele/video/zoom/){target=_blank}| - Single-Sign-On-Url: ``uni-bamberg``<br>- Online service for web conferencing<br>- Teaching as Meetings or Webinars<br>- Recording functionality<br>- For events that exclusively involve members students of our university, please use [Teams](#teams) because of data security and privacy concerns |
[Calendly](https://calendly.com/event_types/user/me){target=_blank}| - Allow students to book appointments, which are automatically added to the Outlook calendar<br>- Example: [30-minute meeting](https://calendly.com/gerit-wagner/30min?month=2023-07){target=_blank} |
[Nuudel](https://nuudel.digitalcourage.de/){target=_blank}| - Doodle replacement |

## Outlook: Calendar permissions

Sharing calendars -> You decide what the other person can see<br>
Permission settings -> In your own calendar, click on "Eigenschaften" -> "Berechtigungen"<br>

## Resources

- [Youtube procedure](https://intranet.neuro.polymtl.ca/computing-resources/youtube.html){target=_blank}
