---
title: "Transition"
---

## Handbook pages

- [x] Consolidate [github workflows](https://github.com/fs-ise/handbook/tree/main/.github/workflows){target=_blank}.
  - [x] regularly run generate-projects-pages.py
- [x] Set repository secrets for actions (e.g., `LABOT_PAT_TOKEN`).
- [x] Imports: see new handbook (local import.py)
- [x] Structure: areas / processes / alphabetical (instead of johnny decimal)
- [x] Postprocessing:
  - [x] remove "tocs" on pages (generated automatically)
  - [x] visual check (images, figures, links)
  - [x] check/fix links
  - [x] Check for self-service boxes
  - [x] Check for Johnny-Decimal references
- [x] Restructure and link nextcloud (e.g., confidential links to grades: lectures, theses, ...; archive; hr)
- [x] Regular updates of the [timeline](/management/statement.html#annual-cadence) and [here](/teaching/index.html)
- [ ] Move nextcloud/mail_tracker to repository
- [ ] Search for references to the "digital work lab"
- [ ] Consolidate [state model](/teaching/course_overview.html) with process overview in [courses](/teaching/courses/2026-SuSe-BDA.html#process) - also add validation script


## Repositories

- Decide which repositories will remain in the old organization, and which ones will be moved.
- Upgrades to quarto:

  - [x] theses
  - [ ] open-source-project
  - [ ] literature-review-seminar
  - [ ] digital-work-lecture
  - [ ] ... 

- [ ] Change buttons from "Offered by digital work lab" to "Offered by ISE (Frankfurt School)"
- [ ] Search for references to the "digital work lab"

## Other

- [x] Return library
- [x] Team / alumni / recommendation letters / offboarding
- [ ] Machine setup
  - [ ] E-Mail (plus authenticator)
  - [ ] Windows VM
- [ ] Update e-mail footer
- [ ] Update affiliations and emails on [profiles](/team/index.html#gerit-wagner-professor){target=_blank}
- [ ] Change e-mail in submission systems
- [ ] Update Calendly
- [ ] [Labot account](https://github.com/digital-work-labot){target=_blank}
- [ ] Check: returning devices (will be collected by the IT service)

## Pages that require an update for the transition

To mark pages that require changes, the `transition_status` and `transition_comment` fields can be added to the yaml header as follows:

```markdown
---
title: "Resources"
transition_status: "toupdate"
transition_comment: "Update keys, lab access, printing/scanning, design, archive"
---

contents ....

```

Once the transition is implemented, the `transition_status` can be changed to `updated`.

---
listing:
  title: "Pages to change"
  contents: ../**
  type: table
  sort: "path"
  fields: [path, title, transition_comment]
  include:
    transition_status: "toupdate"
  page-size: 200
---
