---
title: "Advertising"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": update completely
:::

## Choose-a-chair event

- TODO : link in dates to track
- Preparation: print topics for theses (add new ones), summarize courses for the next semester
- Update poster and have it printed ([link](https://github.com/digital-work-lab/handbook/tree/main/assets/docs/teaching-poster){target=_blank})

## Fachschaft: E-Mail Verteiler

- [VC-Kurs: Aktuelle Informationen der Fachschaft WIAI](https://vc.uni-bamberg.de/user/view.php?id=1157&course=284){target=_blank}

## Website

TODO

## Pinboards

TODO

## Lectures etc.

We provide an overview of the other teaching activities at the beginning and end of the lectures (IDW).

## Instagram

### Project OSP

::: callout-note
- Previous posts: [1](https://www.instagram.com/informatik_unibamberg/p/CyQd-OXIl9R/){target=_blank}, [2](https://www.instagram.com/informatik_unibamberg/p/DI3iAAvITII/?img_index=1){target=_blank}
:::

Von Prof. Dr. Gerit Wagners Juniorprofessur für Wirtschaftsinformatik, insbesondere Digital Work stellen wir Euch zwei Lehrveranstaltungen für Euren Sommersemester-Stundenplan vor:
In dem Open Source Projekt der Wirtschaftsinformatik (WI-Projekt für Bachelorstudierende) lernt Ihr Programmieren mit Python. Außerdem lernt Ihr den Umgang mit Git und werdet Git-basierte Open Source Workflows und Entwicklungsumgebungen verstehen und verwenden. Dabei sollen im Rahmen eines bestehenden Open-Source-Projektes ausgewählte Funktionalitäten in kleinen Teams entwickelt und eingebracht werden. Die Teilprojekte werden in der ersten Einheit der Veranstaltung am **30. April**, vorgestellt. Bitte meldet euch bei Interesse per E-Mail.

Mehr Infos findet Ihr unter:
www.uni-bamberg.de/digital-work/studium/bachelor/wi-projekt-open-source-projekt

Bring your passion, and let's code together!

### Lecture IDW

::: callout-note
- Previous posts: [1](https://www.instagram.com/informatik_unibamberg/p/DI3iAAvITII/?img_index=2){target=_blank}
:::

Die Vorlesung Introduction to Digital Work (Bachelor) vermittelt einen Überblick über das spannende Themenfeld der digitalen Arbeit mit Fokus auf zentrale Gestaltungsbereiche. Der Kurs behandelt globale Trends und Treiber des Wandels (Future of Work), die Gestaltung digitaler Arbeit auf individueller Ebene, im Team und mit Crowdworkern sowie die Folgen digitaler Arbeit. Ihr entwickelt ein fundiertes Verständnis für Veränderungen, Gestaltungsbereiche und Auswirkungen digitaler Arbeit und lernt ein Repertoire an Methoden, Designprinzipien und organisationalen Policies kennen, das Ihr situationsgerecht anwenden könnt. Zudem diskutieren wir, wie sich einzelne Maßnahmen evaluieren lassen – damit Ihr digitale Arbeit effektiv und verantwortungsvoll gestalten könnt.

Die erste Veranstaltung findet am Montag, den **28.04.2025, statt (von 8:15–11:45 Uhr im Raum WE5/04.003)**.

Mehr Infos findet Ihr unter:
👉 https://www.uni-bamberg.de/digital-work/studium/bachelor/introduction-to-digital-work/

Let's explore the future of work together!


### Seminar LRSem

::: callout-note
- Previous posts: [1](https://www.instagram.com/informatik_unibamberg/p/CyRI7QLvxWB/){target=_blank}
:::

Im Masterseminar "Literature Review Seminar" steht die Methode der Literaturübersicht im Fokus. Ziel ist es, den Methodenpluralismus innerhalb des Literature Review Genres zu verstehen und die Prozessschritte nachzuvollziehen, zu planen, und an die Ziele des Reviews anzupassen. Ihr werdet die Qualität von Literature Reviews in verschiedenen Dimensionen diskutieren sowie geeignete Software für die Umsetzung auswählen.
Das Masterseminar empfiehlt sich als Vorbereitung für Eure Masterarbeiten oder Dissertationen.

Bitte meldet Euch bis zum **20. April** mit Angabe von Name, Matrikelnummer, Studiengang und Fachsemester an – per Email an gerit.wagner@uni-bamberg.de!

Die Termine finden an zwei Blockterminen statt: **Freitag, den 10.05. und 17.05. von 8.15-15.45 Uhr im Raum WE5/05.005**.

Mehr Infos zum Seminar findet Ihr https://www.uni-bamberg.de/digital-work/studium/master/seminar-dw-sem-m/ 👈

Share our excitement for literature reviews and join the seminar!
