---
title: "Evaluations"
transition_status: "toupdate"
transition_comment: "update"

listing:
  id: course-evaluations
  contents: courses
  type: table
  fields: ["semester", "title", "student_evaluations"]
  sort: "semester desc"
  sort-ui: false
  categories: false
  page-size: 20
---

::: callout-note
This section is marked as "toupdate": update completely
:::

## Purpose

Evaluate teaching activities **at the end of each semester**.

::: callout-note
**Trigger**
Evaluations can be ordered by **early December / early July**. We receive an e-mail reminder.
:::

## Process

- Evaluations can be ordered via EvaSys, which requires a **minimum of 5 students** to complete the evaluation. Otherwise, anonymity is not given, and results will not be made available.
- For small courses, it is possible to use other tools or modes of evaluation.
- It is possible and recommended that the survey be adapted (shortened).
- Evaluation results and potential improvements should be discussed with students (last week of teaching).
- Students should be reminded in the session and via VC.
- Add to the list of prior reports below.
- The evaluation results are stored in 19.XXXXXX (Nextcloud) and published in the handbook: Upload PDFs in [assets/evaluations](https://github.com/fs-ise/handbook/tree/main/assets/evaluations){target=_blank} and link them in the [course files](https://github.com/fs-ise/handbook/tree/main/_courses){target=_blank}.
- Evaluation results should be analyzed to improve teaching activities. Improvements are documented in the [Improvements](/teaching/improvements.html) section.
- Evaluation results are shared (e.g., via e-mail or link in VC) and discussed with students.

Note: We are allowed to publish evaluation reports (no personal information, no hand-written responses that could identify individuals).

::: callout-note
To use a QR code in the session, ask the [QM team](https://www.uni-bamberg.de/pqm/qualitaetsmanagement/){target=_blank}.
:::

## Example for the invitation to the evaluation

> Dear Students,
>
We would like to invite you to participate in the upcoming course evaluation. Your feedback is voluntary and anonymous, so please be open and honest in your responses. Your participation helps us improve the quality of our courses, and we highly value your opinions.
>
> Please rest assured that your responses will remain confidential, and there is no risk of disadvantage or negative consequences for you, regardless of the feedback you provide.
>
> Thank you for your time and honest feedback!

## Systems

Create or edit a survey ([account](https://www.uni-bamberg.de/its/dienstleistungen/eva/evasys/){target=_blank} required - [form](https://www.uni-bamberg.de/its/dienstleistungen/eva/evasys/antrag-benutzerkonto-in-evasys/){target=_blank}):

- [EvaSys](https://evasys.uni-bamberg.de/evasys/public/ui/){target=_blank}

Order an evaluation: [RZ intern](https://www.uni-bamberg.de/its/lehrevaluation/){target=_blank}

## Survey

**The Lecturer and Your Course**

- The lecturer's competence / expertise in the subject area.
- The lecturer's teaching style (rhetorical skills, methods, etc.).
- The lecturer's accessibility and approachability.
- The structure of the course.
- The materials provided by the lecturer (scripts, slides etc.).
- The overall quality of the course.

**Your Spent Workload**

- Average amount of time (assignments & self-study) needed for 1 academic hour (45 minutes):
- Study time generally needed for this course compared to the indicated workload (i.e. in the module description):

**General Aspects of Your Course**

- The overall course level was... (extremely hard <-> extremely easy)
- The relevance of the course was...
- The atmosphere in class (discussion, cooperation etc.) was...
- The overall organisation of the course was...

**Your Comments and Suggestions**

- In the course with [lecturer], I especially liked...
- For the course with [lecturer], I suggest the following changes...

## Evaluation results

::: {#lecture-listing}
:::

## Applicable regulations

- [Evaluation der Lehre (ยง5 and ยง6)](https://www.uni-bamberg.de/fileadmin/www.abt-studium/Rechtsvorschriften/1Organisation/Evaluation%20Lehre%20Studium/180305-O-Sicherung-Qualitaet-Lehre-Studium.pdf){target=_blank}
- [Overview: Goals, procedure, data protection etc.](https://www.uni-bamberg.de/qm/evaluation/lehrveranstaltungsevaluation/schriftliche-lehrveranstaltungsevaluation/){target=_blank}

