---
title: "FlexNow"
transition_status: "toupdate"
transition_comment: "completely update"
---

::: callout-note
This section is marked as "toupdate": completely update
:::

## System

- [FlexNow](https://fn2web.zuv.uni-bamberg.de/FN2AUTH/FN2AuthServlet?op=Login)

## Create courses

- In der Regel bereits vorhandene LV kopieren
- FlexNow - Menü - LV-Verwaltung - LV wählen - Kopieren nach Semester xy

## Entering grades

::: callout-note
The grading process is documented [here](/teaching/exams.html).
:::

- [Login: FlexNow](https://fn2web.zuv.uni-bamberg.de/FN2AUTH/FN2AuthServlet?op=Login){target=_blank} - Lehrstuhlmodul - Prüfungsteilnehmer / zentral organisiert / Veranstaltung auswählen / Teilnehmer laden
- Formular zum Ändern einzelner Teilnehmer: Noten eingeben (Punkte müssen nicht eingegeben werden), speichern und weiter
- Oder CSV: export (utf-8), add grades/points via vlookup, import (csv-format: semicolon, no quotes)
- Im oberen Bereich: Teilnehmer laden, drucken, exportieren via LV-Semester:
"Noten endgültig freischalten und verbuchen" ([14.01](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/10-lab/14_grades/01_lectures&fileid=71){target=_blank}). After the activation, changes can only be made through the examination office (wiai.pruefungen@uni-bamberg.de)
- Only store grades as PDF (not as csv)?
- Klausuren entsprechend der Reihenfolge im PDF sortieren.

Projekt:

- Dezentral
- "Teilnehmer hinzufügen"
- Noten eintragen
- Noten freigeben
- Noten als PDF in 14.02 ablegen (ggf. Excel-Datei löschen)

::: callout-note
If grades cannot be entered, reach out to the FlexNow team via e-mail: [flexnow@uni-bamberg.de](mailto:flexnow@uni-bamberg.de>).
:::

## ERASMUS students

For ERASMUS students, the FlexNow team has to assign students to modules. Use the following e-mail template:

```Markdown
Betreff: Anlage eines Moduls für ERASMUS Studierende

Liebe Kolleginnen und Kollegen des FlexNow-Teams,

Darf ich Sie bitten, in FlexNow das nachstehende Modul für die unten genannten ERASMUS-Studierenden anzulegen:

* **Modulhandbuch:** Modulhandbuch Bachelor Wirtschaftsinformatik – Studienbeginn ab dem WS 2024/2025
* **Modultitel:** LV\_721\_114387\_1\_81\_1 – Digital-Work-Projekt-B: Bachelorprojekt aus der Fächergruppe Wirtschaftsinformatik (Wagner)

Für folgende Studierende:

* Student name (student ID)
* Student name (student ID)
* Student name (student ID)

Vielen Dank im Voraus!

Mit freundlichen Grüßen
Gerit Wagner
```

Once students can be selected, double-check the number of ECTS before submitting grades.
