---
title: "LMS (Canvas)"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": update completely
:::

## Good practices

- General information (rooms, dates, ...)
- Overview of sessions and topics
- Teaching concept
- Structure: `2. ERP-Prozesse | 08.07.-13.07.` (containing slides, video, quit/exercise)
- Quiz-Fragen
- Fragestunde
- Literature (end)
- Syllabus document: Expectations and relevant information (dates, bonus, support, ...)
- Offer previous exams

Welcome E-Mail at the beginning, Welcome video (top of the VC course) - switch role to student, explain how the VC-course is organized

- [Example](https://vc.uni-bamberg.de/course/view.php?id=67883){target=_blank}, [example](https://vc.uni-bamberg.de/course/view.php?id=68017){target=_blank}, [example](https://vc.uni-bamberg.de/course/view.php?id=61226){target=_blank}
- [Syllabus example](https://web.psi.uni-bamberg.de/teaching/syllabi/de-eirbs-syllabus-2023.html){target=_blank}

## Creating an anonymous forum

The module for creating an anonymous forum is not activated in VC, but there is a workaround.

- Set up an new email account (Gmail or similar), keep the password confidential.
- Create a new "self-registered" user account for the VC (https://vc.uni-bamberg.de/moodle/login/signup.php/?lang=en). Name the username "Anonymous". Share the set password for the account and the username in the course.
- Students can log in with the shared account (instead of their own) and post in the VC using it. It is important that when logging in, the login details for the anonymous account are entered in the form under "Login with separate account by email". It does not work with "Login for University of Bamberg".
