---
title: "New course"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
Update the templates (in line with quarto)!
:::

## Setup

Courses are [here](https://github.com/fs-ise/handbook/tree/main/teaching/courses){target=_blank}.

To set up a new lecture, seminar, or project:

- Add a [new module](#new-module) if necessary.
- Announcement and scheduling is documented [here](../management/course_organization.html)
- Create a [new lecture, seminar, or project](https://github.com/digital-work-lab/handbook/new/main/_courses){target=_blank} with this filename pattern: `2023-SuSe-IDW.md` based on the right template:

::: {.callout-note title="Lecture template" collapse=true}

```markdown
---
layout: default
title: IDW
title_long: The Literature Review Seminar
parent: 32 Courses
grand_parent: Teaching
semester: 20XX-WiSe
status: ⟳
student_evaluations: ""
improvement_issue: ""
improvement_status: N/A
---

# IDW 20XX WiSe

Field               | Value
------------------- | -------------------
Title               | {{ page.title_long }}
Lecturer            | Gerit Wagner
Link: VC            | TODO
Link: Website       | [Website](https://www.uni-bamberg.de/digital-work/studium/bachelor/introduction-to-digital-work/){target=_blank}
Status              | {{ page.status }}
Student Evaluations | {% if page.student_evaluations != "" %} <a href="/assets/evaluations/{{ page.student_evaluations }}" target="_blank">PDF</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Improvement Issue   | {% if page.improvement_issue != "" %} <a href="{{ page.improvement_issue }}" target="_blank">Issue Link</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Status of Revisions | {{ page.improvement_status }}

## Process

## 1. Announce the course (4 months before)
 
Start: December (summer term), May (winter term)

- [ ] Team Assistant: Create the course in FlexNow.

At the end of the semester: 

- [ ] Professor: Announce lecture on the website for the next semester (without dates/rooms).
- [ ] Team Assistant: Update information in UnivIS (add keywords „WI-Seminar“ and „WI-Seminare“ for seminars), check information on the website.

Deadline: mid-May (summer term), December/January (winter term)

## 2. Prepare the course (1 month before)

Start: March (summer term), September (winter term)

- [ ] Team Assistant and Professor: Set dates and request lecture rooms.
- [ ] IT department: The courses are created 7 weeks before the start of the semester (automatically based on UnivIS).
- [ ] Have the lecture announced on [Instagram](https://www.instagram.com/informatik_unibamberg/){target=_blank} (see [dissemination](/research/dissemination.html))
- [ ] Professor: Create a reminder for the evaluations.
- [ ] Team Assistant: Add moderator and session dates in VC.
- [ ] Professor: Summarize the feedback from the last course and explain how it was addressed.
- [ ] Professor: Activate course in VC (visible to students).

Deadline: April (summer term), October (winter term)

## 3. Offer the course

Start: April (summer term), October (winter term)

- [ ] Professor: Schedule evaluations in the pen-ultimate week ([30.21.evaluations](/teaching/evaluations.html)).
- [ ] Team Assistant: Order exam materials (Prüfungspapier, Mantelbögen).
- [ ] Professor (Team Assistant): Prepare the exams (Deadline: day of the exam), information is typically provided one month before the semester ends (E-Mail: "Prüferbestellung"). Use the [exam checklist](/management/exams.html#preparing-the-exam).
- [ ] Add exam dates to the [calendar](../../calendar/events.yaml)
- [ ] Scheine ([Formular](https://www.uni-bamberg.de/ism/studium/anmeldung-scheinklausur/){target=_blank}), Scheinklausur-anmeldungen bei Erstellung der Klausurbögen berücksichtigen

## 4. Exam grading and documentation

Before grading (day of the exam)

- [ ] Professor: Cases of cheating (Unterschleif): immediately enter it into FlexNow and send the exam to the examination office (do not grade it)
- [ ] Professor: Cases of missed exams (Versäumnisklausuren): immediately enter it into FlexNow, archive the exams for 1 year.
- [ ] Professor: Send the exam sheets, protocols (Anwesenheitslisten), and two empty exams to the examination office immediately after the exams are completed.
- [ ] Team Assistant: Empty exams (Versäumnis-Klausur): archive for one semester.

Grading

- [ ] Create a reminder for the deadline: approx. 15. September (summer term), ??? (winter term). Grade early because colleagues may be on vacation before the deadline (not available to review failed exams).
- [ ] Add bonus points if any and **if exam is passed**. Otherwise, note the bonus points and add a note "kann nicht angerechnet werden".
- [ ] Do not dispose of empty exams
- [ ] Use the [grading scripts](https://github.com/digital-work-lab/handbook/tree/main/src/grading){target=_blank} to assign grades and prepare FlexNow import
- [ ] Check whether to adjust the grades of narrowly failing exams upwards and, if necessary, lower the passing threshold in favor of students
- [ ] Have failed exams reviewed by a second professor (must be completed before entering grades in FlexNow)

Entering Grades into FlexNow

- [ ] Team Assistant: [Enter grades in FlexNow](/teaching/flexnow.html#entering-grades) (or create certificates if exam is not yet available in FlexNow ([script](https://github.com/digital-work-lab/handbook/tree/main/src/scheine){target=_blank})).
- [ ] Professor: Archive bonus exercises (if any).

Sending exams to the examination office

- [ ] Professor: Exams are sent to the examination office (in person): [Silke Nüßlein](https://univis.uni-bamberg.de/prg?search=persons&show=info&department=322130&fullname=Silke+Nue%C3%9Flein){target=_blank}, Kapuzinerstr. 25, 00.01

Documentation

- [ ] Professor: Analyse the evaluations, store the files, and document the improvements (see [evaluations](/teaching/evaluations.html)).
- [ ] Professor: Document necessary changes for the following exams (e.g., unclear questions, too many questions)

Deadline: End of August (summer term), March (winter term)

## 5. Repeat exam (following term)

Students have the possibility to repeat the exam in the following term (even if the lecture is not offered again). Registration for students in FlexNow is created by the examination office. (true???)

- [ ] Professor: Upon notification by the examination office (E-Mail: "Prüferbestellung"), create the repeat exam. Student registrations are available in FlexNow.
- [ ] Repeat relevant steps of *Exams and documentation* (step 4) 

Students can review their exams and grades in person (Einsichtnahme) on the dates set by the examination office ([link](https://www.uni-bamberg.de/pruefungsamt/einsichtnahmen/){target=_blank}).
```
:::

::: {.callout-note title="Seminar template" collapse=true}

```markdown
---
layout: default
title: LRSem
title_long: The Literature Review Seminar
parent: 32 Courses
grand_parent: Teaching
semester: 20XX-WiSe
status: ⟳
student_evaluations: ""
improvement_issue: ""
improvement_status: N/A
---

# LRSem 20XX WiSe

Field               | Value
------------------- | -------------------
Title               | {{ page.title_long }}
Lecturer            | Gerit Wagner
Link: VC            | TODO
Link: Website       | [the-literature-review-seminar](https://digital-work-lab.github.io/literature-review-seminar/){target=_blank}, [Website](https://www.uni-bamberg.de/digital-work/studium/bachelor/seminar-digital-work/){target=_blank}
Status              | {{ page.status }}
Student Evaluations | {% if page.student_evaluations != "" %} <a href="/assets/evaluations/{{ page.student_evaluations }}" target="_blank">PDF</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Improvement Issue   | {% if page.improvement_issue != "" %} <a href="{{ page.improvement_issue }}" target="_blank">Issue Link</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Status of Revisions | {{ page.improvement_status }}

## Process

- FlexNow: Seminars must be created for each semester (decentral exams), a seminar paper and presentation are mandatory
- Grading: The Team Assistant registers students for the seminar, enters grades, and submits them online. Students do not need to register on FlexNow.

## 1. Announce the seminar (4 months before)
 
Start: December (summer term), May (winter term)

- [ ] Team Assistant: Create the course in FlexNow.

{: .highlight }
>  Check public holidays
>
> Flexnow: Besonderheiten bei Ausstattung/Hinweise:
> 
> - 8h Semesterwoche 5, Freitag, Blocktermin, Seminarraum
> - 8h Semesterwoche 6, Freitag, Blocktermin, Seminarraum

At the end of the semester: 

- [ ] Professor: Announce the seminar on the website for the next semester (without dates/rooms).
- [ ] Team Assistant: Update information in UnivIS (**add keywords „WI-Seminar“ and „WI-Seminare“**), check information on the website.
- Note: If the course is mentioned on the website, it should automatically be announced in the [Fachschaft WIAI newsletter](https://vc.uni-bamberg.de/course/view.php?id=284){target=_blank}{target=_blank}

Deadline: mid-May (summer term), December/January (winter term)

## 2. Prepare the seminar (1 month before)

Start: March (summer term), September (winter term)

- [ ] Team Assistant and Professor: Set dates and request lecture rooms.
- [ ] IT department: Create the VC course, two weeks before the semester starts (automatically based on UnivIS).
- [ ] Have the seminar announced on [Instagram](https://www.instagram.com/informatik_unibamberg/){target=_blank} (see [dissemination](/research/dissemination.html))
- [ ] Professor: Create a reminder for the evaluations.
- [ ] Team Assistant: Add moderator and session dates in VC.
- [ ] Professor: Summarize the feedback from the last course and explain how it was addressed.
- [ ] Professor: Activate course in VC (visible to students).

Deadline: April (summer term), October (winter term)

## 3. Offer the seminar

Start: April (summer term), October (winter term)

- [ ] Team Assistant: Add the presentation (exam) dates to the department calendar
- [ ] Professor: Set deadline for protocol submissions (upload in VC).
- [ ] Professor: Set the date for the presentation.
- [ ] Professor: Add presentation dates to the [calendar](../../calendar/events.yaml)
- [ ] Professor: Schedule evaluations in the pen-ultimate week ([30.21.evaluations](/teaching/evaluations.html)).

## 4. Grading and documentation

Grading

- [ ] Create a reminder for the deadline.
- [ ] Use the [grading scripts](https://github.com/digital-work-lab/handbook/tree/main/src/grading){target=_blank} to assign grades and prepare FlexNow import

Entering Grades into FlexNow

- [ ] Team Assistant: [Enter grades in FlexNow](/teaching/flexnow.html#entering-grades) (or create certificates if exam is not yet available in FlexNow ([script](https://github.com/digital-work-lab/handbook/tree/main/src/scheine){target=_blank})).
- [ ] Professor: Archive grades presentation protocols (projects and seminars: digital is sufficient) at [14.03](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/10-lab/14_grades/03_seminars&fileid=72){target=_blank}.

Documentation

- [ ] Professor: Analyse the evaluations, store the files, and document the improvements (see [evaluations](/teaching/evaluations.html)).
- [ ] Professor: [Report](/management/reports.html) teaching efforts at the end of the semester.

Deadline: End of August (summer term), March (winter term)

```


:::

::: {.callout-note title="Project template" collapse=true}

```markdown
---
layout: default
title: OSP
title_long: Open-Source Projekt (WI-Projekt)
parent: 32 Courses
grand_parent: Teaching
semester: 20XX-WiSe
status: ⟳
student_evaluations: ""
improvement_issue: ""
improvement_status: N/A
---

# OSP 20XX WiSe

Field               | Value
------------------- | -------------------
Title               | {{ page.title_long }}
Lecturer            | Gerit Wagner
Link: VC            | TODO
Link: Website       | [Website](https://www.uni-bamberg.de/digital-work/studium/bachelor/wi-projekt-open-source-projekt/){target=_blank}
Status              | ⟳ in-preparation
Student Evaluations | {% if page.student_evaluations != "" %} <a href="/assets/evaluations/{{ page.student_evaluations }}" target="_blank">PDF</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Improvement Issue   | {% if page.improvement_issue != "" %} <a href="{{ page.improvement_issue }}" target="_blank">Issue Link</a> {% else %} <span class="label label-yellow">Pending</span> {% endif %}
Status of Revisions | {{ page.improvement_status }}

## Process

- Grading: The Team Assistant registers students for the seminar, enters grades, and submits them online. Students do not need to register on FlexNow.

## 1. Announce the project (4 months before)
 
Start: December (summer term), May (winter term)

- [ ] Team Assistant: Create the project in FlexNow.

{: .highlight }
>  Check public holidays
>
> Flexnow: Besonderheiten bei Ausstattung/Hinweise:
> 
> - 2h in Semesterwoche 1, Tag und Zeit egal
> - 4h in Semesterwoche 2, Freitag, Uhrzeit egal, CIP-Pool
> - 2 x 4h in Semesterwoche 3, Donnerstag und Freitag, Uhrzeit egal, CIP-Pool
> - 2h in Semesterwoche 5, Donnerstag oder Freitag, Uhrzeit egal, CIP-Pool

At the end of the semester: 

- [ ] Team Assistant: Update information in UnivIS (**add keywords „WI-Projekt“ and „WI-Projekte“**), check information on the website. VC/UnivIS: "WI-Projekt-B: Bachelorprojekt aus der Fächergruppe Wirtschaftsinformatik"
- [ ] Team Assistant: Announce the project on the website for the next semester (without dates/rooms).

Deadline: mid-May (summer term), December/January (winter term)

## 2. Prepare the project (1 month before)

Start: March (summer term), September (winter term)

- [ ] Team Assistant and Professor: Set dates and request lecture rooms.
- [ ] IT department: Create the VC course, two weeks before the semester starts (automatically based on UnivIS).
- [ ] Professor: The project should be announced on [Instagram](https://www.instagram.com/informatik_unibamberg/){target=_blank} and in the [Fachschaft WIAI newsletter](https://vc.uni-bamberg.de/course/view.php?id=284){target=_blank}  (see [dissemination](/research/dissemination.html))
- [ ] Professor: Create a reminder for the evaluations.
- [ ] Team Assistant: Add moderator and session dates in VC.
- [ ] Professor: Summarize the feedback from the last course and explain how it was addressed.
- [ ] Professor: Activate course in VC (visible to students).

Deadline: April (summer term), October (winter term)

## 3. Offer the project

Start: April (summer term), October (winter term)

- [ ] Team Assistant: Add the presentation (exam) dates to the department calendar
- [ ] Professor: Set deadline for pull-request evaluation.
- [ ] Professor: Set the date for the code review session.
- [ ] Professor: Add the code review session to the [calendar](../../calendar/events.yaml)
- [ ] Professor: Schedule evaluations in the pen-ultimate week ([30.21.evaluations](/teaching/evaluations.html)).
- [ ] Scheine ([Formular](https://www.uni-bamberg.de/ism/studium/anmeldung-scheinklausur/){target=_blank}), Scheinklausur-anmeldungen bei Erstellung der Klausurbögen berücksichtigen

## 4. Grading and documentation

Grading

- [ ] Create a reminder for the deadline.
- [ ] Use the [grading scripts](https://github.com/digital-work-lab/handbook/tree/main/src/grading){target=_blank} to assign grades and prepare FlexNow import

Entering Grades into FlexNow

- [ ] Team Assistant: [Enter grades in FlexNow](/teaching/flexnow.html#entering-grades) (or create certificates if exam is not yet available in FlexNow ([script](https://github.com/digital-work-lab/handbook/tree/main/src/scheine){target=_blank})).
- [ ] Professor: Archive grades and presentation protocols (projects and seminars: digital is sufficient) at [14.02](https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/10-lab/14_grades/02_projects&fileid=69){target=_blank}.

Documentation

- [ ] Professor: Analyse the evaluations, store the files, and document the improvements (see [evaluations](/teaching/evaluations.html)).
- [ ] Professor: [Report](/management/reports.html) teaching efforts at the end of the semester.

Deadline: End of August (summer term), March (winter term)
```
:::

- Update yaml-header information.
- The [overview](lectures.html), [evaluation](/teaching/evaluations.html) and [improvements](/teaching/improvements.html) are updated automatically.
- Update github pages, e.g., dates on the [project page](https://digital-work-lab.github.io/open-source-project/){target=_blank}.

## New module

New modules must be created in FlexNow (see [process overview](https://www.uni-bamberg.de/qm/prozesse-studium-und-lehre/prozessportal/){target=_blank}).

A description for creating and editing modules in FlexNow is available in the [VC course "FlexNow für Lehrstühle"](https://vc.uni-bamberg.de/course/view.php?id=268){target=_blank}.

Once the new module is created, teaching sessions must be created for each semester.

## Applicable regulations

- [Ordnung zur Sicherung der Qualität in Lehre und Studium](https://www.uni-bamberg.de/fileadmin/www.abt-studium/Rechtsvorschriften/1Organisation/Evaluation%20Lehre%20Studium/O-Sicherung-Qualitaet-Lehre-Studium-1.pdf){target=_blank}
- [Prüfungstermine](https://www.uni-bamberg.de/pruefungsamt/pruefungstermine/){target=_blank} (Klausurtermine, examination dates)
