---
title: "Academic programs"
transition_status: "toupdate"
transition_comment: "update Platforms & University of Bamberg"
---

::: callout-note
This section is marked as "toupdate": Create an overview of modules x study programs (WI/AI/I/...)
:::

## Platforms

- [Classcentral](https://www.classcentral.com/){target=_blank}
- [Coursera](https://www.coursera.org/){target=_blank}
- [Open Textbooks](https://oercommons.org/hubs/open-textbooks){target=_blank}
- [EdX](https://www.edx.org/){target=_blank}
- [MERLOT platform](https://merlot.org/merlot/index.htm){target=_blank}

## Frankfurt School of Finance & Management

### Bachelor of Science (BSc)

- [Bachelor in Business Administration (BSc)](https://www.frankfurt-school.de/en/study/bachelor/bachelor-science/bachelor-in-business-administration){target=_blank}
- [Bachelor in Computational Business Analytics (BSc)](https://www.frankfurt-school.de/en/study/bachelor/bachelor-science/bachelor-computational-business-analytics){target=_blank}
<!-- - [Bachelor in Management, Philosophy & Economics (BSc)](https://www.frankfurt-school.de/en/study/bachelor/bachelor-science/bachelor-in-management-philosophy-economics){target=_blank} -->

### Bachelor of Arts (BA)

- [Bachelor of Arts (part-time)](https://www.frankfurt-school.de/en/study/bachelor/bachelor-arts){target=_blank}
<!-- - [Bachelor in Betriebswirtschaftslehre (BA) (part-time)](https://www.frankfurt-school.de/en/study/bachelor/bachelor-arts/bachelor-betriebswirtschaftslehre){target=_blank} -->

### Master (pre-experience)

- [Master in Management (MiM)](https://www.frankfurt-school.de/en/study/master/master-in-management){target=_blank}
- [Master of Artificial Intelligence & Data Science (MSc)](https://www.frankfurt-school.de/en/study/master/master-of-artificial-intelligence-and-data-science){target=_blank}
<!--
- [Master of Finance (MSc)](https://www.frankfurt-school.de/en/study/master/master-of-finance){target=_blank}
- [Master in Financial Technology (MSc)](https://www.frankfurt-school.de/en/study/master/master-in-financial-technology){target=_blank}
- [Master in Real Estate (MSc)](https://www.frankfurt-school.de/en/study/master/master-in-real-estate){target=_blank}
-->

<!--
## University of Bamberg

Bachelor of Science

- [Angewandte Informatik](https://www.uni-bamberg.de/ba-ai/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-bachelor-angewandte-informatik/){target=_blank}
- [Informatik: Software Systems Science](https://www.uni-bamberg.de/sosysc/){target=_blank} (no new registration possible)
- [Künstliche Intelligenz & Data Science](https://www.uni-bamberg.de/ba-ki/){target=_blank} [(modules)](https://www.uni-bamberg.de/ba-ki/dokumente/){target=_blank}
- [International Information Systems Management](https://www.uni-bamberg.de/ba-iism/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-bachelor-international-information-systems-management/){target=_blank}
- [Wirtschaftsinformatik](https://www.uni-bamberg.de/ba-wi/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-bachelor-wirtschaftsinformatik/){target=_blank}

Master of Science

- [Angewandte Informatik](https://www.uni-bamberg.de/ma-ai/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-master-angewandte-informatik/){target=_blank}
- [Computing in the Humanities](https://www.uni-bamberg.de/ma-cith/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuch-master-computing-in-the-humanities/){target=_blank}
- [Interaction Research & Design](https://www.uni-bamberg.de/ma-ird/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuch-interaction-research-design/){target=_blank}
- [International Software Systems Science](https://www.uni-bamberg.de/ma-isosysc/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuch-master-international-software-systems-science/){target=_blank}
- [International Information Systems Management](https://www.uni-bamberg.de/ma-iism/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-master-international-information-systems-management/){target=_blank}
- [Wirtschaftsinformatik](https://www.uni-bamberg.de/ma-wi/auf-einen-blick/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuecher-master-wirtschaftsinformatik/){target=_blank}
- [Virtueller Weiterbildungsstudiengang Wirtschaftsinformatik](https://www.uni-bamberg.de/ma-vawi/auf-einen-blick/){target=_blank} [(modules)](https://www.uni-bamberg.de/abt-studium/aufgaben/modulhandbuecher/wiai/modulhandbuch-master-vawi/){target=_blank}
-->

## Other Universities in Germany

- [Wirtschaftsinformatik Universität Leipzig](https://www.uni-leipzig.de/studium/vor-dem-studium/studienangebot/studiengang/course/show/wirtschaftsinformatik-b-sc){target=_blank}
- [Wirtschaftsinformatik WWU Münster](https://www.wi.uni-muenster.de/de/studieninteressierte/unsere-studiengaenge/bachelor){target=_blank}
- [Wirtschaftsinformatik Universität Rostock](https://www.informatik.uni-rostock.de/studium-lehre/bachelor-studiengaenge/wirtschaftsinformatik-bsc-1/){target=_blank}
- [Wirtschaftsinformatik Universität Augsburg](https://www.uni-augsburg.de/de/studium/studienangebot/uebersicht/wirtschaftsinformatik-bsc/){target=_blank}
- [Wirtschaftsinformatik FAU](https://meinstudium.fau.de/studienangebot/wirtschaftsinformatik-bsc/){target=_blank}
- [Wirtschaftsinformatik Universität Hildesheim](https://www.uni-hildesheim.de/studium/studienangebot/bachelorstudium/wirtschaftsinformatik-bachelor-of-science-bsc/){target=_blank}
- [Wirtschaftsinformatik Universität Osnabrück](https://www.uni-osnabrueck.de/studieninteressierte/studiengaenge-a-z/wirtschaftsinformatik-bachelor-of-science/){target=_blank}
- [Wirtschaftsinformatik Universität Paderborn](https://www.uni-paderborn.de/studienangebot/studiengang/wirtschaftsinformatik-bachelor){target=_blank}
- [Wirtschaftsinformatik Universität Würzburg](https://www.uni-wuerzburg.de/studium/angebot/faecher/wirtschaftsinformatik/){target=_blank}
- [Wirtschaftsinformatik TU Dresden](https://tu-dresden.de/bu/wirtschaft/studium/studienangebot/diplom-wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität Göttingen](https://www.uni-goettingen.de/de/640687.html){target=_blank}
- [Wirtschaftsinformatik Universität Mannheim](https://www.uni-mannheim.de/studium/studienangebot/bachelor-wirtschaftsinformatik/){target=_blank}
- [Wirtschaftsinformatik TUM](https://www.tum.de/studium/studienangebot/detail/wirtschaftsinformatik-bachelor-of-science-bsc){target=_blank}
- [Wirtschaftsinformatik TU Darmstadt](https://www.tu-darmstadt.de/studieren/studieninteressierte/studienangebot_studiengaenge/studiengang_177856.de.jsp){target=_blank}
- [Wirtschaftsinformatik FernUniversität Hagen](https://www.fernuni-hagen.de/studium/studienangebot/bachelor-wirtschaftsinformatik.shtml){target=_blank}
- [Wirtschaftsinformatik TU Ilmenau](https://www.tu-ilmenau.de/studium/vor-dem-studium/studienangebot/bachelorstudiengaenge/wirtschaftsinformatik-b-sc){target=_blank}
- [Wirtschaftsinformatik KIT](https://www.wirtschaftsinformatik.kit.edu/bachelor.php){target=_blank}
- [Wirtschaftsinformatik Universität Magdeburg](https://www.ovgu.de/informatikstudieren.html?gclid=EAIaIQobChMIuNu7_LX0_wIVj-Z3Ch2pSQQkEAAYASAAEgKX8PD_BwE){target=_blank}
- [Wirtschaftsinformatik Universität Passau](https://www.uni-passau.de/bachelor-wirtschaftsinformatik/){target=_blank}
- [Wirtschaftsinformatik Universität Regensburg](https://www.uni-regensburg.de/studium/studienangebot/studiengaenge-a-z/wirtschaftsinformatik-bsc/index.html){target=_blank}
- [Wirtschaftsinformatik Universität Hamburg](https://www.inf.uni-hamburg.de/studies/bachelor/wiinf.html){target=_blank}
- [Wirtschaftsinformatik Universität Kiel](https://www.studium.uni-kiel.de/de/studienangebot/studienfaecher/wirtschaftsinformatik-ba){target=_blank}
- [Wirtschaftsinformatik Universität Siegen](https://www.uni-siegen.de/en/study/bachelor/business-information-systems){target=_blank}
- [Wirtschaftsinformatik Universität Bremen](https://www.uni-bremen.de/studium/orientieren-bewerben/studienangebot/dbs/study/33){target=_blank}
- [Wirtschaftsinformatik Universität Chemnitz](https://www.tu-chemnitz.de/wirtschaftsinformatik/){target=_blank}
- [Wirtschaftsinformatik Universität Jena](https://www.uni-jena.de/msc-wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität zu Köln](https://wiso.uni-koeln.de/de/studium/bachelor/bachelor-wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität Potsdam](https://www.uni-potsdam.de/de/studium/studienangebot/bachelor/ein-fach-bachelor/wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik TU Braunschweig](https://www.tu-braunschweig.de/wirtschaftsinformatik-bachelor){target=_blank}
- [Wirtschaftsinformatik Universität Duisburg-Essen](https://www.uni-due.de/studienangebote/studiengang.php?id=110){target=_blank}
- [Wirtschaftsinformatik Universität des Saarlandes](https://www.uni-saarland.de/studium/angebot/bachelor/wirtschaftsinformatik.html){target=_blank}
- [Wirtschaftsinformatik Universität Bayreuth](https://www.wi.uni-bayreuth.de/de/index.html){target=_blank}
- [Wirtschaftsinformatik TU Clausthal](https://www.tu-clausthal.de/studieninteressierte/studiengaenge/master-studiengaenge/wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität Hohenheim](https://www.uni-hohenheim.de/wirtschaftsinformatik-bachelor-studium){target=_blank}
- [Wirtschaftsinformatik Universität Marburg](https://www.uni-marburg.de/de/studium/studienangebot/bachelor/wirtinfobsc){target=_blank}
- [Wirtschaftsinformatik Universität Stuttgart](https://www.uni-stuttgart.de/studium/bachelor/wirtschaftsinformatik-b.sc./){target=_blank}
- [Wirtschaftsinformatik Universität Halle-Wittenberg](https://studienangebot.uni-halle.de/wirtschaftsinformatik-business-information-systems-bachelor-180){target=_blank}
- [Wirtschaftsinformatik Universität Koblenz](https://www.uni-koblenz.de/de/studium/studienangebot/wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität Lüneburg](https://www.leuphana.de/college/bachelor/wirtschaftsinformatik-studium.html){target=_blank}
- [Wirtschaftsinformatik Universität Oldenburg](https://uol.de/informatik/bsc/wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität der Bundeswehr München](https://www.unibw.de/inf/studium/studiengaenge-wirtschaftsinformatik/studiengang-bachelor-wirtschaftsinformatik){target=_blank}
- [Wirtschaftsinformatik Universität Trier](https://www.uni-trier.de/studium/studienangebot/studienfaecher/wirtschaftsinformatik){target=_blank}
