---
title: "Quarto"
---

::: {.callout-important}
Do not create quarto brand extension or use the revealjs seminar plugin (complexity).
:::

## TODO

- Layout: template, font, logo (see /home/gerit/ownCloud/inbox/quarto/presentation-example-big_data_analytics)
- Interaction (seminar plugin + feedback flow)
- Ask students how they learn (PDF, ...) whether they use a knowledge management system (which one), ...
- always build output in `_site` dir

## Principles

- Design contents in such a way that students can learn them (after the session, pdf, making comments)
- Add dynamic illustrations only as an extra (link them in the offline version)

## Layout

typography defaults:

```css
  --font-family: "Source Sans Pro", sans-serif;
```

Adding headings to the navigation

```qmd
## Heading {data-menu-title="I. Overview"}

### Will not be in the navigation

```

## PDF output for students based on an `all-slides.qmd` (with `make pdf`)

```qmd
---
title: "BDA Analytics (LECTURE)"
format: revealjs
---

# BDA Analytics  (LECTURE)

Hand-made toc

\newpage

## Lecture 1

\{\{< include lecture_1.qmd >\}\}

\newpage

## Lecture 2

\{\{< include lecture_2.qmd >\}\}

```

## Adding extensions

```bash
docker compose run --rm quarto quarto add gadenbuie/countdown/quarto
docker compose run --rm quarto quarto add martinomagnifico/quarto-simplemenu
```


## Publishing to github pages

For `quarto publish gh-pages` : install quarto locally (otherwise, the ssh and git setup in the docker container requires detailed configuration).

See [tutorial](https://www.jtrive.com/posts/creating-gh-pages-blog-with-quarto/creating-gh-pages-blog-with-quarto.html)

## Creating extensions

https://github.com/mcanouil/awesome-quarto

https://m.canouil.dev/quarto-extensions/

quarto list extensions

https://quarto.org/docs/extensions/creating.html


<!--
https://posit-dev.github.io/brand-yml/
See branded shiny app for creating brand extensions: https://posit-dev.github.io/brand-yml/articles/llm-brand-yml-prompt/
embedd extension:
quarto add fs-ise/fs-ise-brand --embed fs-ise-presentation
Brand: https://github.com/mcanouil/quarto-mcanouil
Example of a brand extension used: https://github.com/mcanouil/mickael.canouil.fr
-->

Shortcuts:
- g : goto slide
- b
- d


### Timer

quarto add gadenbuie/countdown/quarto

```text
{{< countdown minutes=5 seconds=32 top=10 left=0 >}}
```


Code annotation (for slides!) (see [link](https://quarto.org/docs/authoring/code-annotation.html))


```r
library(tidyverse)
library(palmerpenguins)
penguins |>                                      # <1>
  mutate(                                        # <2>
    bill_ratio = bill_depth_mm / bill_length_mm, # <2>
    bill_area  = bill_depth_mm * bill_length_mm  # <2>
  )                                              # <2>
```

1. Take `penguins`, and then,
2. add new columns for the bill ratio and bill area.


Your content here… [^1]


```{mermaid}
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

Icons: [Bootstrap](https://icons.getbootstrap.com/)

\{\{icon="mortarboard-fill"\}\}

Native page break:

\{\{< pagebreak >\}\}

:::{.callout-note}
Note that there are five types of callouts, including: 
`note`, `tip`, `warning`, `caution`, and `important`.
:::

[^1]: A url and further information.

@CastonguayWagnerMotulskyEtAl2023 is useful.


Handbook: navigation is updated in `_quarto.yml`.


Convert PowerPoint to quarto:

```
pptx2md "slides.pptx" --output "slides_with_notes.qmd" --enable-slides --qmd --image-dir "images"
```