---
title: "Teaching reports (LUFV)"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": completely update
:::

## Purpose and applicable regulations

Report teaching activities **after each semester** in line with [Lehrverpflichtungsverordnung (LUFV)](http://gesetze-bayern.de/Content/Document/BayLUFV){target=_blank} and "Erhebungsbogen" (in e-mail)

<a href="https://www.uni-bamberg.de/fileadmin/abt-personal/Homepage_ab_2016-03/11_Formulare_Infos_Merkblaetter/Lehrverpflichtung/Erkl%C3%A4rung_zur_Erf%C3%BCllung_der_Lehrverpflichtung.pdf">LUFV Formular</a>

→ "Erhebungsbogen" is completed only once per chair.

## Responsibility

- Professor

## Process

- Notification is sent out by the Dean's office (mid-July / mid-January)
- The form is available online ([Erklärung zur Erfüllung der Lehrverpflichtung](https://www.uni-bamberg.de/abt-personal/formulare-infos-und-merkblaetter/){target=_blank} / Lehrdeputat)
- Required to teach 7 SWS (in the first three years: 5 SWS).
- When reporting more (or less), a reason must be provided (e.g., "Sicherstellung des Lehrangebots").

Theses

- Check for [theses completed this semester](https://github.com/fs-ise/theses-confidential){target=_blank}.
- Check [prior reports]({{< meta nextcloud.archive >}}){target=_blank} to **avoid reporting the same thesis twice**.
- Theses can be reported in the semester of admission or grading.
- If the LUFV deadline has already passed, a thesis can also be reported in the following semester.
- Theses that have required considerable effort for supervision but were not completed may also be reported.
- SWS: 0.15 for Bachelor's theses, and 0.45 for Master's theses (Bachelorarbeit / Diplom- bzw. Masterarbeit in Ingenieurswissenschaften).
- A maximum of 2 SWS for theses can be reported per semester.

Projects

- Declared as a "Seminar" (factor: 1) - without splitting groups
- Note: new categories will become available soon, including "projects".

Submission

- Print, sign, and add a copy to the [archive]({{< meta nextcloud.archive >}}){target=_blank}.
- Add to the list of prior reports below.
- Submit to the Dean's office (report due: mid-September / mid-March)

## Prior reports

| Semester      | Report / Status  |
|---------------|------------------|
| SuSe 2025     | 000136           |
| WiSe 2024/25  | 000116           |
| SuSe 2024     | 000089           |
| WiSe 2022/23  | 000031           |
| SuSe 2023     | 000035           |
| WiSe 2023/24  | 000067           |
