---
title: "Reviews"
transition_status: "toupdate"
transition_comment: "update"
---

::: callout-note
This section is marked as "toupdate": update completely
:::

This is the process for students to appeal against their grades for centrally organized exams and other exams (e.g. thesis, projects and seminars)

## Centrally organized exams (Nachkorrektur)

### Procedure - Students

- For exams that are organized centrally, students can attend the "Reviewing Examination Results Date" (Einsichtnahme), which can be found on this [website](https://www.uni-bamberg.de/en/examinations-office/translate-to-1-english-einsichtnahmen/){target=_blank}. 
- During these reviewing days, students are encouraged to take notes and photographs of the exam. If students notice any discrepancies, they can write down their observations on a separate piece of paper and take pictures. 
- After the reviewing days, students can send an email to the responsible chair and request a correction, but only if they can specifically identify the questions and provide a picture of the exam task that requires correction.
- Afterwards, the chair determines whether a post-correction is necessary based on the description and picture, and informs the student via email.

### Procedure - Chair

- When the chair receives a student’s correction request, the respective exam has to be requested at the examination office (E-Mail to: registratur.pruefungen@uni-bamberg.de, including student’s name and matriculation number). 
- After arrival at the chair, the exam will then be post-corrected by the professor/lecturer. When points or grade change, incorrect points or grade are to be crossed out, correct points and grade stated, together with date, stamp and signature (on the exam cover/Prüfungsumschlag).
- When a grade changes, **scan the first page of the exam (indicating the new grade) and save it on Nextcloud**
- The exam is then sent back to the examination office, which carries our a possible change of grades in FlexNow.

## Other exams

For projects, seminars, and theses, feedback and comments are part of the process. You can ask to review the grading of your work and discuss potential corrections.
