---
title: "Statement"
transition_status: "toupdate"
transition_comment: "update Resources"
---

## Teaching goals

<!-- 
<div style="text-align: center;">
<h2>"Preparing for a digital world of work"</h2>
</div>
-->

Our goal is to prepare students to actively shape and critically engage with the digital transformation of work.
We aim to empower them to become capable managers, designers, and researchers of information systems
 — with a particular focus on digital work environments, platform ecosystems, and knowledge-intensive contexts. 
To this end, we pursue two core objectives:

1. **Enable students to understand, design, and responsibly shape digital work in socio-technical systems**, 
  equipping them with transferable methods and competencies for interdisciplinary collaboration in evolving digital environments.
2. **Foster critical thinking, ethical judgment, and reflective engagement**, 
  empowering students to assess and influence the societal, organizational, and individual implications of digital technologies.

<!-- 
Our focus is on **equipping students with skills, methods, and tools necessary for the digital world of work**.
We prioritize skills that are relevant and transferrable across a variety of professional settings, particularly those involving digital work practices, organizing distributed teams, and synthesizing knowledge.
We place a strong emphasis on complex skill development and fostering a mindset of continuous learning.
The content we cover goes beyond what is typically found in information systems textbooks,
integrating topics from the fields of organizational psychology and behavior, insights from practitioners, open-source software engineering, and moral philosophy
to provide a holistic understanding of modern work environments.

We aim to make a **real-world impact** with our students' work. Our teaching approach is centered around giving students the opportunity to create and publish products, papers, or other outcomes that have tangible relevance.
We empower students to contribute to real-world, publicly accessible projects, such as Python packages.
This hands-on experience not only enhances their technical skills but also instills a sense of accomplishment and relevance.
These projects provide students with concrete examples of their work that they can showcase on their CVs, demonstrating their practical contributions and teamwork skills to potential employers.
-->

To achieve these goals, we rely on a pedagogical approach that emphasizes active engagement, transparency, inclusivity, and continuous reflection
— both in how we teach and how students learn.

## Pedagogical approach

Our pedagogical approach consists of four pillars: Active engagement, transparent assessment, DEI, and continuous reflection.
These apply universally to all teaching formats.

**Active engagement** is integral to our teaching efforts.
Our passion for the subject matter plays a pivotal role in motivating students to get involved in the topic, challenge themselves, and grow.
To foster this engagement, we employ a variety of teaching formats that encourage exploration, collaboration, and competition.
We focus on guiding students through the learning process by asking insightful questions and offering support, all while preserving the inherent complexity of the material.
This ensures that students develop resilience and sharpen their problem-solving abilities.
In addition, we "dogfood" the  work practices, tools, and theory covered in our sessions
by implementing strategies such as Getting-Things-Done, organizing our work through a public handbook, and using cutting-edge knowledge management systems.
Additionally, we integrate our research into our teaching, bringing real-world examples to the classroom and enriching the learning experience.
<!-- see humanist teaching philosophies, https://www.indeed.com/career-advice/career-development/teaching-philosophies -->

**Transparent assessment** is the guiding principle for our teaching activities, and we strive to ensure that assessment is transparent, fair, and objective.
We establish clear criteria and objectives at the outset of each course and session, which are made accessible through detailed documentation in our slides and learning materials.
These criteria are directly tied to verifiable skills and learning outcomes, enabling students to understand exactly what is expected of them.
To ensure objectivity, we implement consistent grading processes that evaluate students' work based on these pre-defined criteria.
Additionally, we recognize that some students may face disadvantages, whether due to personal circumstances or learning differences,
 and we offer tailored support to ensure everyone has an equal opportunity to succeed.
This includes providing additional guidance, offering flexible deadlines when appropriate, and making accommodations for those with specific needs.
Through these efforts, we aim to create a fair and supportive evaluation process that empowers all students to reach their full potential.

**Diversity, equity, and inclusion** are central to our learning environments. 
We believe that diversity in backgrounds, perspectives, and experiences is a strength in itself that also drives creativity, critical thinking, and innovation.
Our teaching is grounded in the conviction that inclusive learning environments not only remove barriers but actively benefit from the plurality of voices and lived experiences our students bring.
We strive to create spaces where all students feel valued, heard, and empowered to contribute — regardless of their identities, abilities, or prior experiences.
Our goal is to create a space where students are not afraid to experiment and explore new ideas, contributing to a more dynamic and diverse educational experience that mirrors the inclusive and collaborative environments they will encounter in their future careers.

**Continuous reflection** is at the core of our teaching approach.
We adopt an iterative process where feedback from students and peer-reviewed teaching materials drive the evolution of our course content.
By regularly revising the material, we ensure that it is up-to-date with recent [evidence-based practices](pedagogy.html#evidence-based-practice), peer-reviewed academic materials, and the latest industry trends.
We constantly challenge ourselves to teach new topics, such as the new lecture [Introduction to Digital Work](https://fs-ise.github.io/digital-work-lecture/){target=_blank}, 
and to teach existing topics more effectively, for instance through our [pedagogical recommendations for teaching Git](https://fs-ise.github.io/rethink-git-teaching/){target=_blank}.
In addition, we develop teaching materials in openly accessible repositories and under open content licenses.
Each repository, along with learning resources, such as slides and notebooks, provides students the opportunity to suggest changes and offer feedback through the open-source workflows of GitHub.
This collaborative approach fosters an open and fully digital learning environment where students can actively contribute and adapt the course contents.

## Focal areas

Our teaching focuses on key areas that reflect the transformation of work in the digital age.
These focal points equip students to understand and shape emerging forms of organizing, collaboration, and innovation in digital environments.

<!-- 
The focal areas correspond to specific formats, such as lectures, projects, or seminars.
Each area builds on its own philosophy.
While lectures may build essentialist or perennialist ideals, progressivist philosophies resonate with project settings, and constructivist views align with seminars. -->

The **digital transformation of work** is a key area that focuses on understanding how technological advancements reshape the nature of work.
It covers both the historical context of digitalization and the practical skills needed to thrive in today’s digital workplaces.
This area emphasizes the tools and strategies necessary for organizing digital work, including the ability to select and adapt tools for specific situations.
As work environments continue to evolve, driven by trends such as remote work, digital nomadism, and the rise of crowd-sourced platforms, students are introduced to state-of-the-art digital work practices.
They also acquire technical skills, such as proficiency in Git, which are critical for managing distributed development and version control in collaborative settings.
Beyond technical competencies, this area fosters the development of collaboration skills, with students participating in individual, team-based, and crowd-sourced projects to simulate real-world work scenarios.
By engaging in these activities, students gain a deeper understanding of how digital tools enable flexible, personalized work environments while also exploring the ethical and societal implications of these shifts.
The most prominent example of this focal area is the lecture [Introduction to Digital Work](https://fs-ise.github.io/digital-work-lecture/){target=_blank},
where these concepts are explored in-depth and applied through hands-on learning and practical projects.

Principles of **open-source development** serve as a prime example of fully digital work and are central to this area of study.
<!-- , as noted by Baiyere, Schneider and Klein (2023), -->
These principles epitomize the collaborative, transparent, and community-driven nature of software development and work in the digital era.
In the [Open-Source Project](https://fs-ise.github.io/open-source-project/){target=_blank},
we teach students the fundamentals of distributed software development using Git,
providing them with the tools necessary to manage and organize projects in a decentralized manner.
Students engage in practical exercises focused on project organization, collaborative development, and maintaining code quality.
These exercises ensure that students not only learn the technical aspects but also experience the real-world challenges and advantages of working in distributed development environments.
Each student or group contributes to a public-facing Python package.
Regular project updates, hacking sessions, and code reviews are integral to this area, providing iterative feedback and opportunities for continuous improvement.
Through these hands-on experiences, students gain a comprehensive understanding of open-source development and the skills needed to work on collaborative, distributed software projects.

The **knowledge synthesis area** focuses on equipping students with the skills to synthesize academic and non-academic knowledge and conduct rigorous literature reviews.
Central to this is the [Literature Review Seminar](https://fs-ise.github.io/literature-review-seminar/){target=_blank},
which covers the different types and goals of reviews, the review process, the qualities of review papers, and tools supporting the conduct of literature reviews.
We encourage students to apply these review methods specifically to research on digital work, enabling them to explore and critically analyze current trends in digital transformation and its broader impact on workplaces.
Through this process, students not only gain a deep understanding of knowledge synthesis but also develop the ability to identify and address key research gaps and contribute to the academic discourse.

Across the focal areas, we aim to foster a curiosity for academic and applied research, which is often reflected in students’ interest in pursuing thesis topics and engaging with our research projects.

## Advising and mentoring

Our approach to [thesis](https://fs-ise.github.io/theses/){target=_blank} advising and mentoring focuses on providing individual guidance while fostering independence and critical thinking.
We support students in choosing innovative research topics that have real-world relevance and align with academic standards, offering regular feedback to help them stay on track.
We encourage students to contribute to ongoing research projects, co-author papers, and engage with the academic community.
By doing so, we create a dynamic learning environment where students not only complete their theses but also gain valuable experience.
Our goal is to empower students to produce work that makes a tangible impact.

::: {.callout-note title="Guidelines for instructors"}
- Create a non-judgmental learning atmosphere in which students are encouraged to make mistakes and ask questions.
- Use inclusive language and non-stereotypical role models/examples.
- Stay up-to-date with teaching resources, such as academic teaching tips or massive open online courses (MOOC), and skills that are important to students.
- Select illustrative cases that are exciting and actively look for case studies and examples.
- Explain our aspiration to design and co-create with students and provide corresponding opportunities (e.g., handbook materials, design of artifacts, or academic publications).
- Ask students what they would like to learn more about.
- Discuss with students how we can improve our lectures and share ideas for the upcoming semesters.
:::

## Resources

- [List of current courses](/teaching/course_overview.html)
- [Continuous improvement overview](/teaching/improvements.html)
- Hall-of-fame: Student accomplishments in [Theses](https://fs-ise.github.io/theses/docs/hall_of_fame.html){target=_blank} and [Projects](https://fs-ise.github.io/open-source-project/docs/hall_of_fame.html){target=_blank}
- [Leitbild Lehre, Universität Bamberg](https://www.uni-bamberg.de/lehre/verstaendnis-von-lehre/leitbild/){target=_blank} and [implementation process](https://www.uni-bamberg.de/lehre/verstaendnis-von-lehre/leitbild/implementierungsprozess/){target=_blank}
- [Rahmenempfehlungen für WI-Studiengänge](https://wirtschaftsinformatik.de/termine-startseite/rahmenempfehlung-studiengang-2024){target=_blank}

<!--
- [Academic integrity](https://uwaterloo.ca/library/research-supports/academic-integrity/undergraduate-academic-integrity-module){target=_blank} and [interactive module](https://contensis.uwaterloo.ca/sites/open/courses/UG-AIM/table-of-contents.aspx){target=_blank}
- [What is a teaching philosophy?](https://pce.sandiego.edu/teaching-philosophy-examples/){target=_blank}
- [Writing a Teaching Philosophy Statement](https://teaching.uwo.ca/awardsdossiers/teachingphilosophy.html){target=_blank}
- [Types of teaching philosophies](https://www.indeed.com/career-advice/career-development/teaching-philosophies){target=_blank}

Es geht hierbei nicht nur darum, Lerninhalte passiv zu erlernen, sondern vielmehr darum, diese auch kritisch zu hinterfragen und sich mit Kommilitonen auszutauschen. Das Lehrkonzept der Juniorprofessur greift dabei auf, dass ein analytisches, kritisches und vorrausschauendes Agieren und Denken, Studierenden dabei helfen kann, im späteren Unternehmensumfeld effektiver handeln zu können. Die Lehrveranstaltungen der Juniorprofessur sind daher so gestaltet, dass Studierende aktiv eingebunden werden und durch Übungen, Gruppenarbeiten und der Lösung von Problemfällen dazu befähigt werden, sich komplexen Diskussionen zu stellen.
-->
