---
title: "Systems for teaching"
transition_status: "toupdate"
transition_comment: "update all systems"
---

::: callout-note
This section is marked as "toupdate": update all systems
:::

| System | Description |
---|---|
[Virtual Campus](https://vc.uni-bamberg.de/moodle/mod/page/view.php?id=225164){target=_blank}<br>(Powered by [moodle](https://docs.moodle.org/39/de/Hauptseite){target=_blank})| - Central hub for teaching for students as well as teachers<br>- User-friendly interface<br>- Allows teachers to structure course materials and courses as well as participants<br>- Secure environment via password or granted access options<br>- Publishing of various content types such as [presentations](#presentation), [scripts](#writing-tools), [videos](#panopto), and quizzes<br>- [Communication](#communication-tools) and collaboration through forums<br>- Online assessments, grading and feedback of exercises<br>- Activate password-based self-registration<br>- [FAQ](https://vc.uni-bamberg.de/mod/glossary/view.php?id=1664511){target=_blank}|
[FlexNow](https://www.uni-bamberg.de/pruefungsamt/FlexNow/){target=_blank}| - Planning courses and examinations is important for students as well as teachers<br>- [Documentation](../../../assets/docs/2023-04-28-Bamberg-FlexNow_ FN2LM.pdf)<br>- Creating and editing courses and exams<br>- Enrolling and withdrawing participants from courses and exams<br>- Entering grades for exam participants<br>- Creating of module handbooks and modules |
[UnivIS](https://univis.uni-bamberg.de/){target=_blank}| - Customize and printing schedules<br>- Search for [courses](https://univis.uni-bamberg.de/form?dsc=anew/lecture&anonymous=1&dir=guk&ref=room&sem=2023s){target=_blank}<br>- Directory of all and [personnel and facilities](https://univis.uni-bamberg.de/form?dsc=anew/pande&anonymous=1&dir=guk&ref=room&sem=2023s){target=_blank}<br>- Directory of all [facilities, their rooms, and their respective equipment](https://univis.uni-bamberg.de/form?dsc=anew/room:&dir=&anonymous=1&ref=room&sem=2023s){target=_blank}<br>- Event calendar of the university<br>- [VC resources](https://vc.uni-bamberg.de/enrol/index.php?id=266){target=_blank}<br>- Administrator / Support: Guntram Förster. Tel.: 0951/863 1127, Mail: info.UnivIS@uni-bamberg.de |
Opencast | - Record and edit videos<br>- See [how-to/vc](https://vc.uni-bamberg.de/course/view.php?id=68429){target=_blank} |
[Marp](https://marp.app/){target=_blank}| [Markdown/marp](../../10-lab/10_processes/10.07.markdown.md) |
[Turnitin Similarity Checker](https://www.uni-bamberg.de/its/turnitin){target=_blank}| - Used to identify potential plagiarism by automatically checking texts for copied passages<br>- Available as a feature within the [Virtual Campus](#virtual-campus-powered-by-moodle)<br>- Teachers can also utilize the [web portal](https://www.uni-bamberg.de/its/turnitin){target=_blank} of Turnitin<br>- Checking process is performed on servers located within the EU<br>- Internal verification index through sources previously checked from our university in addition to Turnitin's sources|
[OBS](https://obsproject.com/){target=_blank}| - Open-source software for video recording and live streaming<br>- Capture and mix audio and video sources<br>- Customizable transitions and effects<br>- Supports multiple scenes and sources<br>- Advanced settings for audio and video encoding<br>- Available for Windows, macOS, and Linux|
[OpenShot](https://www.openshot.org/){target=_blank}| - Open-source video editing software<br>- User-friendly interface<br>- Trim, slice, and arrange video clips<br>- Add transitions, effects, and animations<br>- Adjust video speed and audio volume<br>- Support for multiple tracks and layers<br>- Cross-platform compatibility (Windows, macOS, and Linux)|
[pypeek](https://github.com/firatkiral/pypeek){target=_blank}| - Record short Gif animations |
[yt-dlp](https://github.com/yt-dlp/yt-dlp){target=_blank}| - Download educational videos from youtube, tictoc, twitter, twitch, etc. |