---
title: "Seeking Out Clear And Unique Information Systems Concepts: A Natural Language Processing Approach"
date: "2020"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
url: "https://aisel.aisnet.org/ecis2020_rp/128"
outlet: "European Conference on Information Systems"
author: "Hassan, Nik Rushdi and Prester, Julian and Wagner, Gerit"
authors:
  - name: "Hassan, Nik Rushdi"
    orcid: "0000-0001-5187-2915"
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
citation_key: "HassanPresterWagner2020"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

The goal of this study is to advance conceptual development and the growth of knowledge in the information systems (IS) field by placing the spotlight on a component of theory that is rarely discussed – the native IS concept. Beginning with the assertion that concepts are not the same as constructs, we build the argument that concepts, which are observable sets of ideas, should take priority over constructs which are unobservable fictions and hypothetical entities. Using natural language processing (NLP) based principles and techniques, we extract a sample of the most important concepts in the IS field from a corpus of 245 highly cited IS review articles and 1,293 citing articles from the Senior Scholars’ Basket of Journals to illustrate the extent to which the field agrees on their usage, their clarity and distinctiveness and how the field can move forward in enhancing its conceptual formation.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/ecis2020_rp/128" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="/data/papers/HassanPresterWagner2020.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Author-copy PDF

<iframe src="/data/papers/HassanPresterWagner2020.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Hassan, N. R., Prester, J., &amp; Wagner, G. (2020). Seeking Out Clear And Unique Information Systems Concepts: A Natural Language Processing Approach. *European Conference on Information Systems* 1--15. https://aisel.aisnet.org/ecis2020_rp/128
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{HassanPresterWagner2020,
  author     = {Hassan, Nik Rushdi and Prester, Julian and Wagner, Gerit},
  booktitle  = {European Conference on Information Systems},
  title      = {Seeking Out Clear And Unique Information Systems Concepts: A Natural Language Processing Approach},
  year       = {2020},
  pages      = {1--15},
  url        = {https://aisel.aisnet.org/ecis2020_rp/128},
  abstract   = {The goal of this study is to advance conceptual development and the growth of knowledge in the information systems (IS) field by placing the spotlight on a component of theory that is rarely discussed – the native IS concept. Beginning with the assertion that concepts are not the same as constructs, we build the argument that concepts, which are observable sets of ideas, should take priority over constructs which are unobservable fictions and hypothetical entities. Using natural language processing (NLP) based principles and techniques, we extract a sample of the most important concepts in the IS field from a corpus of 245 highly cited IS review articles and 1,293 citing articles from the Senior Scholars’ Basket of Journals to illustrate the extent to which the field agrees on their usage, their clarity and distinctiveness and how the field can move forward in enhancing its conceptual formation.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Hassan, Nik Rushdi
AU  - Prester, Julian
AU  - Wagner, Gerit
TI  - Seeking Out Clear And Unique Information Systems Concepts: A Natural Language Processing Approach
T2  - European Conference on Information Systems
PY  - 2020
SP  - 1
EP  - 15
UR  - https://aisel.aisnet.org/ecis2020_rp/128
ER  - 
```
