---
title: "A method for resolving organisation‐enterprise system misfits: An action research study in a pluralistic organisation"
date: "2023"
date-format: "YYYY"
categories: ["digital-health"]
keywords: ["digital-health"]
doi: "10.1111/ISJ.12433"
journal.name: "Information Systems Journal"
outlet: "Information Systems Journal"
author: "Morquin, David and Ologeanu‐Taddei, Roxana and Paré, Guy and Wagner, Gerit"
authors:
  - name: "Morquin, David"
  - name: "Ologeanu‐Taddei, Roxana"
  - name: "Paré, Guy"
  - name: "Wagner, Gerit"
citation_key: "MorquinOlogeanuTaddeiPareEtAl2023"
free_fulltext: false
self_archiving_possible_1y: false
self_archiving_possible_2y: true
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Although off‐the‐shelf enterprise systems (ES) have been widely adopted in organisations, the extant literature repeatedly documents ES failures caused by misfits between organisational processes and the ES. Although some misfits can be identified early in the ES lifecycle, others emerge in the onward and upward phase (i.e., after the implementation) and, hence, must be resolved reactively. Prior research on misfits and resolution strategies has primarily focused on the implementation phase, often assuming that close‐to‐perfect information on the misfit's nature and characteristics is available. However, no study has examined how to effectively complete a shared diagnosis and resolution of misfits when diverging individual user perceptions are taken as the starting point. Such situations may be particularly pronounced in pluralistic organisations, where a variety of interdependent processes and potentially competing perceptions of processes are prevalent. The main objective of this study is to address this gap. To this end, we propose a pragmatic method for the diagnosis and resolution of misfits between organisational processes and enterprise systems, which builds on an actionable conceptualization of misfits. This method builds on theoretical concepts of affordances, affordance actualization, user participation, and change agentry. To demonstrate the feasibility and effectiveness of the proposed method, we conducted an action research study in a university hospital. Our analysis focused on a specific misfit involving the hospital's ES‐supported clinical processes. The findings suggest that the method effectively diagnoses and resolves misfits and optimises the resources required for their resolution through efficient management of user participation. We conclude with a discussion of the theoretical and practical contributions of our work.}, author+an:orcid               = {0000-0002-0757-0685;0000-0002-9797-325X;0000-0001-7425-1994;0000-0003-3926-7717

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.1111/ISJ.12433" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>




```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.1111/ISJ.12433"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.1111/ISJ.12433"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.1111/ISJ.12433">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Morquin, D., Ologeanu‐Taddei, R., Paré, G., &amp; Wagner, G. (2023). A method for resolving organisation‐enterprise system misfits: An action research study in a pluralistic organisation. *Information Systems Journal* 33(5), 995--1028. https://doi.org/10.1111/ISJ.12433
</p>
</div>


## Citation: BibTeX

```bibtex
@article{MorquinOlogeanuTaddeiPareEtAl2023,
  doi        = {10.1111/ISJ.12433},
  author     = {Morquin, David and Ologeanu‐Taddei, Roxana and Paré, Guy and Wagner, Gerit},
  journal    = {Information Systems Journal},
  title      = {A method for resolving organisation‐enterprise system misfits: An action research study in a pluralistic organisation},
  year       = {2023},
  volume     = {33},
  number     = {5},
  pages      = {995--1028},
  abstract   = {Although off‐the‐shelf enterprise systems (ES) have been widely adopted in organisations, the extant literature repeatedly documents ES failures caused by misfits between organisational processes and the ES. Although some misfits can be identified early in the ES lifecycle, others emerge in the onward and upward phase (i.e., after the implementation) and, hence, must be resolved reactively. Prior research on misfits and resolution strategies has primarily focused on the implementation phase, often assuming that close‐to‐perfect information on the misfit's nature and characteristics is available. However, no study has examined how to effectively complete a shared diagnosis and resolution of misfits when diverging individual user perceptions are taken as the starting point. Such situations may be particularly pronounced in pluralistic organisations, where a variety of interdependent processes and potentially competing perceptions of processes are prevalent. The main objective of this study is to address this gap. To this end, we propose a pragmatic method for the diagnosis and resolution of misfits between organisational processes and enterprise systems, which builds on an actionable conceptualization of misfits. This method builds on theoretical concepts of affordances, affordance actualization, user participation, and change agentry. To demonstrate the feasibility and effectiveness of the proposed method, we conducted an action research study in a university hospital. Our analysis focused on a specific misfit involving the hospital's ES‐supported clinical processes. The findings suggest that the method effectively diagnoses and resolves misfits and optimises the resources required for their resolution through efficient management of user participation. We conclude with a discussion of the theoretical and practical contributions of our work.}, author+an:orcid               = {0000-0002-0757-0685;0000-0002-9797-325X;0000-0001-7425-1994;0000-0003-3926-7717},
  fulltext   = {https://onlinelibrary.wiley.com/doi/pdf/10.1111/isj.12433}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Morquin, David
AU  - Ologeanu‐Taddei, Roxana
AU  - Paré, Guy
AU  - Wagner, Gerit
TI  - A method for resolving organisation‐enterprise system misfits: An action research study in a pluralistic organisation
T2  - Information Systems Journal
PY  - 2023
VL  - 33
IS  - 5
SP  - 995
EP  - 1028
DO  - 10.1111/ISJ.12433
ER  - 
```
