---
title: "How to develop and frame impactful review articles: key recommendations"
date: "2024"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
doi: "10.1080/12460125.2023.2197701"
url: "https://www.tandfonline.com/doi/full/10.1080/12460125.2023.2197701"
journal.name: "Journal of Decision Systems"
outlet: "Journal of Decision Systems"
author: "Paré, Guy and Wagner, Gerit and Prester, Julian"
authors:
  - name: "Paré, Guy"
    orcid: "0000-0001-7425-1994"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
citation_key: "PareWagnerPrester2024"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Developing and framing an impactful review article at a top journal can be a daunting challenge, especially for graduate students and junior academics. With rising demands related to review types, methods, and contributions, guidance is sorely needed. In this short commentary, we draw on our experience as authors, reviewers, and editors of reviews, as well as instructors of a doctoral seminar on literature reviews. Our goal is to offer key recommendations on the elements of an impactful review paper and on the crucial role that feedback can play in the process. We believe these suggestions, together with the contributions of the special issue, are a useful resource for prospective authors of influential review papers.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.1080/12460125.2023.2197701" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-primary" href="/data/papers/PareWagnerPrester2023.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-pdf"></i> Open access PDF
  </a>
</div>



## Open access PDF

<iframe src="/data/papers/PareWagnerPrester2023.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.1080/12460125.2023.2197701"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.1080/12460125.2023.2197701"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.1080/12460125.2023.2197701">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Paré, G., Wagner, G., &amp; Prester, J. (2024). How to develop and frame impactful review articles: key recommendations. *Journal of Decision Systems* 33(4), 566--582. https://doi.org/10.1080/12460125.2023.2197701
</p>
</div>


## Citation: BibTeX

```bibtex
@article{PareWagnerPrester2024,
  doi        = {10.1080/12460125.2023.2197701},
  author     = {Paré, Guy and Wagner, Gerit and Prester, Julian},
  journal    = {Journal of Decision Systems},
  title      = {How to develop and frame impactful review articles: key recommendations},
  year       = {2024},
  volume     = {33},
  number     = {4},
  pages      = {566--582},
  url        = {https://www.tandfonline.com/doi/full/10.1080/12460125.2023.2197701},
  abstract   = {Developing and framing an impactful review article at a top journal can be a daunting challenge, especially for graduate students and junior academics. With rising demands related to review types, methods, and contributions, guidance is sorely needed. In this short commentary, we draw on our experience as authors, reviewers, and editors of reviews, as well as instructors of a doctoral seminar on literature reviews. Our goal is to offer key recommendations on the elements of an impactful review paper and on the crucial role that feedback can play in the process. We believe these suggestions, together with the contributions of the special issue, are a useful resource for prospective authors of influential review papers.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Paré, Guy
AU  - Wagner, Gerit
AU  - Prester, Julian
TI  - How to develop and frame impactful review articles: key recommendations
T2  - Journal of Decision Systems
PY  - 2024
VL  - 33
IS  - 4
SP  - 566
EP  - 582
DO  - 10.1080/12460125.2023.2197701
UR  - https://www.tandfonline.com/doi/full/10.1080/12460125.2023.2197701
ER  - 
```
