---
title: "Classifying the Ideational Impact of IS Review Articles - A Natural Language Processing Based Approach"
date: "2018"
date-format: "YYYY"
categories: ["digital-work", "student-paper"]
keywords: ["digital-work", "student-paper"]
url: "https://aisel.aisnet.org/icis2018/research/Presentations/1"
outlet: "International Conference on Information Systems"
author: "Prester, Julian and Wagner, Gerit and Schryen, Guido"
authors:
  - name: "Prester, Julian"
  - name: "Wagner, Gerit"
  - name: "Schryen, Guido"
citation_key: "PresterWagnerSchryen2018"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

By providing knowledge contributions and stimulating future research, review articles (RAs) play a vital role for cumulative knowledge development. Although many papers cite RAs, it is rarely transparent to which degree citation impact represents perfunctory citations as opposed to a deeper engagement with a RA’s knowledge contributions. This distinction between perfunctory and ideational impact has largely been neglected in the literature arguably because of the manual effort required for qualitative analysis. Against this background, our study aims at developing automated classifiers of ideational impact of IS RAs. We propose a machine learning model based on natural language processing to evaluate the feasibility of automated analyses. The evaluation results provide evidence for an effective and scalable classification approach that presents a reliable and reproducible solution to the ideational impact classification problem. We discuss implications for improving the capabilities of understanding how IS scholars build on their field’s body of knowledge.}, author+an:orcid               = {0000-0003-2682-8036;0000-0003-3926-7717;0000-0003-3794-1413

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/icis2018/research/Presentations/1" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="/data/papers/PresterWagnerSchryen2018.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Author-copy PDF

<iframe src="/data/papers/PresterWagnerSchryen2018.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Prester, J., Wagner, G., &amp; Schryen, G. (2018). Classifying the Ideational Impact of IS Review Articles - A Natural Language Processing Based Approach. *International Conference on Information Systems* 1--17. https://aisel.aisnet.org/icis2018/research/Presentations/1
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{PresterWagnerSchryen2018,
  author     = {Prester, Julian and Wagner, Gerit and Schryen, Guido},
  booktitle  = {International Conference on Information Systems},
  title      = {Classifying the Ideational Impact of IS Review Articles - A Natural Language Processing Based Approach},
  year       = {2018},
  pages      = {1--17},
  url        = {https://aisel.aisnet.org/icis2018/research/Presentations/1},
  abstract   = {By providing knowledge contributions and stimulating future research, review articles (RAs) play a vital role for cumulative knowledge development. Although many papers cite RAs, it is rarely transparent to which degree citation impact represents perfunctory citations as opposed to a deeper engagement with a RA’s knowledge contributions. This distinction between perfunctory and ideational impact has largely been neglected in the literature arguably because of the manual effort required for qualitative analysis. Against this background, our study aims at developing automated classifiers of ideational impact of IS RAs. We propose a machine learning model based on natural language processing to evaluate the feasibility of automated analyses. The evaluation results provide evidence for an effective and scalable classification approach that presents a reliable and reproducible solution to the ideational impact classification problem. We discuss implications for improving the capabilities of understanding how IS scholars build on their field’s body of knowledge.}, author+an:orcid               = {0000-0003-2682-8036;0000-0003-3926-7717;0000-0003-3794-1413}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Prester, Julian
AU  - Wagner, Gerit
AU  - Schryen, Guido
TI  - Classifying the Ideational Impact of IS Review Articles - A Natural Language Processing Based Approach
T2  - International Conference on Information Systems
PY  - 2018
SP  - 1
EP  - 17
UR  - https://aisel.aisnet.org/icis2018/research/Presentations/1
ER  - 
```
