---
title: "Contracting Decisions on Digital Markets for Knowledge Work Services: A Qualitative Systematic Review"
date: "2021"
date-format: "YYYY"
categories: ["digital-work"]
keywords: ["digital-work"]
url: "https://aisel.aisnet.org/icis2021/sharing_econ/sharing_econ/6"
outlet: "International Conference on Information Systems"
author: "Prester, Julian and Wagner, Gerit"
authors:
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
citation_key: "PresterWagner2021"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

A growing amount of research is dedicated to digital markets for knowledge work services and contracting decisions as one of their most critical bottlenecks. Large-scale studies with average samples exceeding 144,000 observations have considered over 70 variables explaining contracting decisions. Our review aims to facilitate the convergence towards commonly agreed categories of variables and overarching models of contracting decisions in this context. To mitigate the risk of propagating deflated p-values associated with large sample studies, we propose a robust version of vote-counting techniques. The principal findings of our research suggest that only a few variables related to the client-worker relationship, the bid and individual worker characteristics have a practically significant effect on worker selection, and that auction success is primarily affected by project value and client experience. These findings lay the groundwork for future research that will lead to better explanations of contracting decisions.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/icis2021/sharing_econ/sharing_econ/6" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>



## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Prester, J. &amp; Wagner, G. (2021). Contracting Decisions on Digital Markets for Knowledge Work Services: A Qualitative Systematic Review. *International Conference on Information Systems* 1--17. https://aisel.aisnet.org/icis2021/sharing_econ/sharing_econ/6
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{PresterWagner2021,
  author     = {Prester, Julian and Wagner, Gerit},
  booktitle  = {International Conference on Information Systems},
  title      = {Contracting Decisions on Digital Markets for Knowledge Work Services: A Qualitative Systematic Review},
  year       = {2021},
  pages      = {1--17},
  url        = {https://aisel.aisnet.org/icis2021/sharing_econ/sharing_econ/6},
  abstract   = {A growing amount of research is dedicated to digital markets for knowledge work services and contracting decisions as one of their most critical bottlenecks. Large-scale studies with average samples exceeding 144,000 observations have considered over 70 variables explaining contracting decisions. Our review aims to facilitate the convergence towards commonly agreed categories of variables and overarching models of contracting decisions in this context. To mitigate the risk of propagating deflated p-values associated with large sample studies, we propose a robust version of vote-counting techniques. The principal findings of our research suggest that only a few variables related to the client-worker relationship, the bid and individual worker characteristics have a practically significant effect on worker selection, and that auction success is primarily affected by project value and client experience. These findings lay the groundwork for future research that will lead to better explanations of contracting decisions.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Prester, Julian
AU  - Wagner, Gerit
TI  - Contracting Decisions on Digital Markets for Knowledge Work Services: A Qualitative Systematic Review
T2  - International Conference on Information Systems
PY  - 2021
SP  - 1
EP  - 17
UR  - https://aisel.aisnet.org/icis2021/sharing_econ/sharing_econ/6
ER  - 
```
