---
title: "Classifying the ideational impact of Information Systems review articles: A content-enriched deep learning approach"
date: "2021"
date-format: "YYYY"
categories: ["literature-review", "student-paper"]
keywords: ["literature-review", "student-paper"]
doi: "10.1016/J.DSS.2020.113432"
url: "https://www.sciencedirect.com/science/article/pii/S0167923620301871"
journal.name: "Decision Support Systems"
outlet: "Decision Support Systems"
author: "Prester, Julian and Wagner, Gerit and Schryen, Guido and Hassan, Nik Rushdi"
citation_key: "PresterWagnerSchryenEtAl2021"
---


# Summary

Ideational impact refers to the uptake of a paper's ideas and concepts by subsequent research. It is defined in stark contrast to total citation impact, a measure predominantly used in research evaluation that assumes that all citations are equal. Understanding ideational impact is critical for evaluating research impact and understanding how scientific disciplines build a cumulative tradition. Research has only recently developed automated citation classification techniques to distinguish between different types of citations and generally does not emphasize the conceptual content of the citations and its ideational impact. To address this problem, we develop Deep Content-enriched Ideational Impact Classification (Deep-CENIC) as the first automated approach for ideational impact classification to support researchers' literature search practices. We evaluate Deep-CENIC on 1256 papers citing 24 information systems review articles from the IT business value domain. We show that Deep-CENIC significantly outperforms state-of-the-art benchmark models. We contribute to information systems research by operationalizing the concept of ideational impact, designing a recommender system for academic papers based on deep learning techniques, and empirically exploring the ideational impact in the IT business value domain.

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.1016/J.DSS.2020.113432" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>



## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Prester, J., Wagner, G., Schryen, G., &amp; Hassan, N. R. (2021). Classifying the ideational impact of Information Systems review articles: A content-enriched deep learning approach. *Decision Support Systems* 140, 113432. https://doi.org/10.1016/J.DSS.2020.113432
</p>
</div>


## Citation: BibTeX

```bibtex
@article{PresterWagnerSchryenEtAl2021,
  doi        = {10.1016/J.DSS.2020.113432},
  author     = {Prester, Julian and Wagner, Gerit and Schryen, Guido and Hassan, Nik Rushdi},
  journal    = {Decision Support Systems},
  title      = {Classifying the ideational impact of Information Systems review articles: A content-enriched deep learning approach},
  year       = {2021},
  volume     = {140},
  pages      = {113432},
  url        = {https://www.sciencedirect.com/science/article/pii/S0167923620301871},
  abstract   = {Ideational impact refers to the uptake of a paper's ideas and concepts by subsequent research. It is defined in stark contrast to total citation impact, a measure predominantly used in research evaluation that assumes that all citations are equal. Understanding ideational impact is critical for evaluating research impact and understanding how scientific disciplines build a cumulative tradition. Research has only recently developed automated citation classification techniques to distinguish between different types of citations and generally does not emphasize the conceptual content of the citations and its ideational impact. To address this problem, we develop Deep Content-enriched Ideational Impact Classification (Deep-CENIC) as the first automated approach for ideational impact classification to support researchers' literature search practices. We evaluate Deep-CENIC on 1256 papers citing 24 information systems review articles from the IT business value domain. We show that Deep-CENIC significantly outperforms state-of-the-art benchmark models. We contribute to information systems research by operationalizing the concept of ideational impact, designing a recommender system for academic papers based on deep learning techniques, and empirically exploring the ideational impact in the IT business value domain.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Prester, Julian
AU  - Wagner, Gerit
AU  - Schryen, Guido
AU  - Hassan, Nik Rushdi
TI  - Classifying the ideational impact of Information Systems review articles: A content-enriched deep learning approach
T2  - Decision Support Systems
PY  - 2021
VL  - 140
SP  - 113432
DO  - 10.1016/J.DSS.2020.113432
UR  - https://www.sciencedirect.com/science/article/pii/S0167923620301871
ER  - 
```
