---
title: "Development of two novel face-recognition CAPTCHAs: A security and usability study"
date: "2016"
date-format: "YYYY"
categories: ["it-security", "student-paper"]
keywords: ["it-security", "student-paper"]
doi: "10.1016/J.COSE.2016.03.007"
url: "https://www.sciencedirect.com/science/article/pii/S0167404816300293"
journal.name: "Computers & Security"
outlet: "Computers & Security"
author: "Schryen, Guido and Wagner, Gerit and Schlegel, Alexander"
authors:
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Schlegel, Alexander"
    orcid: "0000-0002-2740-0982"
citation_key: "SchryenWagnerSchlegel2016"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

CAPTCHAs are challenge-response tests that aim at preventing unwanted machines, including bots, from accessing web services while providing easy access for humans. Recent advances in artificial-intelligence based attacks show that the level of security provided by many state-of-the-art text-based CAPTCHAs is declining. At the same time, techniques for distorting and obscuring the text, which are used to maintain the level of security, make text-based CAPTCHAs difficult to solve for humans, and thereby further degrade usability. The need for developing alternative types of CAPTCHAs that improve both the current security and the usability levels has been emphasized widely. With this study, we contribute to research through (1) the development of two new face recognition CAPTCHAs (Farett-Gender and Farett-Gender&Age), (2) the security analysis of both procedures, and (3) the provision of empirical evidence that one of the suggested CAPTCHAs (Farett-Gender) is similar to Google's reCAPTCHA and better than KCAPTCHA concerning effectiveness (error rates), superior to both regarding learnability and satisfaction but not efficiency.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.1016/J.COSE.2016.03.007" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3965653" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Author-copy PDF

<iframe src="/assets/papers/SchryenWagnerSchlegel2016.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.1016/J.COSE.2016.03.007"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.1016/J.COSE.2016.03.007"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.1016/J.COSE.2016.03.007">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Schryen, G., Wagner, G., &amp; Schlegel, A. (2016). Development of two novel face-recognition CAPTCHAs: A security and usability study. *Computers &amp; Security* 60, 95--116. https://doi.org/10.1016/J.COSE.2016.03.007
</p>
</div>


## Citation: BibTeX

```bibtex
@article{SchryenWagnerSchlegel2016,
  doi        = {10.1016/J.COSE.2016.03.007},
  author     = {Schryen, Guido and Wagner, Gerit and Schlegel, Alexander},
  journal    = {Computers & Security},
  title      = {Development of two novel face-recognition CAPTCHAs: A security and usability study},
  year       = {2016},
  volume     = {60},
  pages      = {95--116},
  url        = {https://www.sciencedirect.com/science/article/pii/S0167404816300293},
  abstract   = {CAPTCHAs are challenge-response tests that aim at preventing unwanted machines, including bots, from accessing web services while providing easy access for humans. Recent advances in artificial-intelligence based attacks show that the level of security provided by many state-of-the-art text-based CAPTCHAs is declining. At the same time, techniques for distorting and obscuring the text, which are used to maintain the level of security, make text-based CAPTCHAs difficult to solve for humans, and thereby further degrade usability. The need for developing alternative types of CAPTCHAs that improve both the current security and the usability levels has been emphasized widely. With this study, we contribute to research through (1) the development of two new face recognition CAPTCHAs (Farett-Gender and Farett-Gender&Age), (2) the security analysis of both procedures, and (3) the provision of empirical evidence that one of the suggested CAPTCHAs (Farett-Gender) is similar to Google's reCAPTCHA and better than KCAPTCHA concerning effectiveness (error rates), superior to both regarding learnability and satisfaction but not efficiency.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Schryen, Guido
AU  - Wagner, Gerit
AU  - Schlegel, Alexander
TI  - Development of two novel face-recognition CAPTCHAs: A security and usability study
T2  - Computers & Security
PY  - 2016
VL  - 60
SP  - 95
EP  - 116
DO  - 10.1016/J.COSE.2016.03.007
UR  - https://www.sciencedirect.com/science/article/pii/S0167404816300293
ER  - 
```
