---
title: "Literature Reviews in IS Research - What Can Be Learnt from the Past and Other Fields?"
date: "2017"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
doi: "10.17705/1CAIS.04130"
url: "https://aisel.aisnet.org/cais/vol41/iss1/30"
journal.name: "Communications of the Association for Information Systems"
outlet: "Communications of the Association for Information Systems"
author: "Schryen, Guido and Benlian, Alexander and Rowe, Frantz and Gregor, Shirley and Larsen, Kai R. and Petter, Stacie and Paré, Guy and Wagner, Gerit and Haag, Steffi and Yasasin, Emrah"
authors:
  - name: "Schryen, Guido"
  - name: "Benlian, Alexander"
  - name: "Rowe, Frantz"
  - name: "Gregor, Shirley"
  - name: "Larsen, Kai R."
  - name: "Petter, Stacie"
  - name: "Paré, Guy"
  - name: "Wagner, Gerit"
  - name: "Haag, Steffi"
  - name: "Yasasin, Emrah"
citation_key: "SchryenBenlianRoweEtAl2017"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Literature reviews (LRs) are recognized for their increasing impact in the information systems literature. Methodologists have drawn attention to the question of how we can leverage the value of LRs to preserve and generate knowledge. The panelists who participated in the discussion of “Standalone Literature Reviews in IS Research: What Can Be Learnt from the Past and Other Fields?” at ICIS 2016 in Dublin acknowledged this significant issue and debated 1) what the IS field can learn from other fields and where IS-specific challenges occur, 2) how the IS field should move forward to foster the genre of LRs, and 3) the best practices to train doctoral IS students in publishing LRs. This paper reports the key takeaways of this panel discussion. We provide guidance for IS scholars on how to conduct LRs that contribute to the cumulative knowledge development in and across the IS field to best prepare the next generation of IS scholars.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.17705/1CAIS.04130" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-primary" href="/data/papers/SchryenBenlianRoweEtAl2017.pdf}, author+an:orcid               = {0000-0003-3794-1413;0000-0002-7294-3097;0000-0001-8520-1570;0000-0002-0686-8674;0000-0002-8812-9866;0000-0003-0522-3943;0000-0001-7425-1994;0000-0003-3926-7717;0000-0002-1902-4390;" target="_blank" role="button">
    <i class="bi bi-file-earmark-pdf"></i> Full-text PDF
  </a>
</div>



## Full-text PDF

<iframe src="/data/papers/SchryenBenlianRoweEtAl2017.pdf}, author+an:orcid               = {0000-0003-3794-1413;0000-0002-7294-3097;0000-0001-8520-1570;0000-0002-0686-8674;0000-0002-8812-9866;0000-0003-0522-3943;0000-0001-7425-1994;0000-0003-3926-7717;0000-0002-1902-4390;" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.17705/1CAIS.04130"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.17705/1CAIS.04130"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.17705/1CAIS.04130">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Schryen, G., Benlian, A., Rowe, F., Gregor, S., Larsen, K. R., Petter, S., Paré, G., Wagner, G., Haag, S., &amp; Yasasin, E. (2017). Literature Reviews in IS Research - What Can Be Learnt from the Past and Other Fields?. *Communications of the Association for Information Systems* 41, 759--774. https://doi.org/10.17705/1CAIS.04130
</p>
</div>


## Citation: BibTeX

```bibtex
@article{SchryenBenlianRoweEtAl2017,
  doi        = {10.17705/1CAIS.04130},
  author     = {Schryen, Guido and Benlian, Alexander and Rowe, Frantz and Gregor, Shirley and Larsen, Kai R. and Petter, Stacie and Paré, Guy and Wagner, Gerit and Haag, Steffi and Yasasin, Emrah},
  journal    = {Communications of the Association for Information Systems},
  title      = {Literature Reviews in IS Research - What Can Be Learnt from the Past and Other Fields?},
  year       = {2017},
  volume     = {41},
  pages      = {759--774},
  url        = {https://aisel.aisnet.org/cais/vol41/iss1/30},
  abstract   = {Literature reviews (LRs) are recognized for their increasing impact in the information systems literature. Methodologists have drawn attention to the question of how we can leverage the value of LRs to preserve and generate knowledge. The panelists who participated in the discussion of “Standalone Literature Reviews in IS Research: What Can Be Learnt from the Past and Other Fields?” at ICIS 2016 in Dublin acknowledged this significant issue and debated 1) what the IS field can learn from other fields and where IS-specific challenges occur, 2) how the IS field should move forward to foster the genre of LRs, and 3) the best practices to train doctoral IS students in publishing LRs. This paper reports the key takeaways of this panel discussion. We provide guidance for IS scholars on how to conduct LRs that contribute to the cumulative knowledge development in and across the IS field to best prepare the next generation of IS scholars.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Schryen, Guido
AU  - Benlian, Alexander
AU  - Rowe, Frantz
AU  - Gregor, Shirley
AU  - Larsen, Kai R.
AU  - Petter, Stacie
AU  - Paré, Guy
AU  - Wagner, Gerit
AU  - Haag, Steffi
AU  - Yasasin, Emrah
TI  - Literature Reviews in IS Research - What Can Be Learnt from the Past and Other Fields?
T2  - Communications of the Association for Information Systems
PY  - 2017
VL  - 41
SP  - 759
EP  - 774
DO  - 10.17705/1CAIS.04130
UR  - https://aisel.aisnet.org/cais/vol41/iss1/30
ER  - 
```
