---
title: "A Knowledge Development Perspective on Literature Reviews - Validation of a new Typology in the IS Field"
date: "2020"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
doi: "10.17705/1CAIS.04607"
url: "https://aisel.aisnet.org/cais/vol46/iss1/7"
journal.name: "Communications of the Association for Information Systems"
outlet: "Communications of the Association for Information Systems"
author: "Schryen, Guido and Wagner, Gerit and Benlian, Alexander and Par\u00e9, Guy"
authors:
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Benlian, Alexander"
    orcid: "0000-0002-7294-3097"
  - name: "Par\u00e9, Guy"
    orcid: "0000-0001-7425-1994"
citation_key: "SchryenWagnerBenlianEtAl2020"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Literature reviews (LRs) play an important role in developing domain knowledge in all fields. Yet, we observe insufficient insights into the activities with which LRs actually develop knowledge. To address this important gap, we 1) derive knowledge-building activities from the extant literature on LRs, 2) suggest a knowledge-based LR typology that complements existing typologies, and 3) apply the typology in an empirical study that explores how LRs with different goals and methodologies have contributed to knowledge development. In analyzing 240 LRs published in 40 renowned information systems (IS) journals between 2000 and 2014, we draw a detailed picture of knowledge development that one of the most important genres in the IS field has achieved. With this work, we help to unify extant LR conceptualizations by clarifying and illustrating how they apply different methodologies in a range of knowledge-building activities to achieve their goals with respect to theory.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.17705/1CAIS.04607" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-primary" href="/assets/papers/SchryenWagnerBenlianEtAl2020.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-pdf"></i> Full-text PDF
  </a>
</div>



## Full-text PDF

<iframe src="/assets/papers/SchryenWagnerBenlianEtAl2020.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.17705/1CAIS.04607"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.17705/1CAIS.04607"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.17705/1CAIS.04607">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Schryen, G., Wagner, G., Benlian, A., &amp; Paré, G. (2020). A Knowledge Development Perspective on Literature Reviews - Validation of a new Typology in the IS Field. *Communications of the Association for Information Systems* 46, 134--186. https://doi.org/10.17705/1CAIS.04607
</p>
</div>


## Citation: BibTeX

```bibtex
@article{SchryenWagnerBenlianEtAl2020,
  doi        = {10.17705/1CAIS.04607},
  author     = {Schryen, Guido and Wagner, Gerit and Benlian, Alexander and Paré, Guy},
  journal    = {Communications of the Association for Information Systems},
  title      = {A Knowledge Development Perspective on Literature Reviews - Validation of a new Typology in the IS Field},
  year       = {2020},
  volume     = {46},
  pages      = {134--186},
  url        = {https://aisel.aisnet.org/cais/vol46/iss1/7},
  abstract   = {Literature reviews (LRs) play an important role in developing domain knowledge in all fields. Yet, we observe insufficient insights into the activities with which LRs actually develop knowledge. To address this important gap, we 1) derive knowledge-building activities from the extant literature on LRs, 2) suggest a knowledge-based LR typology that complements existing typologies, and 3) apply the typology in an empirical study that explores how LRs with different goals and methodologies have contributed to knowledge development. In analyzing 240 LRs published in 40 renowned information systems (IS) journals between 2000 and 2014, we draw a detailed picture of knowledge development that one of the most important genres in the IS field has achieved. With this work, we help to unify extant LR conceptualizations by clarifying and illustrating how they apply different methodologies in a range of knowledge-building activities to achieve their goals with respect to theory.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Schryen, Guido
AU  - Wagner, Gerit
AU  - Benlian, Alexander
AU  - Paré, Guy
TI  - A Knowledge Development Perspective on Literature Reviews - Validation of a new Typology in the IS Field
T2  - Communications of the Association for Information Systems
PY  - 2020
VL  - 46
SP  - 134
EP  - 186
DO  - 10.17705/1CAIS.04607
UR  - https://aisel.aisnet.org/cais/vol46/iss1/7
ER  - 
```
