---
title: "Theory of Knowledge for Literature Reviews - An Epistemological Model, Taxonomy and Empirical Analysis of IS Literature"
date: "2015"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
url: "http://aisel.aisnet.org/icis2015/proceedings/ResearchMethods/8"
outlet: "International Conference on Information Systems"
author: "Schryen, Guido and Wagner, Gerit and Benlian, Alexander"
authors:
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Benlian, Alexander"
    orcid: "0000-0002-7294-3097"
citation_key: "SchryenWagnerBenlian2015"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Literature reviews play an important role in the development of knowledge. Yet, we observe a lack of theoretical underpinning of and epistemological insights into how literature reviews can contribute to knowledge creation and have actually contributed in the IS discipline. To address these theoretical and empirical research gaps, we suggest a novel epistemological model of literature reviews. This model allows us to align different contributions of literature reviews with their underlying knowledge conversions - thereby building a bridge between the previously largely unconnected fields of literature reviews and epistemology. We evaluate the appropriateness of the model by conducting an empirical analysis of 173 IS literature reviews which were published in 39 pertinent IS journals between 2000 and 2014. Based on this analysis, we derive an epistemological taxonomy of IS literature reviews, which complements previously suggested typologies.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="http://aisel.aisnet.org/icis2015/proceedings/ResearchMethods/8" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="/assets/papers/SchryenWagnerBenlian2015.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Author-copy PDF

<iframe src="/assets/papers/SchryenWagnerBenlian2015.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Schryen, G., Wagner, G., &amp; Benlian, A. (2015). Theory of Knowledge for Literature Reviews - An Epistemological Model, Taxonomy and Empirical Analysis of IS Literature. *International Conference on Information Systems* 1--22. http://aisel.aisnet.org/icis2015/proceedings/ResearchMethods/8
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{SchryenWagnerBenlian2015,
  author     = {Schryen, Guido and Wagner, Gerit and Benlian, Alexander},
  booktitle  = {International Conference on Information Systems},
  title      = {Theory of Knowledge for Literature Reviews - An Epistemological Model, Taxonomy and Empirical Analysis of IS Literature},
  year       = {2015},
  pages      = {1--22},
  url        = {http://aisel.aisnet.org/icis2015/proceedings/ResearchMethods/8},
  abstract   = {Literature reviews play an important role in the development of knowledge. Yet, we observe a lack of theoretical underpinning of and epistemological insights into how literature reviews can contribute to knowledge creation and have actually contributed in the IS discipline. To address these theoretical and empirical research gaps, we suggest a novel epistemological model of literature reviews. This model allows us to align different contributions of literature reviews with their underlying knowledge conversions - thereby building a bridge between the previously largely unconnected fields of literature reviews and epistemology. We evaluate the appropriateness of the model by conducting an empirical analysis of 173 IS literature reviews which were published in 39 pertinent IS journals between 2000 and 2014. Based on this analysis, we derive an epistemological taxonomy of IS literature reviews, which complements previously suggested typologies.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Schryen, Guido
AU  - Wagner, Gerit
AU  - Benlian, Alexander
TI  - Theory of Knowledge for Literature Reviews - An Epistemological Model, Taxonomy and Empirical Analysis of IS Literature
T2  - International Conference on Information Systems
PY  - 2015
SP  - 1
EP  - 22
UR  - http://aisel.aisnet.org/icis2015/proceedings/ResearchMethods/8
ER  - 
```
