---
title: "Information Systems Design Science Research and Cumulative Knowledge Development - An Exploratory Study"
date: "2018"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
url: "https://aisel.aisnet.org/icis2018/design/Presentations/3"
outlet: "International Conference on Information Systems"
author: "Schuster, Richard and Wagner, Gerit and Schryen, Guido"
authors:
  - name: "Schuster, Richard"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
citation_key: "SchusterWagnerSchryen2018"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Contributing to cumulative knowledge development is a central goal in Information Systems design science research (IS-DSR). IS design theories (ISDTs) have been recognized as a particularly important building block for the accumulation of design- oriented knowledge. Yet, there are limited insights into how follow-up research builds on IS design theories in terms of testing and extending. To address these issues, we present results from the first empirical analysis of how ISDTs have been tested and extended within and beyond IS journals. Our qualitative analysis of papers citing ISDTs uncovers an alarming paucity of follow-up research that builds on these ISDTs. Specifically, the overall number of papers testing and extending any of the selected ISDTs ranges in the single digits. To propose an actionable path forward, we formulate four specific guidelines on how the IS(-DSR) community can facilitate the cumulative extension of the IS knowledge base.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/icis2018/design/Presentations/3" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>



## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Schuster, R., Wagner, G., &amp; Schryen, G. (2018). Information Systems Design Science Research and Cumulative Knowledge Development - An Exploratory Study. *International Conference on Information Systems* 1--17. https://aisel.aisnet.org/icis2018/design/Presentations/3
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{SchusterWagnerSchryen2018,
  author     = {Schuster, Richard and Wagner, Gerit and Schryen, Guido},
  booktitle  = {International Conference on Information Systems},
  title      = {Information Systems Design Science Research and Cumulative Knowledge Development - An Exploratory Study},
  year       = {2018},
  pages      = {1--17},
  url        = {https://aisel.aisnet.org/icis2018/design/Presentations/3},
  abstract   = {Contributing to cumulative knowledge development is a central goal in Information Systems design science research (IS-DSR). IS design theories (ISDTs) have been recognized as a particularly important building block for the accumulation of design- oriented knowledge. Yet, there are limited insights into how follow-up research builds on IS design theories in terms of testing and extending. To address these issues, we present results from the first empirical analysis of how ISDTs have been tested and extended within and beyond IS journals. Our qualitative analysis of papers citing ISDTs uncovers an alarming paucity of follow-up research that builds on these ISDTs. Specifically, the overall number of papers testing and extending any of the selected ISDTs ranges in the single digits. To propose an actionable path forward, we formulate four specific guidelines on how the IS(-DSR) community can facilitate the cumulative extension of the IS knowledge base.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Schuster, Richard
AU  - Wagner, Gerit
AU  - Schryen, Guido
TI  - Information Systems Design Science Research and Cumulative Knowledge Development - An Exploratory Study
T2  - International Conference on Information Systems
PY  - 2018
SP  - 1
EP  - 17
UR  - https://aisel.aisnet.org/icis2018/design/Presentations/3
ER  - 
```
