---
title: "Explaining and Distinguishing Scientific Impact in Information Systems Research"
date: "2019"
date-format: "YYYY"
categories: ["literature-review"]
keywords: ["literature-review"]
author: "Wagner, Gerit"
authors:
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
citation_key: "Wagner2019"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Since its inception, the Information Systems discipline has been striving to develop impactful papers that contribute to cumulative knowledge development. Yet, there is a surprising lack of insights on how scientific impact can be accomplished and to which extent this impact represents a substantial engagement with, and extension of the knowledge contributions of the original papers. Especially for review articles and design science research, there are both competing conceptions of what makes these papers impactful and a lack of empirical evidence that would inform this debate. Furthermore, there is a latent skepticism as to whether this sometimes staggering impact of review articles actually represents knowledge development. In a similar way, it is unclear how and to which extent design science research has stimulated meaningful, cumulative knowledge development in information systems. The goal of this thesis is therefore to (1) explain and to (2) distinguish the scientific impact of review articles and design science research. Specifically, the first goal considers overall scientific impact as the dependent variable whose association with antecedent factors is analyzed by regression methodologies. The second goal zooms in on the concept of scientific impact and considers it as a relation between citing and cited papers that is explored through methodologies of manual content analysis and machine- learning classification.<br>With Paper 1, I develop the foundation of knowledge development through review articles by crystallizing their contributions and aligning them with their underlying knowledge conver- sion processes in an overarching framework. This framework is based on the abstraction and codification of knowledge and thereby integrates two essential dimensions of knowledge devel- opment. Overall, the foundation developed in the first paper informs the underlying conception of knowledge development of both review articles and citing papers.<br>Addressing the first goal, Papers 2 and 3 develop and test scientometric impact models ex- plaining the scientific impact of review articles and design science research, respectively. Beyond common control variables related to the journal and author level, they offer distinct insights for each type of paper. For review articles, I identify strong effects related to methodological transparency and the development of a research agenda, which vary depending on the type of review. For design science research, I show that theorization and novelty drive scientific impact.<br>Concerning the second goal, Papers 4 and 5 distinguish different types of scientific impact of review articles and design science research, respectively. To analyze the different types of impact that review articles have on their overwhelming number of citing papers, I develop machine learning classifiers. Specifically, I distinguish ideational impact, which corresponds to a substantial engagement with and development of the knowledge contributions of the review article, from perfunctory impact, which corresponds to more trivial connections to the review article. In a similar, though not automated way, I analyze the types of impact of information systems design theories, a particular type of design science research. These analyses primarily focus on whether follow-up research tests and extends these theories. Based on our content analysis, I identify an alarming paucity of follow-up research in this area and develop specific guidelines for the design science community to address this challenge.<br>The thesis concludes with an overview of the research contributions, implications for research practice, future research opportunities, and final remarks.

:::


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G. (2019). Explaining and Distinguishing Scientific Impact in Information Systems Research. 1--217.
</p>
</div>


## Citation: BibTeX

```bibtex
@phdthesis{Wagner2019,
  author     = {Wagner, Gerit},
  title      = {Explaining and Distinguishing Scientific Impact in Information Systems Research},
  year       = {2019},
  pages      = {1--217},
  abstract   = {Since its inception, the Information Systems discipline has been striving to develop impactful papers that contribute to cumulative knowledge development. Yet, there is a surprising lack of insights on how scientific impact can be accomplished and to which extent this impact represents a substantial engagement with, and extension of the knowledge contributions of the original papers. Especially for review articles and design science research, there are both competing conceptions of what makes these papers impactful and a lack of empirical evidence that would inform this debate. Furthermore, there is a latent skepticism as to whether this sometimes staggering impact of review articles actually represents knowledge development. In a similar way, it is unclear how and to which extent design science research has stimulated meaningful, cumulative knowledge development in information systems. The goal of this thesis is therefore to (1) explain and to (2) distinguish the scientific impact of review articles and design science research. Specifically, the first goal considers overall scientific impact as the dependent variable whose association with antecedent factors is analyzed by regression methodologies. The second goal zooms in on the concept of scientific impact and considers it as a relation between citing and cited papers that is explored through methodologies of manual content analysis and machine- learning classification.<br>With Paper 1, I develop the foundation of knowledge development through review articles by crystallizing their contributions and aligning them with their underlying knowledge conver- sion processes in an overarching framework. This framework is based on the abstraction and codification of knowledge and thereby integrates two essential dimensions of knowledge devel- opment. Overall, the foundation developed in the first paper informs the underlying conception of knowledge development of both review articles and citing papers.<br>Addressing the first goal, Papers 2 and 3 develop and test scientometric impact models ex- plaining the scientific impact of review articles and design science research, respectively. Beyond common control variables related to the journal and author level, they offer distinct insights for each type of paper. For review articles, I identify strong effects related to methodological transparency and the development of a research agenda, which vary depending on the type of review. For design science research, I show that theorization and novelty drive scientific impact.<br>Concerning the second goal, Papers 4 and 5 distinguish different types of scientific impact of review articles and design science research, respectively. To analyze the different types of impact that review articles have on their overwhelming number of citing papers, I develop machine learning classifiers. Specifically, I distinguish ideational impact, which corresponds to a substantial engagement with and development of the knowledge contributions of the review article, from perfunctory impact, which corresponds to more trivial connections to the review article. In a similar, though not automated way, I analyze the types of impact of information systems design theories, a particular type of design science research. These analyses primarily focus on whether follow-up research tests and extends these theories. Based on our content analysis, I identify an alarming paucity of follow-up research in this area and develop specific guidelines for the design science community to address this challenge.<br>The thesis concludes with an overview of the research contributions, implications for research practice, future research opportunities, and final remarks.},
  school     = {Universität Regensburg}
}
```


## Citation: RIS

```bibtex
TY  - THES
AU  - Wagner, Gerit
TI  - Explaining and Distinguishing Scientific Impact in Information Systems Research
PY  - 2019
SP  - 1
EP  - 217
ER  - 
```
