---
title: "Exploring the Scientific Impact of Information Systems Design Science Research"
date: "2021"
date-format: "YYYY"
categories: ["literature-review", "student-paper"]
keywords: ["literature-review", "student-paper"]
doi: "10.17705/1CAIS.04837"
url: "https://aisel.aisnet.org/cais/vol48/iss1/37"
journal.name: "Communications of the Association for Information Systems"
outlet: "Communications of the Association for Information Systems"
author: "Wagner, Gerit and Prester, Julian and Schryen, Guido"
authors:
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
citation_key: "WagnerPresterSchryen2021"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

While design science research has established its position as a prominent field of research in the IS community, there is a lack of transparency regarding the impact of recent information systems design science research (IS DSR) papers. This lack of insight arguably poses challenges to an informed discourse and limits our ability to communicate the progress that IS DSR has achieved. Therefore, after mapping impactful IS DSR papers, we develop a scientometric study to address the lack of insights into factors that affect the scientific impact of IS DSR papers in top IS journals. In this study, we focus on active, IS-specific DSR areas and consider papers published in the AIS Senior Scholars’ basket of journals between 2004 and 2014. Specifically, we develop a model that explores factors that affect IS DSR papers’ scientific impact. Our findings show that theorization and novelty significantly explain scientific impact. We discuss our work’s implications and derive recommendations intended to shape future knowledge creation in IS DSR.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.17705/1CAIS.04837" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-primary" href="/assets/papers/WagnerPresterSchryen2021.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-pdf"></i> Full-text PDF
  </a>
</div>



## Full-text PDF

<iframe src="/assets/papers/WagnerPresterSchryen2021.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.17705/1CAIS.04837"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.17705/1CAIS.04837"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.17705/1CAIS.04837">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G., Prester, J., &amp; Schryen, G. (2021). Exploring the Scientific Impact of Information Systems Design Science Research. *Communications of the Association for Information Systems* 48, 379--423. https://doi.org/10.17705/1CAIS.04837
</p>
</div>


## Citation: BibTeX

```bibtex
@article{WagnerPresterSchryen2021,
  doi        = {10.17705/1CAIS.04837},
  author     = {Wagner, Gerit and Prester, Julian and Schryen, Guido},
  journal    = {Communications of the Association for Information Systems},
  title      = {Exploring the Scientific Impact of Information Systems Design Science Research},
  year       = {2021},
  volume     = {48},
  pages      = {379--423},
  url        = {https://aisel.aisnet.org/cais/vol48/iss1/37},
  abstract   = {While design science research has established its position as a prominent field of research in the IS community, there is a lack of transparency regarding the impact of recent information systems design science research (IS DSR) papers. This lack of insight arguably poses challenges to an informed discourse and limits our ability to communicate the progress that IS DSR has achieved. Therefore, after mapping impactful IS DSR papers, we develop a scientometric study to address the lack of insights into factors that affect the scientific impact of IS DSR papers in top IS journals. In this study, we focus on active, IS-specific DSR areas and consider papers published in the AIS Senior Scholars’ basket of journals between 2004 and 2014. Specifically, we develop a model that explores factors that affect IS DSR papers’ scientific impact. Our findings show that theorization and novelty significantly explain scientific impact. We discuss our work’s implications and derive recommendations intended to shape future knowledge creation in IS DSR.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Wagner, Gerit
AU  - Prester, Julian
AU  - Schryen, Guido
TI  - Exploring the Scientific Impact of Information Systems Design Science Research
T2  - Communications of the Association for Information Systems
PY  - 2021
VL  - 48
SP  - 379
EP  - 423
DO  - 10.17705/1CAIS.04837
UR  - https://aisel.aisnet.org/cais/vol48/iss1/37
ER  - 
```
