---
title: "Teaching Tip Rethinking How We Teach Git: Pedagogical Recommendations and Practical Strategies for the Information Systems Curriculum"
date: "2025"
date-format: "YYYY"
categories: ["data-management", "student-paper"]
keywords: ["data-management", "student-paper"]
doi: "10.62273/BTKM5634"
url: "https://jise.org/Volume36/n1/JISE2025v36n1pp1-12.html"
journal.name: "Journal of Information Systems Education"
outlet: "Journal of Information Systems Education"
author: "Wagner, Gerit and Thurner, Laureen"
authors:
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Thurner, Laureen"
    orcid: "0009-0000-5716-5816"
citation_key: "WagnerThurner2025"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Git, as the leading version-control system, is frequently employed by software developers, digital product managers, and knowledge workers. Information systems (IS) students aspiring to fill software engineering, management, or research positions would therefore benefit from familiarity with Git. However, teaching Git effectively can be challenging, as students in IS and other disciplines report themselves overwhelmed by the plethora of Git’s detailed commands and options, including those involved in local setup and secure shell (SSH) connections. From our view, such technical considerations distract students, and even prevent them from developing a deeper understanding of the Git model and its underlying concepts. Ideally, teaching efforts should convey a solid understanding of the Git model and thereby enable students to ask the right questions and look up the relevant commands. With this teaching tip, we therefore challenge the common approach to organizing Git teaching materials. In particular, we draw on established pedagogical theory to propose a novel approach that employs a new, macro-level ordering of contents beginning with the concept of branches and then proceeding to committing and collaboration. We present several practical strategies that make this approach feasible. In addition, we recommend that teachers clearly separate conceptual from applied learning and present the more challenging transfer questions at the end of the course. Our hope is to stimulate reflection on the most effective ways to teach Git to future professionals.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://doi.org/10.62273/BTKM5634" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-primary" href="/data/papers/WagnerThurner2025.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-pdf"></i> Open access PDF
  </a>
</div>



## Additional resources

- Summary / overview: <https://digital-work-lab.github.io/rethink-git-teaching/>


## Open access PDF

<iframe src="/data/papers/WagnerThurner2025.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>



```{=html}
<div class="metrics-row">

  <!-- Altmetric badge -->
  <div class="metric">
    <div class="altmetric-embed"
         data-badge-type="donut"
         data-badge-popover="right"
         data-doi="10.62273/BTKM5634"
         data-hide-no-mentions="true">
    </div>
  </div>

  <!-- Dimensions badge -->
  <div class="metric">
    <span class="__dimensions_badge_embed__"
          data-doi="10.62273/BTKM5634"
          data-style="small_circle"
          data-hide-zero-citations="true"
          data-legend="hover-right">
    </span>
  </div>

  <!-- scite.ai badge -->
  <div class="metric">
    <div class="scite-badge"
         data-doi="10.62273/BTKM5634">
    </div>
  </div>

</div>
```


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G. &amp; Thurner, L. (2025). Teaching Tip Rethinking How We Teach Git: Pedagogical Recommendations and Practical Strategies for the Information Systems Curriculum. *Journal of Information Systems Education* 36(1), 1--12. https://doi.org/10.62273/BTKM5634
</p>
</div>


## Citation: BibTeX

```bibtex
@article{WagnerThurner2025,
  doi        = {10.62273/BTKM5634},
  author     = {Wagner, Gerit and Thurner, Laureen},
  journal    = {Journal of Information Systems Education},
  title      = {Teaching Tip Rethinking How We Teach Git: Pedagogical Recommendations and Practical Strategies for the Information Systems Curriculum},
  year       = {2025},
  volume     = {36},
  number     = {1},
  pages      = {1--12},
  url        = {https://jise.org/Volume36/n1/JISE2025v36n1pp1-12.html},
  abstract   = {Git, as the leading version-control system, is frequently employed by software developers, digital product managers, and knowledge workers. Information systems (IS) students aspiring to fill software engineering, management, or research positions would therefore benefit from familiarity with Git. However, teaching Git effectively can be challenging, as students in IS and other disciplines report themselves overwhelmed by the plethora of Git’s detailed commands and options, including those involved in local setup and secure shell (SSH) connections. From our view, such technical considerations distract students, and even prevent them from developing a deeper understanding of the Git model and its underlying concepts. Ideally, teaching efforts should convey a solid understanding of the Git model and thereby enable students to ask the right questions and look up the relevant commands. With this teaching tip, we therefore challenge the common approach to organizing Git teaching materials. In particular, we draw on established pedagogical theory to propose a novel approach that employs a new, macro-level ordering of contents beginning with the concept of branches and then proceeding to committing and collaboration. We present several practical strategies that make this approach feasible. In addition, we recommend that teachers clearly separate conceptual from applied learning and present the more challenging transfer questions at the end of the course. Our hope is to stimulate reflection on the most effective ways to teach Git to future professionals.}
}
```


## Citation: RIS

```bibtex
TY  - JOUR
AU  - Wagner, Gerit
AU  - Thurner, Laureen
TI  - Teaching Tip Rethinking How We Teach Git: Pedagogical Recommendations and Practical Strategies for the Information Systems Curriculum
T2  - Journal of Information Systems Education
PY  - 2025
VL  - 36
IS  - 1
SP  - 1
EP  - 12
DO  - 10.62273/BTKM5634
UR  - https://jise.org/Volume36/n1/JISE2025v36n1pp1-12.html
ER  - 
```
