---
title: "Factors Affecting the Scientific Impact of Literature Reviews - A Scientometric Study"
date: "2016"
date-format: "YYYY"
categories: ["literature-review", "student-paper"]
keywords: ["literature-review", "student-paper"]
url: "http://aisel.aisnet.org/icis2016/GeneralIS/Presentations/9"
outlet: "International Conference on Information Systems"
author: "Wagner, Gerit and Prester, Julian and Roche, Maria Patricia and Benlian, Alexander and Schryen, Guido"
authors:
  - name: "Wagner, Gerit"
  - name: "Prester, Julian"
  - name: "Roche, Maria Patricia"
  - name: "Benlian, Alexander"
  - name: "Schryen, Guido"
citation_key: "WagnerPresterRocheEtAl2016"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Standalone literature reviews are fundamental in every scientific discipline. Their value is reflected by a profound scientific impact in terms of citations. Although previous empirical research has shown that this impact has a large variance, it is largely unknown which specific factors influence the impact of literature reviews. Against this background, the purpose of our study is to shed light on the driving factors that make a difference in the scientific impact of literature reviews. Our analysis of an exhaustive set of 214 IS literature reviews reveals that factors on the author level (e.g., expertise, collaboration, and conceptual feedback) and on the article level (e.g., methodological rigor) are significant and robust predictors of scientific impact over and above journal level factors. These insights enhance our understanding of what distinguishes highly cited literature reviews. In so doing, our study informs future guidelines on literature reviews and provides insights for prospective authors.}, author+an:orcid               = {0000-0003-3926-7717;0000-0003-2682-8036;0000-0003-4941-5402;0000-0002-7294-3097;0000-0003-3794-1413

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="http://aisel.aisnet.org/icis2016/GeneralIS/Presentations/9" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="/data/papers/WagnerPresterRocheEtAl2016.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Author-copy PDF

<iframe src="/data/papers/WagnerPresterRocheEtAl2016.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G., Prester, J., Roche, M. P., Benlian, A., &amp; Schryen, G. (2016). Factors Affecting the Scientific Impact of Literature Reviews - A Scientometric Study. *International Conference on Information Systems* 1--24. http://aisel.aisnet.org/icis2016/GeneralIS/Presentations/9
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{WagnerPresterRocheEtAl2016,
  author     = {Wagner, Gerit and Prester, Julian and Roche, Maria Patricia and Benlian, Alexander and Schryen, Guido},
  booktitle  = {International Conference on Information Systems},
  title      = {Factors Affecting the Scientific Impact of Literature Reviews - A Scientometric Study},
  year       = {2016},
  pages      = {1--24},
  url        = {http://aisel.aisnet.org/icis2016/GeneralIS/Presentations/9},
  abstract   = {Standalone literature reviews are fundamental in every scientific discipline. Their value is reflected by a profound scientific impact in terms of citations. Although previous empirical research has shown that this impact has a large variance, it is largely unknown which specific factors influence the impact of literature reviews. Against this background, the purpose of our study is to shed light on the driving factors that make a difference in the scientific impact of literature reviews. Our analysis of an exhaustive set of 214 IS literature reviews reveals that factors on the author level (e.g., expertise, collaboration, and conceptual feedback) and on the article level (e.g., methodological rigor) are significant and robust predictors of scientific impact over and above journal level factors. These insights enhance our understanding of what distinguishes highly cited literature reviews. In so doing, our study informs future guidelines on literature reviews and provides insights for prospective authors.}, author+an:orcid               = {0000-0003-3926-7717;0000-0003-2682-8036;0000-0003-4941-5402;0000-0002-7294-3097;0000-0003-3794-1413}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Wagner, Gerit
AU  - Prester, Julian
AU  - Roche, Maria Patricia
AU  - Benlian, Alexander
AU  - Schryen, Guido
TI  - Factors Affecting the Scientific Impact of Literature Reviews - A Scientometric Study
T2  - International Conference on Information Systems
PY  - 2016
SP  - 1
EP  - 24
UR  - http://aisel.aisnet.org/icis2016/GeneralIS/Presentations/9
ER  - 
```
