---
title: "Exploring the Scientific Impact of Information Systems Design Science Research - A Scientometric Study"
date: "2017"
date-format: "YYYY"
categories: ["literature-review", "student-paper"]
keywords: ["literature-review", "student-paper"]
url: "http://aisel.aisnet.org/icis2017/ResearchMethods/Presentations/8"
outlet: "International Conference on Information Systems"
author: "Wagner, Gerit and Prester, Julian and Schryen, Guido"
citation_key: "WagnerPresterSchryen2017"
---


# Summary

Design science is a fundamental research stream that contends its position in the information systems discipline. While ongoing debates address the relative importance of design science contributions in the information systems community, insights into the scientific impact of design science research (DSR) are missing and this lack of understanding arguably poses challenges to an informed discourse. To identify the most influential papers and those factors that explain their scientific impact, this paper presents an exploratory study of the scientific impact of DSR papers published in the AIS Senior Scholars' Basket of Journals. We uncover the current DSR landscape by taking stock of influential papers and theories and develop a model to explain the scientific impact of DSR papers. Our findings show that scientific impact is significantly explained by theorization and novelty. We discuss how the implications of our work can be projected on the overarching discourse on DSR.

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="http://aisel.aisnet.org/icis2017/ResearchMethods/Presentations/8" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>



## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G., Prester, J., &amp; Schryen, G. (2017). Exploring the Scientific Impact of Information Systems Design Science Research - A Scientometric Study. *International Conference on Information Systems* 1--24. http://aisel.aisnet.org/icis2017/ResearchMethods/Presentations/8
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{WagnerPresterSchryen2017,
  author     = {Wagner, Gerit and Prester, Julian and Schryen, Guido},
  booktitle  = {International Conference on Information Systems},
  title      = {Exploring the Scientific Impact of Information Systems Design Science Research - A Scientometric Study},
  year       = {2017},
  pages      = {1--24},
  url        = {http://aisel.aisnet.org/icis2017/ResearchMethods/Presentations/8},
  abstract   = {Design science is a fundamental research stream that contends its position in the information systems discipline. While ongoing debates address the relative importance of design science contributions in the information systems community, insights into the scientific impact of design science research (DSR) are missing and this lack of understanding arguably poses challenges to an informed discourse. To identify the most influential papers and those factors that explain their scientific impact, this paper presents an exploratory study of the scientific impact of DSR papers published in the AIS Senior Scholars' Basket of Journals. We uncover the current DSR landscape by taking stock of influential papers and theories and develop a model to explain the scientific impact of DSR papers. Our findings show that scientific impact is significantly explained by theorization and novelty. We discuss how the implications of our work can be projected on the overarching discourse on DSR.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Wagner, Gerit
AU  - Prester, Julian
AU  - Schryen, Guido
TI  - Exploring the Scientific Impact of Information Systems Design Science Research - A Scientometric Study
T2  - International Conference on Information Systems
PY  - 2017
SP  - 1
EP  - 24
UR  - http://aisel.aisnet.org/icis2017/ResearchMethods/Presentations/8
ER  - 
```
