---
title: "Information Systems Research on Digital Platforms for Knowledge Work - A Scoping Review"
date: "2019"
date-format: "YYYY"
categories: ["digital-work"]
keywords: ["digital-work"]
url: "https://aisel.aisnet.org/icis2019/future_of_work/future_work/2"
outlet: "International Conference on Information Systems"
author: "Wagner, Gerit and Prester, Julian"
authors:
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
citation_key: "WagnerPrester2019"
free_fulltext: true
self_archiving_possible_1y: false
self_archiving_possible_2y: false
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Digital platforms for knowledge work, such as Upwork, Freelancer.com and Amazon Mechanical Turk connect clients with millions of workers for a range of tasks, including software development, virtual assistance, and micro-tasks. Information systems research on this emergent phenomenon has gained traction in recent years regarding publication volume and research diversity. To identify relevant papers, to distinguish them from related types of digital platforms, and to guide future research, we conducted a scoping review, focusing on the information systems literature. Results are structured according to a theoretical framework of the knowledge work process, covering three phases: Worker-client matching, committing for future action, and executing commitments. While the first phase has been analyzed extensively, we contend that the main phases of the knowledge work process have received scant attention. In this emergent stage of extant research, our review identifies promising research directions to guide prospective studies.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/icis2019/future_of_work/future_work/2" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
  <a class="btn btn-sm btn-outline-secondary me-2" href="/data/papers/WagnerPrester2019.pdf" target="_blank" role="button">
    <i class="bi bi-file-earmark-text"></i> Author copy
  </a>
</div>



## Additional resources

- Appendix / supplementary materials: <https://github.com/fs-ise/dpkw-lr-appendix>


## Author-copy PDF

<iframe src="/data/papers/WagnerPrester2019.pdf" width="100%" height="800px" style="border: 1px solid #ccc;">
  This browser does not support PDFs. Please use the button above to download the PDF.
</iframe>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G. &amp; Prester, J. (2019). Information Systems Research on Digital Platforms for Knowledge Work - A Scoping Review. *International Conference on Information Systems* 1--17. https://aisel.aisnet.org/icis2019/future_of_work/future_work/2
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{WagnerPrester2019,
  author     = {Wagner, Gerit and Prester, Julian},
  booktitle  = {International Conference on Information Systems},
  title      = {Information Systems Research on Digital Platforms for Knowledge Work - A Scoping Review},
  year       = {2019},
  pages      = {1--17},
  url        = {https://aisel.aisnet.org/icis2019/future_of_work/future_work/2},
  abstract   = {Digital platforms for knowledge work, such as Upwork, Freelancer.com and Amazon Mechanical Turk connect clients with millions of workers for a range of tasks, including software development, virtual assistance, and micro-tasks. Information systems research on this emergent phenomenon has gained traction in recent years regarding publication volume and research diversity. To identify relevant papers, to distinguish them from related types of digital platforms, and to guide future research, we conducted a scoping review, focusing on the information systems literature. Results are structured according to a theoretical framework of the knowledge work process, covering three phases: Worker-client matching, committing for future action, and executing commitments. While the first phase has been analyzed extensively, we contend that the main phases of the knowledge work process have received scant attention. In this emergent stage of extant research, our review identifies promising research directions to guide prospective studies.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Wagner, Gerit
AU  - Prester, Julian
TI  - Information Systems Research on Digital Platforms for Knowledge Work - A Scoping Review
T2  - International Conference on Information Systems
PY  - 2019
SP  - 1
EP  - 17
UR  - https://aisel.aisnet.org/icis2019/future_of_work/future_work/2
ER  - 
```
