---
title: "Designing a Novel Strategy for Exploring Literature Corpora"
date: "2020"
date-format: "YYYY"
categories: ["literature-review", "student-paper"]
keywords: ["literature-review", "student-paper"]
url: "https://aisel.aisnet.org/ecis2020_rp/44"
outlet: "European Conference on Information Systems"
author: "Wagner, Gerit and Empl, Philip and Schryen, Guido"
authors:
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Empl, Philip"
    orcid: "0000-0002-7616-5931"
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
citation_key: "WagnerEmplSchryen2020"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Understanding a new literature corpus can be a grueling experience for junior scholars. Nevertheless, corresponding guidelines have not been updated for decades. We contend that the traditional strategy of skimming all papers and reading selected papers afterwards needs to be revised. Therefore, we design a new strategy that guides the overall exploratory process by prioritizing influential papers for initial reading, followed by skimming the remaining papers. Consistent with schemata theory, starting with indepth reading allows readers to acquire more substantial prior content schemata, which are representative for the literature corpus and useful in the following skimming process. To this end, we develop a prototype that identifies the influential papers from a set of PDFs, which is illustrated in a case study in the IT business value domain. With the new strategy, we envision a more efficient process of exploring unknown literature corpora.

:::

<div class="text-center my-3">
  <a class="btn btn-sm btn-outline-secondary me-2" href="https://aisel.aisnet.org/ecis2020_rp/44" target="_blank" role="button">
    <i class="bi bi-box-arrow-up-right"></i> Article / DOI link
  </a>
</div>



## Additional resources

- Code / source: <https://github.com/digital-work-lab/enlit>


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Wagner, G., Empl, P., &amp; Schryen, G. (2020). Designing a Novel Strategy for Exploring Literature Corpora. *European Conference on Information Systems* 1--17. https://aisel.aisnet.org/ecis2020_rp/44
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{WagnerEmplSchryen2020,
  author     = {Wagner, Gerit and Empl, Philip and Schryen, Guido},
  booktitle  = {European Conference on Information Systems},
  title      = {Designing a Novel Strategy for Exploring Literature Corpora},
  year       = {2020},
  pages      = {1--17},
  url        = {https://aisel.aisnet.org/ecis2020_rp/44},
  abstract   = {Understanding a new literature corpus can be a grueling experience for junior scholars. Nevertheless, corresponding guidelines have not been updated for decades. We contend that the traditional strategy of skimming all papers and reading selected papers afterwards needs to be revised. Therefore, we design a new strategy that guides the overall exploratory process by prioritizing influential papers for initial reading, followed by skimming the remaining papers. Consistent with schemata theory, starting with indepth reading allows readers to acquire more substantial prior content schemata, which are representative for the literature corpus and useful in the following skimming process. To this end, we develop a prototype that identifies the influential papers from a set of PDFs, which is illustrated in a case study in the IT business value domain. With the new strategy, we envision a more efficient process of exploring unknown literature corpora.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Wagner, Gerit
AU  - Empl, Philip
AU  - Schryen, Guido
TI  - Designing a Novel Strategy for Exploring Literature Corpora
T2  - European Conference on Information Systems
PY  - 2020
SP  - 1
EP  - 17
UR  - https://aisel.aisnet.org/ecis2020_rp/44
ER  - 
```
