---
title: "Towards an Economic Approach to Identity and Access Management Systems Using Decision Theory"
date: "2015"
date-format: "YYYY"
categories: ["it-security", "student-paper"]
keywords: ["it-security", "student-paper"]
outlet: "2nd International Workshop on Security in Highly Connected IT Systems"
author: "Weish\u00e4upl, Eva and Kunz, Michael and Yasasin, Emrah and Wagner, Gerit and Prester, Julian and Schryen, Guido and Pernul, G\u00fcnther"
authors:
  - name: "Weish\u00e4upl, Eva"
  - name: "Kunz, Michael"
  - name: "Yasasin, Emrah"
  - name: "Wagner, Gerit"
    orcid: "0000-0003-3926-7717"
  - name: "Prester, Julian"
    orcid: "0000-0003-2682-8036"
  - name: "Schryen, Guido"
    orcid: "0000-0003-3794-1413"
  - name: "Pernul, G\u00fcnther"
    orcid: "0000-0003-1338-9003"
citation_key: "WeishauplKunzYasasinEtAl2015"
format:
  html:
    include-after-body: ../../assets/metrics-scripts.html
---


# Summary

::: { .justify }

Nowadays, providing employees with failure-free access to various systems, applications and services is a crucial factor for organizations’ success as disturbances potentially inhibit smooth workflows and thereby harm productivity. However, it is a challenging task to assign access rights to employees’ accounts within a satisfying time frame. In addition, the management of multiple accounts and identities can be very onerous and time consuming for the responsible administrator and therefore expensive for the organization. In order to meet these challenges, firms decide to invest in introducing an Identity and Access Management System (IAMS) that supports the organization by using policies to assign permissions to accounts, groups, and roles. In practice, since various versions of IAMSs exist, it is a challenging task to decide upon introduction of an IAMS. The following study proposes a first attempt of a decision support model for practitioners which considers four alternatives: Introduction of an IAMS with Role-based Access Control (RBAC) or without and no introduction of IAMS again with or without RBAC. To underpin the practical applicability of the proposed model, we parametrize and operationalize it based on a real world use case using input from an expert interview.

:::


## Citation (APA style)

<div class="apa-citation">
<p style="text-indent:-2.5em; margin-left:2.5em;">
Weishäupl, E., Kunz, M., Yasasin, E., Wagner, G., Prester, J., Schryen, G., &amp; Pernul, G. (2015). Towards an Economic Approach to Identity and Access Management Systems Using Decision Theory. *2nd International Workshop on Security in Highly Connected IT Systems* 1--5.
</p>
</div>


## Citation: BibTeX

```bibtex
@inproceedings{WeishauplKunzYasasinEtAl2015,
  author     = {Weishäupl, Eva and Kunz, Michael and Yasasin, Emrah and Wagner, Gerit and Prester, Julian and Schryen, Guido and Pernul, Günther},
  booktitle  = {2nd International Workshop on Security in Highly Connected IT Systems},
  title      = {Towards an Economic Approach to Identity and Access Management Systems Using Decision Theory},
  year       = {2015},
  pages      = {1--5},
  abstract   = {Nowadays, providing employees with failure-free access to various systems, applications and services is a crucial factor for organizations’ success as disturbances potentially inhibit smooth workflows and thereby harm productivity. However, it is a challenging task to assign access rights to employees’ accounts within a satisfying time frame. In addition, the management of multiple accounts and identities can be very onerous and time consuming for the responsible administrator and therefore expensive for the organization. In order to meet these challenges, firms decide to invest in introducing an Identity and Access Management System (IAMS) that supports the organization by using policies to assign permissions to accounts, groups, and roles. In practice, since various versions of IAMSs exist, it is a challenging task to decide upon introduction of an IAMS. The following study proposes a first attempt of a decision support model for practitioners which considers four alternatives: Introduction of an IAMS with Role-based Access Control (RBAC) or without and no introduction of IAMS again with or without RBAC. To underpin the practical applicability of the proposed model, we parametrize and operationalize it based on a real world use case using input from an expert interview.}
}
```


## Citation: RIS

```bibtex
TY  - CONF
AU  - Weishäupl, Eva
AU  - Kunz, Michael
AU  - Yasasin, Emrah
AU  - Wagner, Gerit
AU  - Prester, Julian
AU  - Schryen, Guido
AU  - Pernul, Günther
TI  - Towards an Economic Approach to Identity and Access Management Systems Using Decision Theory
T2  - 2nd International Workshop on Security in Highly Connected IT Systems
PY  - 2015
SP  - 1
EP  - 5
ER  - 
```
